const all_pages = {
    "Ablauf":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html",
    "Ahai":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#4el",
    "Ak":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Wirinima/Wirinima.html#ddhz",
    "Akamah":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Wirinima/Wirinima.html#akamah",
    "Amaka":"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Amaka/Amaka.html",
    "Amaka (Regelwerk)":"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Amaka/Amaka_Regelwerk.html",
    "Angriff (Kampf)":"https://joelbondy.github.io/Suruthua/Regelwerk/Kampf/Kampf.html#ang",
    "Attribute":"https://joelbondy.github.io/Suruthua/Regelwerk/Charakterbogen/Attribute.html",
    "Augling":"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Augling/Augling.html",
    "Augling (Regelwerk)":"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Augling/Augling_Regelwerk.html",
    'Avzitil':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Avzitil/Avzitil.html",
    'Avztil (Regelwerk)':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Avzitil/Avzitil_Regelwerk.html",
    "Ära":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html#kaera",
    "Baumgeister":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#baumgeister",
    'Berethao':"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Berethao/Berethao.html",
    "Berge von Loromoth":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Loromoth/Loromoth.html#berge",
    'Blauer Traum':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Blauer_Traum/Blauer_Traum.html",
    'Blib':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Blib/Blib.html",
    'Blutborke':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Blutborke/Blutborke.html",
    "Bodengolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#bodeng",
    "Chapaka/Chapakay":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Chapaka/Chapaka.html",
    'Charakterbogen':"https://joelbondy.github.io/Suruthua/Regelwerk/Charakterbogen/Charakterbogen.html",
    "Cul'thur":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/VerfluchteWesen/Culthur/Culthur.html",
    "Cureg":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Loromoth/Loromoth.html#cureg",
    "Drah":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Xaraton/Xaraton.html#draskenlande",
    "Dras und Drus":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Loromoth/Loromoth.html#drasdrus",
    "Dras und Drus Feldzug":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/WichtigeDaten.html#ddfeldzug",
    'Draske':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Draske/Draske.html",
    'Draske (Regelwerk)':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Draske/Draske_Regelwerk.html",
    "Drasna":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Xaraton/Xaraton.html#drasna",
    'Myzar':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Myzar/Myzar.html",
    'Myzar (Regelwerk)':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Myzar/Myzar_Regelwerk.html",
    'Entstehung der Welt':"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Entstehung_der_Welt.html",
    "Feuergolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#feuerg",
    'Flossenbeutler':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Flossenbeutler/Flossenbeutler.html",
    "Fluggolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#flugg",
    "Flukte":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Pilze/Flukte/Flukte.html",
    "Flüche":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion_Regelwerk.html",
    "Flüsse":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Gewaesser/Gewaesser.html#fluss",
    'Frostwein':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Frostwein/Frostwein.html",
    "Förun":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Berethao/Berethao.html#stalbu",
    'Gebirge':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Geologie/Gebirge.html",
    'Gegner':"https://joelbondy.github.io/Suruthua/Regelwerk/ListeAllerGegner.html",
    "Geistige Gesundheit":"https://joelbondy.github.io/Suruthua/Regelwerk/Charakterbogen/Charakterbogen.html#geistigegesundheit",
    "Gemüsegolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#gemuesg",
    'Geologie':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Geologie/Geologie.html",
    "Gesteinsgolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#gesteing",
    'Gewässer':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Gewaesser/Gewaesser.html",
    "Giftgolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#giftg",
    "Glaubenskriege":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/WichtigeDaten.html#vsglaube",
    'Gloq':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Gloq/Gloq.html",
    'Golem':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html",
    'Große Persönlichkeiten':"https://joelbondy.github.io/Suruthua/Kulturen/GrossePersoenlichkeiten/GrossePersoenlichkeiten.html",
    'Guqual':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Guqual/Guqual.html",
    'Guqual (Regelwerk)':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Guqual/Guqual_Regelwerk.html",
    "Halluzinationspilz":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Pilze/Halluzinationspilz/Halluzinationspilz.html",
    "Himmelserz":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Geologie/Geologie.html#himmelserz",
    "Himmelsregen":"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html#himmelsregen",
    'Ideen':"https://joelbondy.github.io/Suruthua/metakram/Ideen.html",
    'Ideen (Tiere)':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Ideen.html",
    "Illoda":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Xaraton/Xaraton.html#illoda",
    "Initiative (Kampf)":"https://joelbondy.github.io/Suruthua/Regelwerk/Kampf/Kampf.html#init",
    'Inseln':"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Inseln/Inseln.html",
    "Jahr":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html",
    "Kalender":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html#kalender",
    'Kampf':"https://joelbondy.github.io/Suruthua/Regelwerk/Kampf/Kampf.html",
    "Kampfwerte":"https://joelbondy.github.io/Suruthua/Regelwerk/Charakterbogen/Charakterbogen.html#kampfwerte",
    'Karte':"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Karte.html",
    "Keil'O Renn":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/KeilO_Renn/KeilO_Renn.html",
    'Kiesenriller-Maus':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/KiesenrillerMaus/KiesenrillerMaus.html",
    "Knochengolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#knocheng",
    'Knochendorn':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Knochendorn/Knochendorn.html",
    "Koberinth":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Geologie/Geologie.html#koberinth",
    "Kontinente":"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html#kontinente",
    "Kuberika":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#kuberika",
    "Kwin Stalbu":"https://joelbondy.github.io/Suruthua/Kulturen/GrossePersoenlichkeiten/Personen/KwinStalbu.html",
    'Lachratte':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Lachratte/Lachratte.html",
    "Leben":"https://joelbondy.github.io/Suruthua/Regelwerk/Charakterbogen/Charakterbogen.html#leben",
    'Loromoth':"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Loromoth/Loromoth.html",
    'Magie':"https://joelbondy.github.io/Suruthua/Regelwerk/Magie.html",
    "Mana":"https://joelbondy.github.io/Suruthua/Regelwerk/Charakterbogen/Charakterbogen.html#mana",
    "Massiv":"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html#kontinente",
    "Meerespocke":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Meerespocke/Meerespocke.html",
    'Mensch':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Mensch/Mensch/Mensch.html",
    "Menschenvernichtung":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/WichtigeDaten.html#mv",
    "Minort (Stalbu)":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Berethao/Berethao.html#stalbu",
    "Mithadium":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Geologie/Geologie.html#mithadium",
    "Monat":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html",
    "Mond":"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html#mond",
    "Mondlauf":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html",
    "Myzarikriege": "https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/WichtigeDaten.html#myzarikrieg",
    'Namen':"https://joelbondy.github.io/Suruthua/metakram/Namen.html",
    'Naturphänomene':"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html#naturphaenomene",
    "Parade (Kampf)":"https://joelbondy.github.io/Suruthua/Regelwerk/Kampf/Kampf.html#para",
    'Parasitkäfer':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Parasitkaefer/Parasitkaefer.html",
    "Pflanzen":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Pflanzen.html",
    "Pflanzengolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#pflanzeg",
    'Pilze':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Pilze/Pilze.html",
    "Psychogolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#psychog",
    "Puletsi":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Inseln/Inseln.html#puletsi",
    'Quork':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Quork/Quork.html",
    'Quork (Regelwerk)':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Quork/Quork_Regelwerk.html",
    "Ranai":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#4el",
    "Ras'qath":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Berethao/Berethao.html#rasqath",
    'Regeln':"https://joelbondy.github.io/Suruthua/Regelwerk/Regeln.html",
    "Religionen und Götter":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html",
    'Religion (Regelwerk)':"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion_Regelwerk.html",
    "Ruryx":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Berethao/Berethao.html#ruryx",
    "Rüstung":"https://joelbondy.github.io/Suruthua/Regelwerk/Kampf/Kampf.html#regelkam",
    "Rux":"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Guqual/Guqual.html",
    "Ry":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Inseln/Inseln.html#ry",
    'Sauerbaum':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Sauerbaum/Sauerbaum.html",
    "Säuregolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#sauerg",
    "Schlafplanze (Blauer Traum)":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Blauer_Traum/Blauer_Traum.html",
    "Schlangenrausch":"https://joelbondy.github.io/Suruthua/Kulturen/Waehrung.html#schlangenrausch",
    'Schreiender Triesel':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Schreiender_Triesel/Schreiender_Triesel.html",
    "Schwarze Löcher":"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html#schwarzloch",
    "Segen":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html",
    "Snei":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Gewaesser/Gewaesser.html#snei",
    "Sonne":"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html#sonne",
    'Sonnensytem':"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html#sonnensystem",
    "Sport":"https://joelbondy.github.io/Suruthua/Kulturen/Sport",
    "Stalbu":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Berethao/Berethao.html#stalbu",
    "Stärke":"https://joelbondy.github.io/Suruthua/Regelwerk/Charakterbogen/Charakterbogen.html#staerke",
    "Suru":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Inseln/Inseln.html#suru",
    "Suruthua":"https://joelbondy.github.io/Suruthua/Suruthua/Welt.html",
    "Tag":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html",
    "Tiere":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Tiere.html",
    'Triesel':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Triesel/Triesel.html",
    "Trivia Gott":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#trivia",
    'Trollbrücke':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Trollbruecke/Trollbruecke.html",
    'Tropfbeutel':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Flora/Tropfbeutel/Tropfbeutel.html",
    'Tropfbeutler':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/Tiere/Tropfbeutler/Tropfbeutler.html",
    "Turninch":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Loromoth/Loromoth.html#turninch",
    'Übernehmen (Natur)':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Uebernehmen.html",
    "Umlauf":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html",
    "Unabhängigkeitskriege von Puletsi":"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/WichtigeDaten.html#kriegpuletsi",
    "Vadon":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Loromoth/Loromoth.html#vadon",
    'Vadonier':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Vadonier/Vadonier.html",
    'Vadonier (Regelwerk)':"https://joelbondy.github.io/Suruthua/Kulturen/Rassen/Vadonier/Vadonier_Regelwerk.html",
    "Vaiad":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Inseln/Inseln.html#vaiad",
    'Verfluchte Wesen':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/VerfluchteWesen/Verfluchte_Wesen.html",
    'Verfluchter Quork':"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/VerfluchteWesen/VQuork/VQuork.html",
    "Versiegeltes Schloss":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#vs",
    "Die vier Elemente":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#4el",
    'Waffenklassen':"https://joelbondy.github.io/Suruthua/Regelwerk/Kampf/Waffenklassen.html",
    "Waffenmodifikatoren":"https://joelbondy.github.io/Suruthua/Regelwerk/Kampf/Kampf.html#modi",
    'Währung':"https://joelbondy.github.io/Suruthua/Kulturen/Waehrung.html",
    "Wai":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#4el",
    "Wassergolem":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Golem/Golem.html#wasserg",
    "Wenai":"https://joelbondy.github.io/Suruthua/Kulturen/Religion/Goetter_Religion.html#4el",
    'Wichtige Daten':"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/WichtigeDaten.html",
    'Wirinima':"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Wirinima/Wirinima.html",
    "Wrethh":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Loromoth/Loromoth.html#wrethh",
    'Xaraton':"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Xaraton/Xaraton.html",
    "Yok":"https://joelbondy.github.io/Suruthua/Suruthua/Natur/Fauna/MagischeKreaturen/Yok/Yok.html",
    "Yok-ma":"https://joelbondy.github.io/Suruthua/Suruthua/Karte/Kontinente/Inseln/Inseln.html#yokma",
    'Zeitrechnung':"https://joelbondy.github.io/Suruthua/Kulturen/Zeitrechnung/Zeitrechnung.html",
};



let results = document.getElementById("results");
Object.entries(all_pages).forEach(([key,value])=>{
    let a = document.createElement("a");
    a.innerText = key;
    a.href = value;
    a.classList.add("resultItem");
    results.appendChild(a);
});

function search() {
    let resultsContainer = document.getElementById("results");
    let resultItems = document.getElementsByClassName("resultItem");

    let input = document.getElementById("searchbar").value
    input=input.toLowerCase();

    let noResults = true;
    for (i=0;i<resultItems.length;i++) {
        if (!resultItems[i].innerHTML.toLowerCase().includes(input) || input === "") {
            resultItems[i].style.display="none";
            continue;
        }
        else {
            resultItems[i].style.display="flex";
            noResults=false;
        }
    }

    resultsContainer.style.display = noResults ? "none":"block";
};
