const lex = {
    'xur': [['Person', 'Lebewesen', "Guqu'al", 'Wesen', 'Form', 'man'], ['Nomen'], [[''], ['rux'], ['dûqur', 'dunaxur', 'lûqur', 'axaxur', 'nāxur', 'ūrnaxur', 'dūxur', 'ðuxur', 'qaður', 'xuran', 'nuxur', 'nuxul', 'kaxur', 'lâkaxur']]],
    'rux': [['Sprache', 'Sprache der Guqual'], ['Nomen'], [[''], ['xur'], ['nārux', 'dûrux', 'lugrux', 'dugrux', 'ūrnarux', 'axarux', 'dunarux', 'ruqdar', 'rûkundar', 'lagrūdar']]],
    'gul': [['groß', 'großartig', 'bedeutend', 'viel', 'gut', 'sehr'], ['Adjektiv'], [[''], [''], ['guldur', 'guldūr', 'gûlad', 'gulrað', 'gulur']]],
    'a-': [['[bestimmter Artikel]'], ['Artikel'], [[''], ['gu-', 'ga-'], ['a-dal', 'a-gal', 'a-kral', 'a-dārulūn', 'ā-', 'āl-', 'ūl-', 'ra-', 'ār-']]],
    'dal': [['Tag', 'Umlauf'], ['Nomen'], [[''], [''], ['a-dal', 'nādal', 'nulâdal', 'gulâdal', 'nûlukdal', 'âdal', 'naldal', 'kundal', 'ðurudal', 'dûral', 'ūrnadal', 'nûladal', 'gâdal', 'âkadal', 'guðudal', 'ðagâral', 'dâlar']]],
    'gal': [['Monat', 'Mondlauf', 'Mond'], ['Nomen'], [[''], [''], ['a-gal', 'gal-krul', 'gâdal']]],
    'lâkadur': [['reden', 'sprechen', 'handeln (tauschen)'], ['Verb'], [['lak'], [''], ['qulakdur']]],
    'dûqur': [['Draske'], ['Nomen'], [['dukdar', 'xur'], ['dugrux'], ['']]],
    'duna': [['Auge'], ['Nomen'], [[''], [''], ['dunaxur', 'dunarux', 'dunadur', 'dunāku']]],
    'nādukal': [['Fluss'], ['Nomen'], [['nāxku', 'dukdar', 'dukal'], [''], ['nādukadur']]],
    'dūr': [['Erde', 'Boden', 'Basis', 'Ursprung'], ['Nomen'], [[''], ['dūl'], ['dūxur', 'dûrux', 'guldūr', 'rûqur', 'dûral', 'kadūr', 'qadūr', 'dūradur', 'dūrak', 'dūran']]],
    'ūrna': [['Himmel', 'Luft', 'Gott'], ['Nomen'], [[''], [''], ['ūrnarux', 'ūrnaxur', 'ūrnâqu', 'ūrnadur', 'ûrukdar', 'ūrnadal', 'ūrnakdur', 'ūrandak']]],
    'ūrnâqu': [['Regen'], ['Nomen'], [['ūrna', 'nāxku'], [''], ['nâqudar']]],
    'qna': [['Festung', 'Burg', 'befestigte Stadt'], ['Nomen'], [[''], [''], ['']]],
    'qun': [['Festung', 'Burg', 'befestigte Stadt'], ['Nomen'], [[''], [''], ['']]], 
    'kral': [['Jahr', 'Ablauf', 'Sonne'], ['Nomen'], [[''], [''], ['a-kral']]],
    'gunda': [['jung'], ['Adjektiv'], [[''], ['gundar'], ['']]],
    'dukdar': [['bewegen', 'fortbewegen', 'laufen', 'gehen'], ['Verb'], [[''], ['dukadur', 'duk'], ['dugrux', 'dûqur', 'nādukal', 'dukal', 'nādukdar', 'ûrukdar', 'dûrukdar', 'ūrnakdur', 'ðûkundar', 'lakdur', 'duqandur', 'ðulðukdar', 'duqardur']]],
    'nâqudar': [['regnen'], ['Verb'], [['ūrnâqu', 'nāxku'], [''], ['']]],
    'guqudar': [['sich wandeln', 'verwandeln', 'sich ändern', 'verändern', 'geboren werden', 'erschaffen werden'], ['Verb'], [[''], [''], ['guður', "guqu'al", 'guqudāndur']]],
    'axa': [['alt'], ['Adjektiv'], [[''], [''], ['axarux', 'axaxur', 'âxadur']]],
    'dunaxur': [['Augling'], ['Eigenname'], [['duna', 'xur'], ['dunarux'], ['']]],
    'dunadur': [['sehen', 'schauen', 'gucken', 'blicken'], ['Verb'], [['duna'], [''], ['dunaƥdur']]],
    'nāxur': [['Amaka'], ['Eigenname'], [['nāxku', 'xur'], ['nārux'], ['']]],
    'dūxur': [['Avzitil'], ['Eigenname'], [['dūr', 'xur'], ['dûrux'], ['']]],
    'lukdar': [['wandern', 'weit laufen', 'weite Strecken zurücklegen'], ['Verb'], [[''], [''], ['lugrux', 'lûqur']]],
    'lûqur': [['Vadonier'], ['Eigenname'], [['lukdar', 'xur'], ['lugrux'], ['']]],
    'kûlu': [['Licht'], ['Nomen'], [[''], [''], ['kûludar']]],
    'ruqdar': [['schreiben'], ['Verb'], [['rux'], [''], ['']]],
    'ruk': [['unten', 'tief'], ['Adjektiv'], [[''], ['rūk'], ['rûqur', 'rukdān', 'rukdāndur', 'rukdar', 'ruqalun', 'laquk', 'rûkur', 'dûrukdar']]],
    'qan': [['oben', 'hoch'], ['Adjektiv/Präposition'], [[''], [''], ['qandān', 'qanar', 'dûqandur', 'laqandur']]],
    'dārul': [['Wind'], ['Nomen'], [[''], [''], ['a-dārulūn', 'dārulaƥ', 'dārulan', 'dârul', 'âdarul']]],
    'âkadur': [['wissen', 'können'], ['Verb'], [['akar', 'akal'], [''], ['']]],
    'ūd': [['Essen', 'Nahrung'], ['Nomen'], [[''], [''], ['ûdar']]],
    'qural': [['Familie', 'Gemeinschaft'], ['Nomen'], [[''], [''], ['']]],
    'lūnad': [['Krieg', 'Katastrophe', 'Schrecken'], ['Nomen'], [[''], [''], ['']]],
    'luxdar': [['sitzen'], ['Verb'], [[''], ['luq'], ['']]],
    'kûdudar': [['sammeln', 'ansammeln', 'versammeln'], ['Verb'], [[''], [''], ['kûdur']]],
    'nūk': [['Tod'], ['Nomen'], [[''], [''], ['nûkudar', 'nuqal']]],
    'ralxū': [['Gebiet', 'Umgebung'], ['Nomen'], [[''], [''], ['']]],
    'nūl': [['hell', 'Tageszeit'], ['Adjektiv, Nomen'], [['nûla'], ['nul'], ['nūlan']]],
    'kûnudar': [['nehmen', 'an sich nehmen'], ['Verb'], [['kun', '-gūn'], ['kunadur'], ['rûkundar', 'kudunaður']]],
    'kûnadur': [['riechen', 'mögen', 'gut finden'], ['Verb'], [['kuna'], [''], ['']]],
    'dûrul': [['dunkel', 'Nacht'], ['Adjektiv, Nomen'], [['dur'], [''], ['dûrudar', 'ðugul', 'duran', 'dûrur']]],
    'a-dal': [['heute'], ['Temporaladverb'], [['a-', 'dal'], [''], ['']]],
    'a-gal': [['diesen Monat'], ['Temporaladverb'], [['a-', 'gal'], [''], ['']]],
    'a-kral': [['dieses Jahr'], ['Temporaladverb'], [['a-', 'kral'], [''], ['']]],
    'ûdar': [['essen'], ['Verb'], [['ūd'], [''], ['']]],
    'luna': [['Zeit', 'Geschichte', 'Historie'], ['Nomen'], [[''], [''], ['lunaƥ', 'qaður-luna', 'ga-luna', 'lunakur']]],
    'nûla': [['Sonne'], ['Nomen'], [[''], [''], ['nûla-krul', 'nûladal', 'nūl', 'nul']]],
    'âdar': [['Baum', 'Holz'], ['Nomen'], [[''], [''], ['âdal']]],
    'nûkudar': [['sterben'], ['Verb'], [['nūk'], ['nuqal'], ['']]],
    'u-': [['und'], ['Konjunktion'], [[''], [''], ['']]],
    'āl-': [['nicht', 'ohne'], ['Negation'], [['a-'], ['gul-', 'gāl-', 'ālun', 'ānul'], ['āl-ðurul', 'âdarul', 'āldar', 'ālnuƥal']]],
    'ā-': [['[und+Artikel]'], ['Konjunktion'], [['a-'], ['ugu-', 'uga-'], ['']]],
    'nādur': [['trinken'], ['Verb'], [['nāxku', 'nār'], ['nādul'], ['']]],
    'dûrudar': [['schlafen'], ['Verb'], [['dûrul'], [''], ['']]],
    'dul': [['Stadt'], ['Nomen'], [[''], [''], ['dûluruð', 'qâladul']]],
    'xuq': [['Kopf'], ['Nomen'], [[''], [''], ['']]],
    'kaðan': [['Kraft', 'Gewalt', 'Stärke'], ['Nomen'], [[''], ['kað', 'kaðadur'], ['kaðal', 'kâðadur', 'kaðandur']]],
    'ûlud': [['Wald'], ['Nomen'], [[''], [''], ['']]],
    'guldur': [['wachsen'], ['Verb'], [['gul'], ['guldūr', 'gûlad'], ['guluð']]],
    'guldūr': [['Pflanze', 'Gewächs'], ['Nomen'], [['gul', 'dūr'], ['guldur', 'gûlad'], ['rugulūr', 'gulðar']]],
    'gûlad': [['Berg'], ['Nomen'], [['gul', 'nûlad'], ['guldur', 'guldūr', 'nûlad'], ['gulâdal', 'gûladun']]],
    'rûqur': [['Tal'], ['Nomen'], [['ruk', 'dūr'], [''], ['']]],
    'larnaqa': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'nûluk': [['Felsen', 'Fels'], ['Nomen'], [[''], ['nûlad'], ['nûlukdal']]],
    '-ūn': [['mit'], ['Präposition'], [[''], [''], ['a-dārulūn']]],
    'ūl-': [['[und+neg+Artikel]'], ['Konjunktion'], [['a-'], ['ugul-', 'gūl-'], ['']]],
    'ðāndrug': [['Alphabet'], ['Nomen'], [[''], [''], ['']]],
    'a-dārulūn': [['Richtung'], ['Nomen'], [['a-', 'dārul', '-ūn'], [''], ['']]],
    'xaradūn': [['Xaraton'], ['Eigenname'], [[''], [''], ['']]],
    'adûranð': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'lûrunað': [['Loromoth'], ['Eigenname'], [[''], [''], ['']]],
    'ƥârān': [['Wirinima'], ['Eigenname'], [[''], [''], ['']]],
    'dārðaru': [['Berethao'], ['Eigenname'], [[''], [''], ['']]],
    'uldūr': [['Schrift', 'Geschriebenes', 'Niederschrift'], ['Nomen'], [[''], [''], ["ka'uldūr"]]],
    'nurguð': [['Geschichte', 'Erzählung', 'Märchen'], ['Nomen'], [[''], [''], ['']]],
    'ðagar': [['Gedanke', 'Konzept', 'Traum', 'Plan'], ['Nomen'], [[''], ['ðâladur'], ['ðagadur', 'ðugul', 'ðagudar', 'ðagâral', 'ðagar-ruðal']]],
    'gulrað': [['Turm'], ['Nomen'], [['gul'], [''], ['']]],
    'ðâladur': [['denken', 'nachdenken', 'überlegen'], ['Verb'], [[''], ['ðagadur', 'ðagar'], ['']]],
    'ðulðu': [['rund'], ['Adjektiv'], [[''], ['ðulður'], ['ðulðudar', 'ðulðukdar']]],
    'ðulður': [['Kugel', 'runder Gegenstand', "Cul'thur", 'Auge'], ['Nomen/Eigenname'], [[''], ['ðulðu'], ['ðulðudar']]],
    'ðuru': [['Leben', 'Existenz', 'Suru'], ['Nomen/Eigenname'], [[''], ['ðural', 'ruð', 'ðulur'], ['ðurudar', "ðuruðu'a", 'ðuxur', 'guður', 'ðurudal', 'ðuraxdur', 'qaðurdar', 'ðurax', 'qaður', 'kudunaður', 'ðuraƥdur']]],
    'ðurudar': [['leben', 'existieren'], ['Verb'], [['ðuru'], ["ðuruðu'a", 'ðuraxdur', 'qaðurdar'], ['ðuraƥdur']]],
    'ðulðudar': [['rollen', 'bewegen der Himmelskörper', 'vergehen des Tages', 'vergehen von Zeit'], ['Verb'], [['ðulðu', 'ðulður'], [''], ['']]],
    'gûluð': [['Karte', 'Landkarte'], ['Nomen'], [[''], [''], ['']]],
    'akdūl': [['links'], ['Präposition'], [[''], [''], ['akdūldān']]],
    'ðadudar': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'dûluruð': [['kleine Stadt', 'Dorf'], ['Nomen'], [['dul', '-(û)ruð'], [''], ['']]],
    'kuna': [['Nase'], ['Nomen'], [[''], [''], ['kûnadur']]],
    '-(û)ruð': [['Diminutiv'], ['Suffix'], [[''], [''], ['dûluruð']]],
    'gâranul': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'ūlrad': [['rechts'], ['Präposition'], [[''], [''], ['ūlradān']]],
    'râdūl': [['Ding', 'Sache', 'Etwas', 'Gegenstand', 'Objekt', 'Item'], ['Nomen'], [[''], [''], ['']]],
    'gâladur': [['scheinen', 'glänzen', 'funkeln', 'glitzern', 'blitzen'], ['Verb'], [['gâla'], ['gâlal'], ['galar']]],
    'galadur': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'galan': [['Wort'], ['Nomen'], [[''], [''], ['kagalan']]],
    'nalgur': [['Konsistenz', 'Beschaffenheit', 'Kern', 'Element', 'woraus etwas besteht'], ['Nomen'], [[''], [''], ['nalgudar', 'nargul']]],
    'nadūl': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    '-dān': [['in Richtung', 'nach', 'zu'], ['Präposition'], [[''], [''], ['ūlrâdān', 'akdūldān', 'qandān', 'rukdān', 'duqandur', 'guqudāndur']]],
    'ūrnadur': [['atmen'], ['Verb'], [['ūrna'], [''], ['']]],
    'rukdān': [['herunter', 'nach unten', 'hinunter', 'unter'], ['Präposition'], [['ruk', '-dān'], [''], ['']]],
    'qandān': [['herauf', 'nach oben', 'hinauf'], ['Präposition'], [['qan', '-dān'], [''], ['']]],
    "ðuruðu'a": [['Suruthua', 'Welt'], ['Eigenname/Nomen'], [['ðuru'], ['ðurudar'], ['']]],
    'akdūldān': [['nach links'], ['Präposition'], [['akdūl', '-dān'], [''], ['']]],
    'ūlradān': [['nach rechts'], ['Präposition'], [['ūlrad', '-dān'], [''], ['']]],
    'xug': [['Haus', 'Gebäude'], ['Nomen'], [[''], [''], ['kaxug', "xug-ðura'ul"]]],
    'durān': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'luga': [['Wal'], ['Nomen'], [[''], [''], ['']]],
    'kā': [['ich'], ['Pronomen'], [[''], [''], ['']]],
    'la': [['du'], ['Pronomen'], [[''], [''], ['']]],
    'rā': [['er, sie, es'], ['Pronomen'], [[''], [''], ['']]],
    'kān': [['wir'], ['Pronomen'], [[''], [''], ['']]],
    'lan': [['ihr'], ['Pronomen'], [[''], [''], ['']]],
    'rān': [['sie (Plural)'], ['Pronomen'], [[''], [''], ['']]],
    'rukdāndur': [['sterben'], ['Verb'], [['ruk', 'dān'], [''], ['']]],
    'qa': [['Ja', 'eins'], ['Ja/Zahl'], [[''], ['qad'], ['qad', 'qar', 'qað', 'qax', 'qaƥar', 'qaxul']]],
    'ruð': [['Nein', 'null', 'Tod'], ['Nein/Zahl/Nomen'], [[''], ['ðuru'], ['ruðal', 'ruðax']]],
    'ðagadur': [['konzipieren', 'entwerfen', 'ausdenken', 'kreieren', 'erschaffen', 'planen'], ['Verb'], [['ðagar'], ['ðâladur', 'lagadur'], ['ðagudar']]],
    'rukdār': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'rukdar': [['nach unten bewegen', 'hinab bewegen', 'hinabsteigen', 'graben', 'ausheben', 'hinabfallen', 'fallen'], ['Verb'], [['ruk'], [''], ['dûqandur', 'nāruk']]],
    'ðuxur': [['Lebewesen', 'Tier'], ['Nomen'], [['ðuru', 'xur'], [''], ['']]],
    'rûkundar': [['lesen', 'verstehen', 'heißen'], ['Verb'], [['rux', 'kûnudar'], [''], ['']]],
    'nāxku': [['Wasser'], ['Nomen'], [[''], ['nāk'], ['nārux', 'nāxur', 'nādukal', 'ūrnâqu', 'nâqudar', 'nādur', 'nādukdar', 'nāl', 'nār', 'nākrul', 'nādal', 'kanāxku', 'dunāku', 'nāruk', 'runāxku', 'nāxak', 'naƥāx']]],
    'gād': [['klein', 'wenig'], ['Adjektiv'], [[''], ['gāl'], ['']]],
    'nûlad': [['Stein'], ['Nomen'], [[''], ['gûlad', 'nûluk'], ['gûlad', 'nulâdal', 'nûlar']]],
    'nal': [['Feuer', 'Lagerfeuer'], ['Nomen'], [[''], [''], ['naldal', 'kanal', 'naldur', 'nalda', 'nâlak']]],
    'dār': [['von', 'seit', 'aus'], ['Präposition'], [[''], [''], ['duqardur']]],
    'lux': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'gurul': [['Fleisch'], ['Nomen'], [[''], [''], ['']]],
    'ūrnaxur': [['Quork'], ['Eigenname'], [['ūrna', 'xur'], ['ūrnarux'], ['']]],
    'dunarux': [['Sprache der Auglinge'], ['Eigenname'], [['duna', 'rux'], ['dunaxur'], ['']]],
    'dûrux': [['Sprache der Avzitil'], ['Eigenname'], [['dūr', 'rux'], ['dūxur'], ['']]],
    'nārux': [['Sprache der Amaka'], ['Eigenname'], [['nāxku', 'rux'], ['nāxur'], ['']]],
    'lugrux': [['Sprache der Vadonier'], ['Eigenname'], [['lukdar', 'rux'], ['lûqur'], ['']]],
    'dugrux': [['Sprache der Drasken'], ['Eigenname'], [['dukdar', 'rux'], ['dûqur'], ['']]],
    'ūrnarux': [['Sprache der Quork'], ['Eigenname'], [['ūrna', 'rux'], ['ūrnaxur'], ['']]],
    'axarux': [['Sprache der Elben'], ['Eigenname'], [['axa', 'rux'], ['axaxur'], ['']]],
    'krūl': [['Krūl (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'qârad': [['Qârad (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'gul xad': [['Gul Xad (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'drâqul': [['Drâqul (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'gul qūd': [['Gul Qūd (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'gûluk': [['Gûluk (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'gârak': [['Gârak (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'nâkadur': [['Nâkadur (Stadt'], ['Eigenname'][[''], [''], ['']]],
    'guldūn': [['Guldūn (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'dûnad': [['Dûnad (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    "xa'ād": [['Vaiad (Insel)'], ['Eigenname'], [[''], [''], ['']]],
    'gul gunud': [['Gul Gunud (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'narūd': [['Narūd (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'nadul': [['Nadul (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'qun xaqud': [['Qun Xaqud (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'dan': [['blau'], ['Farbe'], [[''], [''], ['']]],
    'run': [['Ohr'], ['Nomen'], [[''], [''], ['rundar']]],
    'runal': [['Zuhörer', 'Gesprächspartner'], ['Nomen'], [[''], [''], ['']]],
    'larun': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'aral': [['dünn', 'schlank', 'mager', 'schmal'], ['Adjektiv'], [[''], [''], ['']]],
    'lāg': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'qalar': [['Mitte', 'Oberhaupt-Titel der Guqual', 'Oberhaupt', ' Anführer', ' Herrscher'], ['Nomen/Eigenname'], [[''], ['qalur', 'qal'], ['qalar-krul', 'qâladul']]],
    'qaðra': [['Frieden'], ['Nomen'], [[''], [''], ['']]],
    'ur-': [['oder'], ['Konjunktion'], [[''], [''], ['']]],
    'ra-': [['[oder+Artikel]'], ['Konjunktion'], [['a-'], ['gur-', 'gar-'], ['']]],
    'ār-': [['[oder+nicht+Artikel]'], ['Konjunktion'], [['a-'], ['āgur-', 'gār-'], ['']]],
    'ga-': [['[bestimmterArtikel]'], ['Artikel'], [[''], ['a-', 'gu-'], ['uga-', 'gāl-', 'gūl-', 'gar-', 'gār-']]],
    'uga-': [['[und+Artikel]'], ['Konjunktion'], [['ga-'], ['ugu-', 'ā-'], ['']]],
    'gāl-': [['[nicht+Artikel]'], ['Artikel'], [['ga-'], ['gul-', 'āl-'], ['']]],
    'gūl-': [['[und+nicht+Artikel]'], ['Konjunktion'], [['ga-'], ['ugul-', 'ūl-'], ['']]],
    'gar-': [['[oder+Artikel]'], ['Konjunktion'], [['ga-'], ['gur-', 'ra-'], ['']]],
    'gār-': [['[oder+nicht+Artikel]'], ['Konjunktion'], [['ga-'], ['āgur-', 'ār-'], ['']]],
    'gu-': [['[bestimmterArtikel]'], ['Artikel'], [[''], ['a-', 'ga-'], ['ugu-', 'gul-', 'ugul-', 'gur-', 'āgur-']]],
    'ugu-': [['[und+Artikel]'], ['Konjunktion'], [['gu-'], ['uga-', 'ā-'], ['']]],
    'gul-': [['[nicht+Artikel]'], ['Artikel'], [['gu-'], ['gāl-', 'āl-'], ['']]],
    'ugul-': [['[und+nicht+Artikel]'], ['Konjunktion'], [['gu-'], ['gūl-', 'ūl-'], ['']]],
    'gur-': [['[oder+Artikel]'], ['Konjunktion'], [['gu-'], ['gar-', 'ra-'], ['']]],
    'āgur-': [['[oder+nicht+Artikel]'], ['Konjunktion'], [['gu-'], ['gār-', 'ār-'], ['']]],
    'ðugul': [['Schlaf'], ['Nomen'], [['ðagar', 'dûrul'], [''], ['ðuguldar', 'ðagudar']]], 'ðuguldar': [['schlafen'], ['Verb'], [['ðugul'], [''], ['ðagudar', 'ðunuldar']]],
    'qalar-krul': [['Mondlaufmitte', ' Monatsmitte', '12. Umlauf eines Monats'], ['Eigenname'], [['qalar', '-krul'], [''], ['']]],
    '-krul': [['Fest', '[Marker für Festtage]'], ['Name'], [[''], [''], ['nākrul', 'nûla-krul', 'gal-krul', 'qalar-krul']]],
    'lag': [['Hand', 'Arm'], ['Nomen'], [[''], [''], ['lagdur', 'laquk', 'lakdur', 'laqandur', 'lagadur', 'lagru']]],
    'lagdur': [['geben'], ['Verb'], [['lag'], [''], ['lagrūdar']]],
    'kun': [['Körper'], ['Nomen'], [[''], [''], ['kûnudar', 'kundal', 'kunrūl', 'kunadur', 'kunād', 'kundar']]],
    'aðrak': [['Zunge', 'Geschmack'], ['Nomen'], [[''], [''], ['aðradur']]],
    'ƥarnadul': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'ƥarla': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'qalur': [['Wahrheit', 'Richtige'], ['Nomen'], [[''], ['qalar', 'qal'], ['']]],
    'dukal': [['Verb'], ['Nomen'], [['dukdar'], ['duk'], ['']]],
    'ƥul': [['gegen', 'entgegen', 'aber', 'jedoch'], ['Adjektiv/Konjunktion'], [[''], [''], ['ƥulur', 'ƥûlaqdar']]],
    'ƥāður': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'rundar': [['hören', 'zuhören', 'lauschen'], ['Verb'], [['run'], [''], ['']]],
    'gal-krul': [['Mondfest', 'Mondfinsternis'], ['Eigenname/Nomen'], [['gal', '-krul'], [''], ['']]],
    'nûla-krul': [['Sonnenfest', 'Sonnenfinsternis'], ['Eigenname/Nomen'], [['nûla', '-krul'], [''], ['']]],
    'guður': [['Geburt'], ['Nomen'], [['guqudar', 'ðuru'], [''], ['guðudal']]],
    'lak': [['Mund'], ['Nomen'], [[''], [''], ['lâkadur']]],
    'ƥalar': [['Haut', 'Farbe', 'Beschaffenheit'], ['Nomen'], [[''], [''], ['ƥaladur']]],
    'ƥaladur': [['fühlen', 'tasten', 'spüren', 'berühren', 'anfassen'], ['Verb'], [['ƥalar'], [''], ['']]],
    'nu': [['zwei'], ['Zahl'], [[''], ['nud'], ['nuxur', 'nuxul']]],
    'lar': [['drei'], ['Zahl'], [[''], [''], ['lâraquk']]],
    'ƥur': [['vier'], ['Zahl'], [[''], [''], ['']]],
    'dāð': [['fünf'], ['Zahl'], [[''], [''], ['']]],
    'dun': [['sechs'], ['Zahl'], [[''], [''], ['']]],
    'xan': [['sieben'], ['Zahl'], [[''], [''], ['']]],
    'gur': [['acht'], ['Zahl'], [[''], [''], ['']]],
    'ðan': [['neun'], ['Zahl'], [[''], [''], ['']]],
    'nādukdar': [['schwimmen'], ['Verb'], [['nāxku', 'dukdar'], [''], ['']]],
    'ûrukdar': [['fliegen'], ['Verb'], [['ūrna', 'dukdar'], [''], ['uruk']]],
    'ālun': [['Nichts', 'Leere'], ['Nomen'], [[''], ['āl-', 'ānul'], ['ruqalun']]],
    'ruqalun': [['Loch', 'Grube', 'Mulde', 'Einkerbung'], ['Nomen'], [['ruk', 'ālun'], [''], ['']]],
    'laquk': [['Bein', 'Fuß'], ['Nomen'], [['lag', 'ruk'], [''], ['lâraquk']]],
    "guqu'al": [["Guqu'al"], ['Eigenname'], [['guqudar'], [''], ['']]],
    'qad': [['alle', 'alles'], ['Nomen'], [['qa'], ['qa', 'qar'], ['qaður']]],
    'qaður': [['jede', 'jeder', 'jedes', 'Ende', 'Stopp'], ['Artikel/Nomen'], [['qad', 'xur', 'ðuru'], [''], ['qaðurdar', 'qaður-luna']]],
    'akal': [['weise', 'allwissend', 'erfahren', 'intelligent'], ['Adjektiv'], [[''], ['akar'], ['âkadur', 'âkadal']]],
    'akar': [['Wissen', 'Reichtum'], ['Nomen'], [[''], ['akal'], ['âkadur', 'âkadal']]],
    'qanar': [['Höhe', 'Anhöhe', 'Erhebung', 'Spitze', 'Höhepunkt'], ['Nomen'], [['qan'], [''], ['']]],
    'gulur': [['Größe', 'Weite'], ['Nomen'], [['gul'], [''], ['kadūgul']]],
    'rûkur': [['Tiefe', 'Tiefpunkt'], ['Nomen'], [['ruk'], [''], ['']]],
    'nuqal': [['tot', 'unlebendig'], ['Adjektiv'], [['nūk'], ['nûkudar'], ['']]],
    'nāl': [['nass'], ['Adjektiv'], [['nāxku'], [''], ['']]],
    'kûdur':[['Sammlung', 'Ansammlung', 'Haufen', 'Besitz'], ['Nomen'], [['kûdudar'], [''], ['']]],
    'nār': [['Getränk', 'Trinkbares'], ['Nomen'], [['nāxku'], ['nādul'], ['nādur']]],
    'nādukadur': [['fliessen'], ['Verb'], [['nādukal'], [''], ['nādul']]],
    'ānul': [['leer'], ['Adjektiv'], [[''], ['ālun', 'āl-'], ['']]],
    'ƥal': [['schnell', 'zügig'], ['Adjektiv'], [[''], [''], ['ƥâladur', 'ƥâlukdar']]],
    'âxadur': [['altern', 'älter werden', 'wachsen', 'heranwachsen'], ['Verb'], [['axa'], [''], ['']]],
    'ƥulur': [['Feind', 'Gegner', 'Widersacher'], ['Nomen'], [['ƥul'], [''], ['']]],
    'laran': [['dick', 'breit', 'fett', 'ausgeprägt'], ['Adjektiv'], [[''], [''], ['']]],
    'nākrul': [['Wasserfest'], ['Eigenname'], [['nāxku', '-krul'], [''], ['']]],
    'nādal': [['3. Umlauf eines Monats'], ['Eigenname'], [['nāxku', 'dal'], [''], ['']]],
    'nulâdal': [['2. Umlauf eines Monats'], ['Eigenname'], [['nûlad', 'dal'], [''], ['']]],
    'gulâdal': [['23. Umlauf eines Monats', 'Monatsende'], ['Eigenname'], [['gûlad', 'dal'], [''], ['']]],
    'nûlukdal': [['13. Umlauf eines Monats'], ['Eigenname'], [['nûluk', 'dal'], [''], ['']]],
    'âdal': [['7. Umlauf eines Monats'], ['Eigenname'], [['âdar', 'dal'], [''], ['']]],
    'naldal': [['22. Umlauf eines Monats'], ['Eigenname'], [['nal', 'dal'], [''], ['']]],
    'kundal': [['15. Umlauf eines Monats'], ['Eigenname'], [['kun', 'dal'], [''], ['']]],
    'ðurudal': [['11. Umlauf eines Monats'], ['Eigenname'], [['ðuru', 'dal'], [''], ['']]],
    'dûral': [['14. Umlauf eines Monats'], ['Eigenname'], [['dūr', 'dal'], [''], ['']]],
    'ðuxural': [['21. Umlauf eines Monats'], ['Eigenname'], [[''], [''], ['']]],
    'guldûral': [['4. Umlauf eines Monats'], ['Eigenname'], [[''], [''], ['']]],
    'ūrnadal': [['10. Umlauf eines Monats'], ['Eigenname'], [['ūrna', 'dal'], [''], ['']]],
    'nûladal': [['5. Umlauf eines Monats'], ['Eigenname'], [['nûla', 'dal'], [''], ['']]],
    'gâdal': [['1. Umlauf eines Monats'], ['Eigenname'], [['gal', 'dal'], [''], ['']]],
    'âkadal': [['6. Umlauf eines Monats'], ['Eigenname'], [['akar', 'akal', 'dal'], [''], ['']]],
    'guðudal': [['16. Umlauf eines Monats'], ['Eigenname'], [['guður', 'dal'], [''], ['']]],
    'galuq': [['Gloq'], ['Eigenname'], [[''], [''], ['']]],
    'galar': [['Stern'], ['Nomen'], [['gâladur'], ['gâla', 'gâlal'], ['']]],
    'ðagar-dan': [['Blauer Traum'], ['Eigenname'], [[''], [''], ['']]],
    'uruk': [['Vogel', 'fliegendes Tier'], ['Nomen'], [['ûrukdar'], [''], ['']]],
    'ðuraxdur': [['anfangen', 'beginnen', 'starten'], ['Verb'], [['ðuru', 'ðurax'], ['ðuru', 'ðurudar', 'qaðurdar'], ['']]],
    'qaðurdar': [['enden', 'beenden', 'stoppen', 'aufhören', 'zu Ende gehen'], ['Verb'], [['ðuru', 'qaður'], ['ðuru', 'ðurudar', 'ðuraxdur'], ['']]],
    'ƥuxur': [['Frucht'], ['Nomen'], [[''], [''], ['']]],
    'raƥ': [['stark', 'viel', 'enorm'], ['Adjektiv'], [[''], [''], ['dārulaƥ']]],
    'kuðul': [['schön', 'außergewöhnlich', 'besonders'], ['Adjektiv'], [[''], [''], ['']]],
    'rūl': [['Klang', 'Sound', 'Ton', 'Geräusch', 'Laut'], ['Nomen'], [[''], [''], ['kunrūl', 'rūlaƥ', 'dârul']]],
    'ƥākul': [['Lösung', 'Ergebnis', 'Entscheidung'], ['Nomen'], [[''], [''], ['laƥuldar', 'ƥakuldar']]],
    'kal': [['schlecht', 'böse'], ['Adjektiv'], [[''], ['kalur', 'karal'], ['karuð']]],
    'qur': [['Weg', 'Straße'], ['Nomen'], [[''], [''], ['']]],
    'quxal': [['Gesetz', 'Regel', 'Bestimmung'], ['Nomen'], [[''], [''], ['']]],
    'laƥrad': [['Gras'], ['Nomen'], [[''], [''], ['laƥradun', 'kalaƥrad']]],
    'dārulaƥ': [['Sturm', 'Orkan', 'Tornado'], ['Nomen'], [['dārul', 'raƥ'], [''], ['']]],
    'kuður': [['Schönheit', 'etwas Besonderes', 'etwas Außergewöhnliches', 'Besonderes', 'Außergewöhnliches'], ['Nomen'], [[''], [''], ['']]],
    'dārulan': [['Wetter', 'Winde'], ['Nomen'], [['dārul'], [''], ['']]],
    'ural': [['Sand'], ['Nomen'], [[''], [''], ["ka'ural", 'urad']]],
    'ūral': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'kadūr': [['Land', 'Gebiet', 'Gegend', 'Gelände'], ['Nomen'], [['dūr', 'ka'], ['qadūr'], ['kadūgul']]],
    'kaður': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'dûqandur': [['springen', 'hochbewegen'], ['Verb'], [['qan', 'rukdar'], [''], ['']]],
    'dûrukdar': [['fallen', 'hinfallen'], ['Verb'], [['dukdar', 'ruk'], [''], ['']]],
    'kaxug': [['Schloß', 'Großhaus', 'großes Haus'], ['Nomen'], [['xug', 'ka'], [''], ['']]],
    'ka': [['viel'], ['Adjektiv'], [[''], [''], ['kaxug', 'kadūr', 'kanal', 'kagalan', "ka'uldūr", 'kadur', 'kanāxku', "ka'ural", 'kaxur', 'kalaƥrad']]],
    'kunrūl': [['Stimme'], ['Nomen'], [['kun', 'rūl'], [''], ['']]],
    'kanal': [['Brand', 'großes Feuer'], ['Nomen'], [['nal', 'ka'], [''], ['']]],
    'naldur': [['brennen', 'verbrennen'], ['Verb'], [['nal'], [''], ['']]],
    'luqak': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'guluð': [['Haar', 'Haare'], ['Nomen'], [['guldur'], [''], ['']]],
    'kagalan': [['Geschichte', 'Erzählung'], ['Nomen'], [['ka', 'galan'], [''], ['']]],
    'qâladul': [['Hauptstadt'], ['Nomen'], [['qalar', 'dul'], [''], ['']]],
    'ður': [['Neuheit', 'Neuigkeit', 'etwas Neues'], ['Nomen'], [[''], [''], ['āl-ðurul']]],
    'ƥarquð': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'rālun': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'ƥaxur': [['Perfektion', 'Vollkommenheit', 'Vollständigkeit'], ['Nomen'], [[''], ['ƥaxul'], ['']]],
    'ƥaxul': [['ganz', 'perfekt', 'vollkommen', 'vollständig'], ['Adjektiv'], [[''], ['ƥaxur'], ['']]],
    'ðurax': [['Anfang', 'Beginn', 'Start'], ['Nomen'], [['ðuru'], [''], ['ðuraxdur', 'ðural']]],
    'dūl': [['trocken', 'erdig'], ['Adjektiv'], [[''], ['dūr'], ['']]],
    'rūldar': [['klingen', 'Geräusche machen', 'tönen', 'singen'], ['Verb'], [[''], [''], ['']]],
    'lagrūdar': [['sagen', 'reden'], ['Verb'], [['lagdur', 'rux'], [''], ['ƥûlaqdar', 'lagruðaldur']]],
    'ðagudar': [['träumen', 'nachdenken', 'lösen', 'lernen'], ['Verb'], [['ðugul', 'ðuguldar', 'ðagadur', 'ðagar'], [''], ['']]],
    "ka'uldūr": [['Buch', 'Schriften', 'Text'], ['Nomen'], [['ka', 'uldūr'], [''], ['']]],
    'kadur': [['addieren', 'vervielfältigen', 'erweitern', 'vermehren', 'bereichern', 'hinzufügen'], ['Verb'], [['ka'], [''], ['']]],
    'ƥûlaqdar': [['erwidern', 'antworten', 'entgegnen'], ['Verb'], [['ƥul', 'lagrūdar'], [''], ['']]],
    'lūd': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'qadur': [['Zacken', 'Spitze'], ['Nomen'], [[''], [''], ['']]],
    'ðugul-gul': [['der große Schlaf', 'Schlaf eines Anführers um bedeutende Probleme zu lösen oder Krisen zu bewältigen'], [], [[''], [''], ['']]],
    'kalūnad': [['die große Katastrophe', '(ein nationaler Notstand)'], ['Eigenname'], [[''], [''], ['']]],
    'ƥûlaq': [['Antwort'], ['Nomen'], [[''], [''], ['']]],
    'gâla': [['Glanz', 'Schein'], ['Nomen'], [[''], ['galar', 'gâlal'], ['gâladur']]],
    'ragul': [['langsam'], ['Adjektiv'], [[''], [''], ['']]],
    'ral': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'lax': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'rūqul': [['weich', 'angenehm', 'schön', 'sanft'], ['Adjektiv'], [[''], [''], ['']]],
    'nûqur': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'gudan': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'kunda': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'naƥ': [['Kälte'], ['Nomen'], [[''], ['nâƥal'], ['']]],
    'nukal': [['möglich', 'wenn', 'ob'], ['Adjektiv'], [[''], [''], ['']]],
    'kadað': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'dûquk': [['Keine Übersetzung'], [''], [[''], [''], ['']]],
    'gudun': [['Sieg', 'Erfolg', 'Gewinn'], ['Nomen'], [[''], ['gudundar'], ['gudul']]],
    'kuqar': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'qul': [['laut'], ['Adjektiv'], [[''], [''], ['qulakdur']]],
    'ād': [['hinter', 'nach'], ['Präposition'], [[''], [''], ['kunād']]],
    'nux': [['Name', 'Bezeichnung', 'Kennung'], ['Nomen'], [[''], [''], ['']]],
    'ûrux': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'kudunað': [['Mörder', 'Töter'], ['Nomen'], [[''], ['kudunaður'], ['']]],
    'gak': [['Ort', 'Platz', 'Stätte', 'Stelle'], ['Nomen'], [[''], [''], ['']]],
    'kad': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'rūlaƥ': [['Lied', 'Song'], ['Nomen'], [['rūl'], [''], ['']]],
    'rūlaður': [['singen', 'erzählen'], ['Verb'], [[''], [''], ['']]],
    'ūrnakdur': [['wehen', 'schweben', 'durch die Luft bewegen'], ['Verb'], [['ūrna', 'dukdar'], [''], ['']]],
    'dukur': [['Wagen', 'Vehikel', 'Fahrzeug'], ['Nomen'], [[''], [''], ['']]],
    'ðural': [['neu', 'neuartig'], ['Adjektiv'], [['ðurax'], ['ðuraxdur', 'ðuru'], ['ðuraldur', 'ðuralagdur']]],
    'ðuraldur': [['lernen', 'erlangen', 'aneignen', 'aufnehmen'], ['Verb'], [['ðural'], [''], ["xug-ðura'ul"]]],
    'dur': [['Dunkelheit', 'Schwärze', 'Finsternis', 'Nacht'], ['Nomen'], [[''], [''], ['duran', 'dûrul', 'dûrur']]],
    'duran': [['schwarz'], ['Farbe'], [['dur', 'dûrul'], [''], ['']]],
    'nūlan': [['weiß'], ['Farbe'], [['nūl'], [''], ['']]],
    'laƥradun': [['grün'], ['Farbe'], [['laƥrad'], [''], ['']]],
    'kanāxku': [['Ozean', 'Meer'], ['Nomen'], [['nāxku', 'ka'], ['runāxku'], ['']]],
    'ðagâral': [['20. Umlauf eines Monats', 'Traumtag'], ['Eigenname'], [['ðagar', 'dal'], [''], ['']]],
    'lunaƥ': [['großer Zeitraum', 'Ära', 'Zeitalter', 'Phase'], ['Nomen'], [['luna'], [''], ['']]],
    'ƥûkur': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'qal': [['wahr', 'echt', 'rein'], ['Adjektiv'], [[''], ['qalar', 'qalur'], ['']]],
    'rukula': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'āl-ðurul': [['lebensfeindlich', 'unaushaltbar', 'bedrohlich'], ['Adjektiv'], [['ður', 'āl-'], [''], ['']]],
    'rax': [['geheiligt', 'gesegnet', 'besonders', 'heilig'], ['Adjektiv'], [[''], [''], ['']]],
    'nūƥ': [['Natur', 'Erde', 'Ursprung', 'Magie'], ['Nomen'], [[''], ['ðar'], ['nūðar', 'nuƥral']]],
    'nūðar': [['Magie ausüben', 'zaubern', 'Myzar', "Mys'thar"], ['Verb/Eigenname'], [['nūƥ'], ['ðar'], ['']]],
    'ruðal': [['falsch', 'unecht', 'schlecht'], ['Adjektiv'], [['ruð'], [''], ['ðagar-ruðal', 'lagruðaldur', 'karuð']]],
    'ðagar-ruðal': [['Halluzination'], ['Nomen'], [['ðagar', 'ruðal'], [''], ['narud ðagar-ruðal']]],
    'narud': [['Pilz'], ['Nomen'], [[''], [''], ['narud ðagar-ruðal', 'narud gâlal']]],
    'narud ðagar-ruðal': [['Halluzinationspilz', 'Tagrut'], ['Eigenname'], [['narud', 'ðagar-ruðal'], [''], ['']]],
    'luq': [['Sitz', 'Stuhl'], ['Nomen'], [[''], ['luxdar'], ['']]],
    'nalda': [['Fackel', 'Lampe', 'Leuchte', 'Licht'], ['Nomen'], [['nal'], [''], ['']]],
    'ðuruð': [['Kreislauf des Lebens', ' (Konzept der Verbundenheit von Leben und Tod)'], ['Nomen'], [[''], [''], ['']]],
    'qar': [['einzig', 'einzigartig', 'allein', 'nur'], ['Adjektiv'], [['qa'], ['qad'], ['qadūr']]],
    'qadūr': [['Insel'], ['Nomen'], [['qar', 'dūr'], ['kadūr'], ['qadūr-nâƥal']]],
    'ƥulað': [['Puletsi'], ['Eigenname'], [[''], [''], ['']]],
    'ak': [['Ak', '(Insel)'], ['Eigenname'], [[''], [''], ['']]],
    'dunāku': [['Träne', 'Augenwasser'], ['Nomen'], [['duna', 'nāxku'], [''], ['nākudar']]],
    'nākudar': [['weinen', 'tränen'], ['Verb'], [['dunāku'], [''], ['']]],
    'nakdur': [['stehen'], ['Verb'], [[''], [''], ['nakul']]],
    'xuran': [['Leute', 'Personen', 'Gruppe an Personen'], ['Nomen'], [['xur'], [''], ['']]],
    'kalaran': [['gelb'], ['Farbe'], [[''], [''], ['']]],
    'lâraquk': [['Triesel'], ['Eigenname'], [['laquk', 'lar'], [''], ['']]],
    'nâƥal': [['kalt'], ['Adjektiv'], [[''], ['naƥ'], ['qadūr-nâƥal', 'naƥāx']]],
    'qadūr-nâƥal': [['Illoda', 'kalte Insel'], ['Eigenname'], [['qadūr', 'nâƥal'], [''], ['']]],
    "ka'ural": [['Wüste'], ['Nomen'], [['ka', 'ural'], [''], ['']]],
    'rūk': [['Ry (Stadt)'], ['Eigenname'], [[''], ['ruk'], ['']]],
    'qun axa': [['Qun Axa (Stadt)'], ['Eigenname'], [[''], [''], ['']]],
    'ðar': [['Zauberressource', 'Magiekraft', 'Mana'], ['Nomen'], [[''], ['nūðar', 'nūƥ'], ['']]],
    'kûludar': [['leuchten', 'scheinen'], ['Verb'], [['kûlu'], [''], ['']]],
    'gâlal': [['leuchtend', 'funkelnd', 'glitzernd'], ['Adjektiv'], [[''], ['gâla', 'galar', 'gâladur'], ['narud gâlal']]],
    'narud gâlal': [['Fluoreszierender Pilz', 'Flukte'], ['Eigenname'], [['narud', 'gâlal'], [''], ['']]],
    'nāruk': [['Wasserfall'], ['Nomen'], [['nāxku', 'rukdar'], [''], ['']]],
    'nakul': [['Tisch'], ['Nomen'], [['nakdur'], [''], ['']]],
    'nûlar': [['steinern', 'fest', 'hart', 'stark', 'schön', 'grau'], ['Adjektiv'], [['nûlad'], [''], ['']]],
    'nul': [['warm'], ['Adjektiv'], [['nûla'], ['nūl'], ['']]],
    'ralux': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'kað': [['an', 'offen', 'angestellt', 'aktiviert', 'laufend', 'in Betrieb', 'benutzbar'], ['Adjektiv'], [[''], ['kaðan', 'kaðal'], ['kaðadur', 'kaðuk']]],
    'kaðal': [['kräftig', 'stark', 'heftig', 'kraftvoll', 'eindrücklich'], ['Adjektiv'], [['kaðan'], ['kað', 'kaðadur'], ['']]],
    'kaðadur': [['anmachen', 'anstellen', 'öffnen', 'aktivieren', 'benutzen', 'angehen'], ['Verb'], [['kað'], ['kaðan', 'kaðal'], ['kaðuk']]],
    "xug-ðura'ul": [['Schule', 'Haus des Lernenden'], ['Nomen'], [['xug', 'ðuraldur'], [''], ['']]],
    'nud': [['wieder', 'nochmal', 'noch einmal', 'zum zweiten Mal'], ['Adjektiv'], [[''], ['nu'], ['']]],
    'ƥâladur': [['beeilen', 'sich beeilen', 'schnell machen', 'spurten'], ['Verb'], [['ƥal'], ['ƥâlukdar'], ['']]],
    'ƥâlukdar': [['rennen', 'schnell bewegen', 'sausen', 'huschen'], ['Verb'], [['ƥal'], ['ƥâladur'], ['']]],
    'gundar': [['Kind', 'Nachkomme', 'Nachfahre', 'Abkömmling', 'gebären', 'Kinder bekommen'], ['Verb'], [[''], ['gunda'], ['']]],
    'qulakdur': [['rufen', 'schreien', 'laut sein'], ['Verb'], [['qul', 'lâkadur'], [''], ['']]],
    'gāl': [['schwach', 'schlaff', 'kraftlos', 'müde'], ['Adjektiv'], [[''], ['gād'], ['']]],
    'dukadur': [['fahren', 'reisen', 'wegbewegen', 'hin und her bewegen'], ['Verb'], [[''], ['dukdar', 'dukar'], ["duka'ul"]]],
    'dukar': [['Reise', 'Fahrt'], ['Nomen'], [[''], ['dukadur', "duka'ul"], ['']]],
    "duka'ul": [['Reisender', 'Fahrender', 'Fahrer'], ['Nomen'], [['dukadur'], ['dukar'], ['']]],
    'xâlad': [['Lachen', 'Begeisterung', 'Erheiterung'], ['Nomen'], [[''], ['xal'], ['xâladur']]], 'xâladur': [['lachen', 'lächeln', 'amüsiert sein'], ['Verb'], [['xâlad'], ['xal'], ['']]],
    'ðun': [['in', 'innen', 'drinnen', 'rein'], ['Präposition'], [[''], [''], ['ðûkundar', 'ðunuldar']]],
    'ðûkundar': [['hereingehen', 'hineingehen', 'hereinbewegen', 'hineinbewegen'], ['Verb'], [['ðun', 'dukdar'], [''], ['ðukun']]],
    'ðukun': [['Eingang', 'Tür', 'Tor', 'Öffnung', 'Portal'], ['Nomen'], [['ðûkundar'], [''], ['']]],
    'lakdur': [['machen', 'tun', 'benutzen'], ['Verb'], [['lag', 'dukdar'], [''], ['lakur', 'laƥuldar', 'lâkar']]],
    'lakur': [['Werkzeug', 'Gerät', 'Ding'], ['Nomen'], [['lakdur'], [''], ['lunakur', 'lâkar']]],
    'xal': [['froh', 'fröhlich', 'glücklich', 'lachend', 'gut gelaunt'], ['Adjektiv'], [[''], ['xâlad', 'xâladur'], ['']]],
    'dârul': [['Pfeife'], ['Nomen'], [['dārul', 'rūl'], [''], ['daruldar']]],
    'daruldar': [['pfeifen', 'zischen'], ['Verb'], [['dârul'], [''], ['']]],
    'qaður-luna': [['immer'], ['Temporaladverb'], [['qaður', 'luna'], [''], ['']]],
    'ga-luna': [['jetzt', 'gerade', 'momentan', 'aktuell'], ['Temporaladverb'], [['luna'], [''], ['']]],
    'nuxur': [['Paar', 'Verbindung', 'Verbund'], ['Nomen'], [['nu', 'xur'], ['nuxul'], ['nuxdar']]],
    'nuxul': [['zusammen', 'gemeinsam', 'verbunden'], ['Adjektiv'], [['nu', 'xur'], ['nuxur'], ['nuxdar']]],
    'nuxdar': [['verbinden', 'kooperieren', 'zusammenarbeiten', 'zusammenbringen'], ['Verb'], [['nuxur', 'nuxul'], [''], ['']]],
    'lunakur': [['Uhr'], ['Nomen'], [['luna', 'lakur'], [''], ['']]],
    'kalur': [['Gegner', 'Feind', 'Bösewicht'], ['Nomen'], [[''], ['kal'], ['']]],
    'duqandur': [['kommen', 'hinkommen', 'ankommen'], ['Nomen'], [['dukdar', '-dān'], [''], ['duqan']]],
    'duk': [['Bewegung'], ['Nomen'], [[''], ['dukdar', 'dukal'], ['ðulðukdar']]],
    'nārul': [['warmes Getränk', 'Tee'], ['Nomen'], [[''], [''], ['']]],
    'duqan': [['Ankunft', 'Ankommen', 'Erscheinen'], ['Nomen'], [['duqandur'], [''], ['']]],
    'kunadur': [['haben', 'besitzen'], ['Verb'], [['kun'], ['kûnudar', 'rakundar'], ['']]],
    'ðulðukdar': [['drehen', 'umdrehen', 'im Kreis bewegen'], ['Verb'], [['duk', 'dukdar', 'ðulðu'], [''], ['']]],
    'lagruðaldur': [['lügen', 'falsches erzählen', 'falsch liegen'], ['Verb'], [['ruðal', 'lagrūdar'], [''], ['']]],
    'kâðadur': [['kämpfen', 'auseinandersetzen', 'streiten'], ['Verb'], [['kaðan'], [''], ['kaðar']]],
    'kaðar': [['Kampf', 'Auseinandersetzung', 'Streit'], ['Nomen'], [['kâðadur'], [''], ['']]],
    'qað': [['Teil', 'Stück', 'Part', 'Anteil', 'Abschnitt'], ['Nomen'], [['qa'], [''], ['']]],
    'qax': [['Jemand', 'Etwas'], ['Nomen'], [['qa'], [''], ['']]],
    'ruðax': [['Niemand'], ['Nomen'], [['ruð'], [''], ['']]],
    'rakundar': [['sich erinnern', 'erinnern', 'aufbewahren', 'konservieren', 'erhalten'], ['Verb'], [[''], ['kunadur'], ['']]],
    'kudunaður': [['töten', 'ermorden', 'schlachten'], ['Verb'], [['kûnudar', 'ðuru'], ['kudunað'], ['']]],
    'nādul': [['Flüssigkeit', 'Trank'], ['Nomen'], [['nādukadur'], ['nār', 'nādur'], ['']]],
    'nuƥral': [['gesund', 'normal', 'natürlich', 'richtig', 'fit'], ['Adjektiv'], [['nūƥ'], [''], ['ālnuƥal']]],
    'qaƥar': [['Kern', 'Punkt', 'Mittelpunkt', 'Herz', 'Herzstück'], ['Nomen'], [['qa'], [''], ['']]],
    'karuð': [['das große Böse', 'Übel', 'Böse', 'Untergang'], ['Nomen'], [['kal', 'ruðal'], [''], ['']]],
    'kar': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'kalar': [['Gefahr'], ['Nomen'], [[''], ['karal'], ['']]],
    'karal': [['gefährlich', 'bedrohlich'], ['Adjektiv'], [[''], ['kalar', 'kal'], ['']]],
    'ƥar': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'rak': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'nakur': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'nak': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'laqandur': [['heben', 'hochheben', 'anheben', 'tragen', 'halten'], ['Verb'], [['lag', 'qan'], [''], ['laqan']]],
    'laqan': [['Tasche', 'Beutel', 'Sack', 'Rucksack'], ['Nomen'], [['laqandur'], [''], ['']]],
    'ðuraƥdur': [['lang leben', 'alt werden', 'alt sein'], ['Verb'], [['ðuru', 'ðurudar'], [''], ['']]],
    'dunaƥdur': [['beobachten', 'anschauen', 'ansehen'], ['Verb'], [['dunadur'], [''], ['']]], 
    'dar': [['sein'], ['Verb'], [[''], [''], ['āldar']]],
    'kaxur': [['Gesellschaft', 'Volk', 'Stamm', 'Rasse', 'Rudel', 'Gemeinschaft', 'Tiergemeinschaft'], ['Nomen'], [['xur', 'ka'], [''], ['']]],
    'xalan': [['rot'], ['Farbe'], [[''], [''], ['']]],
    'kunād': [['Hinterteil', 'Schwanz'], ['Nomen'], [['kun', 'ād'], [''], ['']]],
    'nāk': [['Gewässer'], ['Nomen'], [[''], ['nāxku'], ['']]],
    'dūradur': [['stammen', 'abstammen'], ['Verb'], [['dūr'], [''], ['']]],
    'ru': [['wenig', 'klein'], ['Adjektiv'], [[''], [''], ['rugulūr', 'lagru']]],
    'runāxku': [['See', 'Teich', 'Tümpel'], ['Nomen'], [['nāxku'], ['kanāxku'], ['']]],
    'dūrak': [['Wenai'], ['Eigenname'], [['dūr'], [''], ['']]],
    'nâlak': [['Ahai'], ['Eigenname'], [['nal'], [''], ['']]],
    'nāxak': [['Wai'], ['Eigenname'], [['nāxku'], [''], ['']]],
    'ūrnak': [['Keine Überstezung'], [''], [[''], [''], ['']]],
    'ūrandak': [['Ranai'], ['Eigenname'], [['ūrna'], [''], ['']]],
    'quƥar': [['Kuberika'], ['Eigenname'], [[''], [''], ['']]],
    'raqath': [["Ras'qath"], ['Eigenname'], [[''], [''], ['']]],
    'ðâlaƥur': [['Stalbu', 'Minort'], ['Eigenname'], [[''], [''], ['']]],
    'darað': [['Dras'], ['Eigenname'], [[''], [''], ['']]],
    'duruð': [['Drus'], ['Eigenname'], [[''], [''], ['']]],
    'draðna': [['Drasna'], ['Eigenname'], [[''], [''], ['']]],
    'lagadur': [['bauen', 'erstellen', 'erschaffen', 'herstellen', 'aufbauen'], ['Verb'], [['lag'], ['ðagadur'], ['ðuralagdur']]],
    'ðuralagdur': [['erneuern', 'ersetzen'], ['Verb'], [['ðural', 'lagadur'], [''], ['']]],
    'dak': [['Gott', 'Gottheit'], ['Nomen'], [[''], [''], ['']]],
    'dakar': [['Gottesglaube', 'Glaube', 'Religion'], ['Nomen'], [[''], [''], ['kaðurak']]],
    'dâkadur': [['glauben', 'an Gott glauben'], ['Verb'], [[''], [''], ['']]],
    'ðulur': [['Lebenszeit', 'Leben'], ['Nomen'], [[''], ['ðuru'], ['']]],
    'kulur': [['Gewicht'], ['Nomen'], [['kul'], [''], ['kuldar']]],
    'kul': [['schwer', 'gewichtig'], ['Adjektiv'], [[''], [''], ['kuldar', 'kulur']]],
    'kuldar': [['wiegen'], ['Verb'], [['kul', 'kulur'], [''], ['']]],
    'dūrad': [['Herkunft', 'Abstammung'], ['Nomen'], [[''], [''], ['']]],
    'rugulūr': [['Gewächs', 'kleine Pflanze', 'Kraut'], ['Nomen'], [['ru', 'guldūr'], [''], ['']]],
    'kalaƥrad': [['Wiese', 'Grasgebiet'], ['Nomen'], [['laƥrad', 'ka'], [''], ['']]],
    'laƥuldar': [['verursachen', 'auslösen', 'bewirken'], ['Verb'], [['lakdur', 'ƥākul'], [''], ['']]],
    'ƥakuldar': [['lösen', 'Ergebnis erzielen', 'vollenden', 'fertig stellen', 'beenden'], ['Verb'], [['ƥākul'], [''], ['']]],
    'urad': [['sandig', 'pulverig', 'wie Staub'], ['Adjektiv'], [['ural'], [''], ['raduk']]],
    'raduk': [['Pulver', 'Staub', 'Puder'], ['Nomen'], [['urad'], [''], ['']]],
    'gulðar': [['Blüte'], ['Nomen'], [['guldūr'], [''], ['']]],
    'duqardur': [['herauskommen', 'weggehen', 'verlassen', 'gehen'], ['Verb'], [['dukdar', 'dār'], [''], ['']]],
    'ðunuldar': [['einschlafen'], ['Verb'], [['ðuguldar', 'ðun'], [''], ['']]],
    'nalgudar': [['bestehen aus', 'gemacht sein von/aus', 'zusammengestellt sein aus', 'sich zusammensetzen aus'], ['Verb'], [['nalgur'], [''], ['nargul']]],
    'nargul': [['zusammengestellt', 'zusammengesetzt', 'aus verschiedenen Teilen bestehend'], ['Verb'], [['nalgur', 'nalgudar'], [''], ['']]],
    'ƥur-nalgur': [['Die vier Elemente'], ['Eigenname'], [[''], [''], ['']]],
    'lagru': [['Finger'], ['Nomen'], [['lag', 'ru'], [''], ['']]],
    'aðradur': [['schmecken'], ['Verb'], [['aðrak'], [''], ['']]],
    'âkana': [['Akamah'], ['Eigenname'], [[''], [''], ['']]],
    'dûrur': [['nachts'], ['Temporaladverb'], [['dûrul', 'dur'], [''], ['']]],
    'dâlar': [['tagsüber', 'tags'], ['Temporaladverb'], [['dal'], [''], ['']]],
    'kaðuk': [['Schlüssel', 'Öffner'], ['Nomen'], [['kaðadur', 'kað'], [''], ['kaðurak']]],
    'kaðurak': [['Versiegeltes Schloss'], ['Eigenname'], [['kaðuk', 'dakar'], [''], ['']]],
    'âdarul': [['Ruhe', 'Stille'], ['Nomen'], [['āl-', 'dārul'], ['âdalur'], ['']]],
    'âdalur': [['still', 'ruhig', 'leise', 'beruhigt', 'gelassen', 'entspannt'], ['Adjektiv'], [[''], ['âdarul'], ['']]],
    'âdarul lagdur': [['beruhigen', 'runterbringen', 'entspannen', 'jemanden entspannen', 'zur Ruhe kommen', 'jemanden zur Ruhe bringen'], ['Verb'], [[''], [''], ['']]],
    'gudundar': [['schaffen', 'gewinnen', 'siegen'], ['Verb'], [[''], ['gudun'], ['gudul']]],
    'gudul': [['siegreich', 'erfolgreich'], ['Adjektiv'], [['gudun', 'gudundar'], [''], ['']]],
    'kaðandur': [['drücken', 'schieben'], ['Verb'], [['kaðan'], [''], ['']]],
    'xul': [['Hälfte', 'halb'], ['Zahl'], [[''], [''], ['qaxul']]],
    'qaxul': [['anderthalb'], ['Zahl'], [['qa', 'xul'], [''], ['']]],
    'gûladun': [['Gebirge'], ['Nomen'], [['gûlad'], [''], ['']]],
    'lâkar': [['Handwerk', 'Handwerken'], ['Nomen'], [['lakur', 'lakdur'], [''], ['lâkaxur']]],
    'lâkaxur': [['Mensch'], ['Eigenname'], [['lâkar', 'xur'], [''], ['']]],
    'dra': [['Drah'], ['Eigenname'], [[''], [''], ['']]],
    'kadūgul': [['Kontinent'], ['Nomen'], [['kadūr', 'gulur'], [''], ['']]],
    'guqudāndur': [['anpassen', 'sich anpassen', 'angleichen', 'sich angleichen', 'hinwandeln', 'in etwas verwandeln'], ['Verb'], [['guqudar', '-dān'], [''], ['']]],
    'kundar': [['aussehen', 'erscheinen'], ['Verb'], [['kun'], [''], ['']]],
    'āldar': [['tot', 'verstorben', 'verschieden', 'nicht existent'], ['Adjektiv'], [['āl-', 'dar'], [''], ['']]],
    'ālnuƥal': [['anders', 'unterschiedlich'], ['Ajdektiv'], [['nuƥral', 'āl-'], [''], ['']]],
    'naƥāx': [['Eis'], ['Nomen'], [['nāxku', 'nâƥal'], [''], ['']]],
    'ūrnaƥal': [['Schnee'], ['Nomen'], [[''], [''], ['']]],
    'dūran': [['braun'], ['Farbe'], [['dūr'], [''], ['']]]
}
function write_d() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "ð"
    search()
}

function write_f() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "ƥ"
    search()
}

function write_a() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "ā"
    search()
}

function write_u() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "ū"
    search()
}

function write_doppela() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "â"
    search()
}

function write_doppelu() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "û"
    search()
}


function search() {
    let resultsContainer = document.getElementById("results");
    let resultItems = document.getElementsByClassName("resultItem");
    let input = document.getElementById("searchbar").value
    let wort1 = document.getElementById("wort1")
    let wort2 = document.getElementById("wort2")
    let wort3 = document.getElementById("wort3")
    let wort4 = document.getElementById("wort4")
    let uebersetzung1 = document.getElementById("uebersetzung1")
    let uebersetzung2 = document.getElementById("uebersetzung2")
    let uebersetzung3 = document.getElementById("uebersetzung3")
    let uebersetzung4 = document.getElementById("uebersetzung4")
    let pos1 = document.getElementById("pos1")
    let pos2 = document.getElementById("pos2")
    let pos3 = document.getElementById("pos3")
    let pos4 = document.getElementById("pos4")
    let root1 = document.getElementById("root1")
    let root2 = document.getElementById("root2")
    let root3 = document.getElementById("root3")
    let root4 = document.getElementById("root4")
    let rel1 = document.getElementById("rel1")
    let rel2 = document.getElementById("rel2")
    let rel3 = document.getElementById("rel3")
    let rel4 = document.getElementById("rel4")
    let derv1 = document.getElementById("derv1")
    let derv2 = document.getElementById("derv2")
    let derv3 = document.getElementById("derv3")
    let derv4 = document.getElementById("derv4")


    
    Object.entries(lex).forEach(([key, value])=>{
        if ((input == key) || (value[0].includes(input))) {
            if ((wort1.innerText)&&(wort1.innerText!=key)) {
                if ((wort2.innerText)&&wort2.innerText!=key) {
                    wort3.innerText = wort2.innerText
                    pos3.innerText= pos2.innerText
                    uebersetzung3.innerText = uebersetzung2.innerText
                    root3.innerText = root2.innerText
                    rel3.innerText = rel2.innerText
                    derv3.innerText = derv2.innerText
                    
                }
                wort2.innerText = wort1.innerText
                pos2.innerText = pos1.innerText
                uebersetzung2.innerText = uebersetzung1.innerText
                root2.innerText = root1.innerText
                rel2.innerText = rel1.innerText
                derv2.innerText = derv1.innerText
            }
            wort1.innerText = key
            uebersetzung1.innerText = value[0].join(", ")
            pos1.innerText = value[1]
            console.log(value[1])
            if (value[1]==['']) {
                console.log("jaja")
            }
            else {
                root1.innerText = "Wurzel: " + value[2][0].join(", ")
                rel1.innerText = "Verwandte Worte: " + value[2][1].join(", ")
                derv1.innerText = "Abgeleitete Worte: " + value[2][2].join(", ")           
            }
        }
        
    })



};
