const lex = {
    "xur": [['Person', 'Lebewesen', "Guqu'al", 'Wesen', 'Form', 'man'], ['Nomen'], [[''], ['rux'], ['dûqur', 'dunaxur', 'lûqur', 'axaxur', 'nāxur', 'ūrnaxur', 'dūxur', 'ðuxur', 'qaður', 'xuran', 'nuxur', 'nuxul', 'kaxur', 'lâkaxur']]], 
    "rux": [['Sprache', 'Sprache der Guqual'], ['Nomen'], [[''], ['xur', 'ruqdar', 'ruq'], ['nārux', 'dûrux', 'lugrux', 'dugrux', 'ūrnarux', 'axarux', 'dunarux', 'ruqdar', 'rûkundar', 'lagrūdar']]], 
    "gul": [['groß', 'großartig', 'bedeutend', 'viel', 'gut', 'sehr'], ['Adjektiv'], [[''], [''], ['guldur', 'guldūr', 'gûlad', 'gulrað', 'gulur', 'gulak']]], 
    "a-": [['[bestimmter Artikel]'], ['Artikel'], [[''], ['gu-', 'ga-'], ['a-dal', 'a-gal', 'a-kral', 'a-dārulūn', 'ā-', 'āl-', 'ūl-', 'ra-', 'ār-']]], 
    "dal": [['Tag', 'Umlauf'], ['Nomen'], [[''], [''], ['a-dal', 'nādal', 'nulâdal', 'gulâdal', 'nûlukdal', 'âdal', 'naldal', 'kundal', 'ðurudal', 'dûral', 'ūrnadal', 'lûrudal', 'gâdal', 'âkadal', 'guðudal', 'ðagâral', 'dâlar']]], 
    "gal": [['Monat', 'Mondlauf', 'Mond'], ['Nomen'], [[''], [''], ['a-gal', 'gal-krul', 'gâdal']]], 
    "lâkadur": [['reden', 'sprechen', 'handeln (tauschen)'], ['Verb'], [['lak'], [''], ['qulakdur']]], 
    "dûqur": [['Draske'], ['Eigenname'], [['dukdar', 'xur'], ['dugrux'], ['']]], 
    "duna": [['Auge'], ['Nomen'], [[''], [''], ['dunaxur', 'dunarux', 'dunadur', 'dunāku']]], 
    "nādukal": [['Fluss'], ['Nomen'], [['nāxku', 'dukdar', 'dukal'], [''], ['nādukadur']]], 
    "dūr": [['Erde', 'Boden', 'Basis', 'Ursprung'], ['Nomen'], [[''], ['dūl'], ['dūxur', 'dûrux', 'guldūr', 'rûqur', 'dûral', 'kadūr', 'qadūr', 'dūradur', 'dūrak', 'dūran']]], 
    "ūrna": [['Himmel', 'Luft', 'Gott'], ['Nomen'], [[''], [''], ['ūrnarux', 'ūrnaxur', 'ūrnâqu', 'ūrnadur', 'ûrukdar', 'ūrnadal', 'ūrnakdur', 'ūrandak', 'ūrnaƥal']]], 
    "ūrnâqu": [['Regen'], ['Nomen'], [['ūrna', 'nāxku'], [''], ['nâqudar']]], 
    "qna": [['Festung', 'Burg', 'befestigte Stadt'], ['Nomen'], [[''], [''], ['']]], 
    "qun": [['Festung', 'Burg', 'befestigte Stadt'], ['Nomen'], [[''], [''], ['']]], 
    "kral": [['Jahr', 'Ablauf', 'Sonne'], ['Nomen'], [[''], [''], ['a-kral']]], 
    "gunda": [['jung'], ['Adjektiv'], [[''], ['gundar'], ['']]], 
    "dukdar": [['bewegen', 'fortbewegen', 'laufen', 'gehen'], ['Verb'], [[''], ['dukadur', 'duk'], ['dugrux', 'dûqur', 'nādukal', 'dukal', 'nādukdar', 'ûrukdar', 'dûrukdar', 'ūrnakdur', 'ðûkundar', 'lakdur', 'duqandur', 'ðulðukdar', 'duqardur', 'dukur']]], 
    "nâqudar": [['regnen'], ['Verb'], [['ūrnâqu', 'nāxku'], [''], ['']]], 
    "guqudar": [['sich wandeln', 'verwandeln', 'sich ändern', 'verändern', 'geboren werden', 'erschaffen werden'], ['Verb'], [[''], [''], ['guður', "guqu'al", 'guqudāndur']]], 
    "axa": [['alt'], ['Adjektiv'], [[''], [''], ['axarux', 'axaxur', 'âxadur']]], 
    "dunaxur": [['Augling'], ['Eigenname'], [['duna', 'xur'], ['dunarux'], ['']]], 
    "dunadur": [['sehen', 'schauen', 'gucken', 'blicken'], ['Verb'], [['duna'], [''], ['dunaƥdur', 'dunradur']]], 
    "nāxur": [['Amaka'], ['Eigenname'], [['nāxku', 'xur'], ['nārux'], ['']]], 
    "dūxur": [['Avzitil'], ['Eigenname'], [['dūr', 'xur'], ['dûrux'], ['']]], 
    "lukdar": [['wandern', 'weit laufen', 'weite Strecken zurücklegen', 'umherwandern'], ['Verb'], [[''], [''], ['lugrux', 'lûqur']]], 
    "lûqur": [['Vadonier'], ['Eigenname'], [['lukdar', 'xur'], ['lugrux'], ['']]], 
    "kûlu": [['Licht'], ['Nomen'], [[''], [''], ['kûludar']]], 
    "ruqdar": [['schreiben'], ['Verb'], [['ruq'], ['rûqudar', 'rux'], ['']]], 
    "ruk": [['unten', 'tief'], ['Adjektiv'], [[''], ['rūk'], ['rûqur', 'rukdān', 'rukdāndur', 'rukdar', 'ruqalun', 'laquk', 'rûkur', 'dûrukdar']]], 
    "qan": [['oben', 'hoch'], ['Präposition'], [['qa'], [''], ['qandān', 'qanar', 'dûqandur', 'laqandur', 'qanak']]], 
    "dārul": [['Wind'], ['Nomen'], [[''], [''], ['a-dārulūn', 'dārulaƥ', 'dārulan', 'dârul', 'âdarul']]], 
    "âkadur": [['wissen', 'können'], ['Verb'], [['akar', 'akal'], [''], ['']]], 
    "ūd": [['Essen', 'Nahrung'], ['Nomen'], [[''], [''], ['ûdar', 'ƥarūdar']]], 
    "qural": [['Familie', 'Gemeinschaft'], ['Nomen'], [[''], [''], ['']]], 
    "lūnad": [['Krieg', 'Katastrophe', 'Schrecken'], ['Nomen'], [['lūn'], [''], ['kalūnad']]], 
    "luxdar": [['sitzen'], ['Verb'], [[''], ['luq'], ['']]], 
    "kûdudar": [['sammeln', 'ansammeln', 'versammeln'], ['Verb'], [[''], [''], ['kûdur']]], 
    "nūk": [['Tod'], ['Nomen'], [[''], [''], ['nûkudar', 'nuqal']]], 
    "ralxū": [['Gebiet', 'Umgebung'], ['Nomen'], [[''], [''], ['']]], 
    "lûrad": [['hell', 'Tageszeit'], ['Nomen'], [['lûru'], ['lurul'], ['lûran']]], 
    "kûnudar": [['nehmen', 'an sich nehmen'], ['Verb'], [['kun', '-gūn'], ['kunadur'], ['rûkundar', 'kudunaður']]], 
    "kûnadur": [['riechen', 'mögen', 'gut finden'], ['Verb'], [['kuna'], [''], ['']]], 
    "dûrul": [['dunkel', 'Nacht'], ['Nomen'], [['dur'], [''], ['dûrudar', 'ðugul', 'duran', 'dûrur']]], 
    "a-dal": [['heute'], ['Temporaladverb'], [['a-', 'dal'], [''], ['']]], 
    "a-gal": [['diesen Monat'], ['Temporaladverb'], [['a-', 'gal'], [''], ['']]], 
    "a-kral": [['dieses Jahr'], ['Temporaladverb'], [['a-', 'kral'], [''], ['']]], 
    "ûdar": [['essen'], ['Verb'], [['ūd'], [''], ['ƥarūdar']]], 
    "luna": [['Zeit', 'Geschichte', 'Historie'], ['Nomen'], [[''], [''], ['lunaƥ', 'qaður-luna', 'ga-luna', 'lunakur']]], 
    "lûru": [['Sonne'], ['Nomen'], [[''], [''], ['lûru-krul', 'lûrudal', 'lûrad', 'lurul', 'lûrunað']]], 
    "âdar": [['Baum', 'Holz'], ['Nomen'], [[''], [''], ['âdal']]], 
    "nûkudar": [['sterben'], ['Verb'], [['nūk'], ['nuqal'], ['']]], 
    "u-": [['und'], ['Konjunktion'], [[''], [''], ['']]], 
    "āl-": [['nicht', 'ohne'], ['Negation'], [['a-'], ['gul-', 'gāl-', 'ālun', 'ānul'], ['āl-ðurul', 'âdarul', 'āldar', 'ālnuƥal']]], 
    "ā-": [['[und+Artikel]'], ['Artikel'], [['a-'], ['ugu-', 'uga-'], ['']]], 
    "nādur": [['trinken'], ['Verb'], [['nāxku', 'nār'], ['nādul'], ['']]], 
    "dûrudar": [['schlafen'], ['Verb'], [['dûrul'], [''], ['']]], 
    "dul": [['Stadt'], ['Nomen'], [[''], [''], ['dûluruð', 'qâladul']]], 
    "xuq": [['Kopf'], ['Nomen'], [[''], [''], ['']]], 
    "kaðan": [['Kraft', 'Gewalt', 'Stärke'], ['Nomen'], [[''], ['kað', 'kaðadur'], ['kaðal', 'kâðadur', 'kaðandur']]], 
    "ûlud": [['Wald'], ['Nomen'], [[''], [''], ['']]], 
    "guldur": [['wachsen', 'wachsen einer Pflanze'], ['Verb'], [['gul'], ['guldūr', 'gûlad'], ['guluð']]], 
    "guldūr": [['Pflanze', 'Gewächs'], ['Nomen'], [['gul', 'dūr'], ['guldur', 'gûlad'], ['rugulūr', 'gulðar']]], 
    "gûlad": [['Berg'], ['Nomen'], [['gul', 'nûlad'], ['guldur', 'guldūr', 'nûlad'], ['gulâdal', 'gûladun']]], 
    "rûqur": [['Tal', 'Absenke'], ['Nomen'], [['ruk', 'dūr'], [''], ['']]], 
    "larnaqa": [[], [''], [[''], [''], ['']]], 
    "nûluk": [['Felsen', 'Fels'], ['Nomen'], [[''], ['nûlad'], ['nûlukdal']]], 
    "-ūn": [['mit'], ['Präposition'], [[''], [''], ['a-dārulūn']]], 
    "ūl-": [['[und+neg+Artikel]'], ['Artikel'], [['a-'], ['ugul-', 'gūl-'], ['']]], 
    "ðāndrug": [['Alphabet'], ['Nomen'], [[''], [''], ['']]], 
    "a-dārulūn": [['Richtung'], ['Nomen'], [['a-', 'dārul', '-ūn'], [''], ['']]], 
    "xaradūn": [['Xaraton', 'Südosten'], ['Eigenname'], [['ƥuradūn', 'xar'], [''], ['dārxad']]], 
    "adûranð": [[], [''], [[''], [''], ['']]], 
    "lûrunað": [['Loromoth', 'Nordwesten'], ['Eigenname'], [['lûru'], [''], ['dārðalun', 'ƥâralur']]], 
    "ƥârān": [['Wirinima', 'Südwesten'], ['Eigenname'], [['ƥârul'], [''], ['ƥaxdūn', 'ƥâralur']]], 
    "dārðaru": [['Berethao', 'Nordosten'], ['Eigenname'], [['dār', 'ðuru'], [''], ['dārxad', 'dārðalun']]], 
    "uldūr": [['Schrift', 'Geschriebenes', 'Niederschrift'], ['Nomen'], [[''], [''], ["ka'uldūr"]]], 
    "nurguð": [['Geschichte', 'Erzählung', 'Märchen'], ['Nomen'], [[''], [''], ['']]], 
    "ðagar": [['Gedanke', 'Konzept', 'Traum', 'Plan', 'Idee'], ['Nomen'], [[''], ['ðâladur'], ['ðagadur', 'ðugul', 'ðagudar', 'ðagâral', 'ðagar-ruðal']]], 
    "gulrað": [['Turm'], ['Nomen'], [['gul'], [''], ['']]], 
    "ðâladur": [['denken', 'nachdenken', 'überlegen'], ['Verb'], [[''], ['ðagadur', 'ðagar'], ['']]], 
    "ðulðu": [['rund'], ['Adjektiv'], [[''], ['ðulður'], ['ðulðudar', 'ðulðukdar']]], 
    "ðulður": [['Kugel', 'runder Gegenstand', "Cul'thur", 'Auge'], ['Nomen'], [[''], ['ðulðu'], ['ðulðudar']]], 
    "ðuru": [['Leben', 'Existenz', 'Suru'], ['Nomen'], [[''], ['ðural', 'ruð', 'ðulur'], ['ðurudar', "ðuruðu'a", 'ðuxur', 'guður', 'ðurudal', 'ðuraxdur', 'qaðurdar', 'ðurax', 'qaður', 'kudunaður', 'ðuraƥdur', 'dārðaru']]], 
    "ðurudar": [['leben', 'existieren'], ['Verb'], [['ðuru'], ["ðuruðu'a", 'ðuraxdur', 'qaðurdar'], ['ðuraƥdur']]], 
    "ðulðudar": [['rollen', 'bewegen der Himmelskörper', 'vergehen des Tages', 'vergehen von Zeit'], ['Verb'], [['ðulðu', 'ðulður'], [''], ['']]], 
    "gûluð": [['Karte', 'Landkarte'], ['Nomen'], [[''], [''], ['']]], 
    "akdūl": [['links'], ['Präposition'], [[''], [''], ['akdūldān']]], 
    "ðadudar": [[], ['Verb'], [[''], [''], ['']]], 
    "dûluruð": [['kleine Stadt', 'Dorf'], ['Nomen'], [['dul', '-(û)ruð'], [''], ['']]], 
    "kuna": [['Nase'], ['Nomen'], [[''], [''], ['kûnadur']]], 
    "-(û)ruð": [['[Diminutiv]'], ['Diminutiv'], [[''], [''], ['dûluruð']]], 
    "gâranul": [[], [''], [[''], [''], ['']]], 
    "ūlrad": [['rechts'], ['Präposition'], [[''], [''], ['ūlradān']]], 
    "râdūl": [['Ding', 'Sache', 'Etwas', 'Gegenstand', 'Objekt', 'Item'], ['Nomen'], [[''], [''], ['dunradur']]], 
    "gâladur": [['scheinen', 'glänzen', 'funkeln', 'glitzern', 'blitzen'], ['Verb'], [['gâla'], ['gâlal'], ['galar']]], 
    "galadur": [[], ['Verb'], [[''], [''], ['']]], 
    "galan": [['Wort'], ['Nomen'], [[''], [''], ['kagalan']]], 
    "nalgur": [['Konsistenz', 'Beschaffenheit', 'Kern', 'Element', 'woraus etwas besteht'], ['Nomen'], [[''], [''], ['nalgudar', 'nargul', 'ƥur-nalgur']]], 
    "nadūl": [[], [''], [[''], [''], ['']]], 
    "-dān": [['in Richtung', 'nach', 'zu'], ['Präposition'], [[''], [''], ['ūlrâdān', 'akdūldān', 'qandān', 'rukdān', 'duqandur', 'guqudāndur']]], 
    "ūrnadur": [['atmen', 'einatmen'], ['Verb'], [['ūrna'], [''], ['']]], 
    "rukdān": [['herunter', 'nach unten', 'hinunter', 'unter'], ['Präposition'], [['ruk', '-dān'], [''], ['']]], 
    "qandān": [['herauf', 'nach oben', 'hinauf'], ['Präposition'], [['qan', '-dān'], [''], ['']]], 
    "ðuruðu'a": [['Suruthua', 'Welt'], ['Eigenname'], [['ðuru'], ['ðurudar'], ['']]], 
    "akdūldān": [['nach links'], ['Präposition'], [['akdūl', '-dān'], [''], ['']]], 
    "ūlradān": [['nach rechts'], ['Präposition'], [['ūlrad', '-dān'], [''], ['']]], 
    "xug": [['Haus', 'Gebäude'], ['Nomen'], [[''], [''], ['kaxug', "xug-ðura'ul", 'ƥaxuq']]], 
    "durān": [[], [''], [[''], [''], ['']]], 
    "luga": [['Wal'], ['Nomen'], [[''], [''], ['']]], 
    "kā": [['ich'], ['Pronomen'], [[''], [''], ['']]], 
    "la": [['du'], ['Pronomen'], [[''], [''], ['']]], 
    "rā": [['er/sie/es'], ['Pronomen'], [[''], [''], ['']]], 
    "kān": [['wir'], ['Pronomen'], [[''], [''], ['']]], 
    "lan": [['ihr'], ['Pronomen'], [[''], [''], ['']]], 
    "rān": [['sie (Plural)'], ['Pronomen'], [[''], [''], ['']]], 
    "rukdāndur": [['(fig) sterben'], ['Verb'], [['ruk', 'dān'], [''], ['']]], 
    "qa": [['Ja', 'eins'], ['Ja', 'Zahl'], [[''], [''], ['qad', 'qar', 'qað', 'qax', 'qaƥar', 'qaxul', 'qal', 'qan']]], 
    "ruð": [['Nein', 'null', 'Tod'], ['Nomen'], [[''], ['ðuru'], ['ruðal', 'ruðax']]], 
    "ðagadur": [['konzipieren', 'entwerfen', 'ausdenken', 'kreieren', 'erschaffen', 'planen'], ['Verb'], [['ðagar'], ['ðâladur', 'lagadur'], ['ðagudar']]], 
    "rukdār": [[], [''], [[''], [''], ['']]], 
    "rukdar": [['nach unten bewegen', 'hinab bewegen', 'hinabsteigen', 'graben', 'ausheben', 'hinabfallen', 'fallen', 'heruntergehen', 'hinuntergehen'], ['Verb'], [['ruk'], [''], ['dûqandur', 'nāruk']]], 
    "ðuxur": [['Lebewesen', 'Tier'], ['Nomen'], [['ðuru', 'xur'], [''], ['']]], 
    "rûkundar": [['lesen', 'verstehen', 'heißen'], ['Verb'], [['rux', 'kûnudar'], [''], ['']]], 
    "nāxku": [['Wasser'], ['Nomen'], [[''], ['nāk'], ['nārux', 'nāxur', 'nādukal', 'ūrnâqu', 'nâqudar', 'nādur', 'nādukdar', 'nāl', 'nār', 'nākrul', 'nādal', 'kanāxku', 'dunāku', 'nāruk', 'runāxku', 'nāxak', 'naƥāx']]], 
    "gād": [['klein', 'wenig'], ['Adjektiv'], [[''], ['gāl'], ['']]], 
    "nûlad": [['Stein'], ['Nomen'], [[''], ['gûlad', 'nûluk'], ['gûlad', 'nulâdal', 'nûlar']]], 
    "nal": [['Feuer', 'Lagerfeuer'], ['Nomen'], [[''], [''], ['naldal', 'kanal', 'naldur', 'nalda', 'nâlak', 'nâlaƥuldar']]], 
    "dār": [['von', 'seit', 'aus'], ['Präposition'], [[''], [''], ['duqardur', 'dārðaru']]], 
    "lux": [[], [''], [[''], [''], ['']]], 
    "gurul": [['Fleisch'], ['Nomen'], [[''], [''], ['']]], 
    "axaxur": [['Elb'], ['Eigenname'], [['axa', 'xur'], ['axarux'], ['']]], 
    "ūrnaxur": [['Quork'], ['Eigenname'], [['ūrna', 'xur'], ['ūrnarux'], ['']]], 
    "dunarux": [['Sprache der Auglinge'], ['Eigenname'], [['duna', 'rux'], ['dunaxur'], ['']]], 
    "dûrux": [['Sprache der Avzitil'], ['Eigenname'], [['dūr', 'rux'], ['dūxur'], ['']]], 
    "nārux": [['Sprache der Amaka'], ['Eigenname'], [['nāxku', 'rux'], ['nāxur'], ['']]], 
    "lugrux": [['Sprache der Vadonier'], ['Eigenname'], [['lukdar', 'rux'], ['lûqur'], ['']]], 
    "dugrux": [['Sprache der Drasken'], ['Eigenname'], [['dukdar', 'rux'], ['dûqur'], ['']]], 
    "ūrnarux": [['Sprache der Quork'], ['Eigenname'], [['ūrna', 'rux'], ['ūrnaxur'], ['']]], 
    "axarux": [['Sprache der Elben'], ['Eigenname'], [['axa', 'rux'], ['axaxur'], ['']]], 
    "krūl": [['Krūl', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "qârad": [['Qârad', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "gul xad": [['Gul Xad', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "drâqul": [['Drâqul', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "gul qūd": [['Gul Qūd', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "gûluk": [['Gûluk', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "gârak": [['Gârak', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "nâkadur": [['Nâkadur', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "guldūn": [['Guldūn', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "dûnad": [['Dûnad', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "xa'ād": [['Vaiad', '[Insel]'], ['Eigenname'], [[''], [''], ['']]], 
    "gul gunud": [['Gul Gunud', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "narūd": [['Narūd', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "nadul": [['Nadul', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "qun xaqud": [['Qun Xaqud', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "dan": [['blau'], ['Adjektiv'], [[''], [''], ['']]], 
    "run": [['Ohr'], ['Nomen'], [[''], [''], ['rundar']]], 
    "runal": [['Zuhörer', 'Gesprächspartner'], ['Nomen'], [[''], [''], ['']]], 
    "larun": [[], [''], [[''], [''], ['']]], 
    "aral": [['dünn', 'schlank', 'mager', 'schmal'], ['Adjektiv'], [[''], [''], ['']]], 
    "lāg": [[], [''], [[''], [''], ['']]], 
    "qalar": [['Mitte', 'Oberhaupt-Titel der Guqual', 'Oberhaupt', 'Anführer', 'Herrscher', 'Balance', 'Gleichgewicht'], ['Nomen'], [[''], ['qalur', 'qal', 'qaraldur'], ['qalar-krul', 'qâladul', 'qaral', 'qalardur']]], 
    "qaðra": [['Frieden'], ['Nomen'], [['qaðardur'], [''], ['']]], 
    "ur-": [['oder'], ['Konjunktion'], [[''], [''], ['']]], 
    "ra-": [['[oder+Artikel]'], ['Artikel'], [['a-'], ['gur-', 'gar-'], ['']]], 
    "ār-": [['[oder+nicht+Artikel]'], ['Artikel'], [['a-'], ['āgur-', 'gār-'], ['']]], 
    "ga-": [['[bestimmterArtikel]'], ['Artikel'], [[''], ['a-', 'gu-'], ['uga-', 'gāl-', 'gūl-', 'gar-', 'gār-']]], 
    "uga-": [['[und+Artikel]'], ['Artikel'], [['ga-'], ['ugu-', 'ā-'], ['']]], 
    "gāl-": [['[nicht+Artikel]'], ['Artikel'], [['ga-'], ['gul-', 'āl-'], ['']]], 
    "gūl-": [['[und+nicht+Artikel]'], ['Artikel'], [['ga-'], ['ugul-', 'ūl-'], ['']]], 
    "gar-": [['[oder+Artikel]'], ['Artikel'], [['ga-'], ['gur-', 'ra-'], ['']]], 
    "gār-": [['[oder+nicht+Artikel]'], ['Artikel'], [['ga-'], ['āgur-', 'ār-'], ['']]], 
    "gu-": [['[bestimmterArtikel]'], ['Artikel'], [[''], ['a-', 'ga-'], ['ugu-', 'gul-', 'ugul-', 'gur-', 'āgur-']]], 
    "ugu-": [['[und+Artikel]'], ['Artikel'], [['gu-'], ['uga-', 'ā-'], ['']]], 
    "gul-": [['[nicht+Artikel]'], ['Artikel'], [['gu-'], ['gāl-', 'āl-'], ['']]], 
    "ugul-": [['[und+nicht+Artikel]'], ['Artikel'], [['gu-'], ['gūl-', 'ūl-'], ['']]], 
    "gur-": [['[oder+Artikel]'], ['Artikel'], [['gu-'], ['gar-', 'ra-'], ['']]], 
    "āgur-": [['[oder+nicht+Artikel]'], ['Artikel'], [['gu-'], ['gār-', 'ār-'], ['']]], 
    "ðugul": [['Schlaf'], ['Nomen'], [['ðagar', 'dûrul'], [''], ['ðuguldar', 'ðagudar']]], 
    "ðuguldar": [['schlafen'], ['Verb'], [['ðugul'], [''], ['ðagudar', 'ðunuldar']]], 
    "qalar-krul": [['Mondlaufmitte', 'Monatsmitte', '12. Umlauf eines Monats'], ['Eigenname'], [['qalar', '-krul'], [''], ['']]], 
    "-krul": [['Fest', '[Marker für Festtage]'], [''], [[''], [''], ['nākrul', 'lûru-krul', 'gal-krul', 'qalar-krul', 'ƥaqrul', 'ādqul']]], 
    "lag": [['Hand', 'Arm'], ['Nomen'], [[''], [''], ['lagdur', 'laquk', 'lakdur', 'laqandur', 'lagadur', 'lagru', 'lagakdur']]], 
    "lagdur": [['geben'], ['Verb'], [['lag'], [''], ['lagrūdar']]], 
    "kun": [['Körper'], ['Nomen'], [[''], ['kunda'], ['kûnudar', 'kundal', 'kunrūl', 'kunadur', 'kunād', 'kundar', 'rakundar']]], 
    "aðrak": [['Zunge', 'Geschmack'], ['Nomen'], [[''], [''], ['aðradur']]], 
    "ƥarnadul": [[], [''], [[''], [''], ['']]], 
    "ƥarla": [[], [''], [[''], [''], ['']]], 
    "qalur": [['Wahrheit', 'Richtige'], ['Nomen'], [[''], ['qalar', 'qal'], ['']]], 
    "dukal": [['Verb'], ['Nomen'], [['dukdar'], ['duk', 'dukur'], ['']]], 
    "ƥul": [['gegen', 'entgegen', 'aber', 'jedoch'], ['Adjektiv', 'Konjunktion'], [[''], [''], ['ƥulur', 'ƥûlaqdar']]], 
    "ƥāður": [[], [''], [[''], [''], ['']]], 
    "rundar": [['hören', 'zuhören', 'lauschen'], ['Verb'], [['run'], [''], ['']]], 
    "gal-krul": [['Mondfest', 'Mondfinsternis'], ['Eigenname'], [['gal', '-krul'], [''], ['']]], 
    "lûru-krul": [['Sonnenfest', 'Sonnenfinsternis'], ['Eigenname'], [['lûru', '-krul'], [''], ['']]], 
    "guður": [['Geburt'], ['Nomen'], [['guqudar', 'ðuru'], [''], ['guðudal']]], 
    "lak": [['Mund', 'Sprache'], ['Nomen'], [[''], [''], ['lâkadur']]], 
    "ƥalar": [['Haut', 'Farbe', 'Beschaffenheit'], ['Nomen'], [[''], [''], ['ƥaladur', 'ƥaluq', 'ƥaxuq']]], 
    "ƥaladur": [['fühlen', 'tasten', 'spüren', 'berühren', 'anfassen'], ['Verb'], [['ƥalar'], [''], ['ƥaluq', 'ƥaxuq']]], 
    "nu": [['zwei'], ['Zahl'], [[''], ['nud'], ['nuxur', 'nuxul']]], 
    "lar": [['drei'], ['Zahl'], [[''], [''], ['lâraquk']]], 
    "ƥur": [['vier'], ['Zahl'], [[''], [''], ['ƥur-nalgur', 'ƥuradūn']]], 
    "dāð": [['fünf'], ['Zahl'], [[''], [''], ['']]], 
    "dun": [['sechs'], ['Zahl'], [[''], [''], ['']]], 
    "xan": [['sieben'], ['Zahl'], [[''], [''], ['']]], 
    "gur": [['acht'], ['Zahl'], [[''], [''], ['']]], 
    "ðan": [['neun'], ['Zahl'], [[''], [''], ['']]], 
    "nādukdar": [['schwimmen'], ['Verb'], [['nāxku', 'dukdar'], [''], ['']]], 
    "ûrukdar": [['fliegen'], ['Verb'], [['ūrna', 'dukdar'], [''], ['uruk']]], 
    "ālun": [['Nichts', 'Leere'], ['Nomen'], [[''], ['āl-', 'ānul'], ['ruqalun']]], 
    "ruqalun": [['Loch', 'Grube', 'Mulde', 'Einkerbung'], ['Nomen'], [['ruk', 'ālun'], [''], ['']]], 
    "laquk": [['Bein', 'Fuß'], ['Nomen'], [['lag', 'ruk'], [''], ['lâraquk']]], 
    "guqu'al": [["Guqu'al"], ['Eigenname'], [['guqudar'], [''], ['']]], 
    "qad": [['alle', 'alles'], ['Nomen'], [['qa'], ['qar'], ['qaður', 'qaðak']]], 
    "qaður": [['jede', 'jeder', 'jedes', 'Ende', 'Stopp'], ['Nomen'], [['qad', 'xur', 'ðuru'], [''], ['qaðurdar', 'qaður-luna']]], 
    "akal": [['weise', 'allwissend', 'erfahren', 'intelligent'], ['Adjektiv'], [[''], ['akar'], ['âkadur', 'âkadal']]], 
    "akar": [['Wissen', 'Reichtum'], ['Nomen'], [[''], ['akal'], ['âkadur', 'âkadal']]], 
    "qanar": [['Höhe', 'Anhöhe', 'Erhebung', 'Spitze', 'Höhepunkt'], ['Nomen'], [['qan'], ['qanak'], ['']]], 
    "gulur": [['Größe', 'Weite'], ['Nomen'], [['gul'], [''], ['kadūgul', 'gulak']]], 
    "rûkur": [['Tiefe', 'Tiefpunkt'], ['Nomen'], [['ruk'], [''], ['']]], 
    "nuqal": [['tot', 'unlebendig'], ['Adjektiv'], [['nūk'], ['nûkudar'], ['']]], 
    "nāl": [['nass'], ['Adjektiv'], [['nāxku'], [''], ['']]], 
    "kûdur": [['Sammlung', 'Ansammlung', 'Haufen', 'Besitz'], ['Nomen'], [['kûdudar'], [''], ['']]], 
    "nār": [['Getränk', 'Trinkbares'], ['Nomen'], [['nāxku'], ['nādul'], ['nādur']]], 
    "nādukadur": [['fliessen'], ['Verb'], [['nādukal'], [''], ['nādul']]], 
    "ānul": [['leer'], ['Adjektiv'], [[''], ['ālun', 'āl-'], ['']]], 
    "ƥal": [['schnell', 'zügig'], ['Adjektiv'], [[''], [''], ['ƥâladur', 'ƥâlukdar']]], 
    "âxadur": [['altern', 'älter werden', 'wachsen', 'heranwachsen'], ['Verb'], [['axa'], [''], ['']]], 
    "ƥulur": [['Feind', 'Gegner', 'Widersacher'], ['Nomen'], [['ƥul'], [''], ['']]], 
    "laran": [['dick', 'breit', 'fett', 'ausgeprägt'], ['Adjektiv'], [[''], [''], ['']]], 
    "nākrul": [['Wasserfest'], ['Eigenname'], [['nāxku', '-krul'], [''], ['']]], 
    "nādal": [['3. Umlauf eines Monats'], ['Eigenname'], [['nāxku', 'dal'], [''], ['']]], 
    "nulâdal": [['2. Umlauf eines Monats'], ['Eigenname'], [['nûlad', 'dal'], [''], ['']]], 
    "gulâdal": [['23. Umlauf eines Monats', 'Monatsende'], ['Eigenname'], [['gûlad', 'dal'], [''], ['']]], 
    "nûlukdal": [['13. Umlauf eines Monats'], ['Eigenname'], [['nûluk', 'dal'], [''], ['']]], 
    "âdal": [['7. Umlauf eines Monats'], ['Eigenname'], [['âdar', 'dal'], [''], ['']]], 
    "naldal": [['22. Umlauf eines Monats'], ['Eigenname'], [['nal', 'dal'], [''], ['']]], 
    "kundal": [['15. Umlauf eines Monats'], ['Eigenname'], [['kun', 'dal'], [''], ['']]], 
    "ðurudal": [['11. Umlauf eines Monats'], ['Eigenname'], [['ðuru', 'dal'], [''], ['']]], 
    "dûral": [['14. Umlauf eines Monats'], ['Eigenname'], [['dūr', 'dal'], [''], ['']]], 
    "ðuxural": [['21. Umlauf eines Monats'], ['Eigenname'], [[''], [''], ['']]], 
    "guldûral": [['4. Umlauf eines Monats'], ['Eigenname'], [[''], [''], ['']]], 
    "ūrnadal": [['10. Umlauf eines Monats'], ['Eigenname'], [['ūrna', 'dal'], [''], ['']]], 
    "lûrudal": [['5. Umlauf eines Monats'], ['Eigenname'], [['lûru', 'dal'], [''], ['']]], 
    "gâdal": [['1. Umlauf eines Monats'], ['Eigenname'], [['gal', 'dal'], [''], ['']]], 
    "âkadal": [['6. Umlauf eines Monats'], ['Eigenname'], [['akar', 'akal', 'dal'], [''], ['']]], 
    "guðudal": [['16. Umlauf eines Monats'], ['Eigenname'], [['guður', 'dal'], [''], ['']]], 
    "galuq": [['Gloq'], ['Eigenname'], [[''], [''], ['']]], 
    "galar": [['Stern'], ['Nomen'], [['gâladur'], ['gâla', 'gâlal'], ['']]], 
    "ðagar-dan": [['Blauer Traum'], ['Eigenname'], [[''], [''], ['']]], 
    "uruk": [['Vogel', 'fliegendes Tier'], ['Nomen'], [['ûrukdar'], [''], ['']]], 
    "ðuraxdur": [['anfangen', 'beginnen', 'starten'], ['Verb'], [['ðuru', 'ðurax'], ['ðuru', 'ðurudar', 'qaðurdar'], ['']]], 
    "qaðurdar": [['enden', 'beenden', 'stoppen', 'aufhören', 'zu Ende gehen'], ['Verb'], [['ðuru', 'qaður'], ['ðuru', 'ðurudar', 'ðuraxdur'], ['']]], 
    "ƥuxur": [['Frucht'], ['Nomen'], [[''], [''], ['']]], 
    "raƥ": [['stark', 'viel', 'enorm'], ['Adjektiv'], [[''], [''], ['dārulaƥ']]], 
    "kuðul": [['schön', 'außergewöhnlich', 'besonders'], ['Adjektiv'], [[''], ['kuður'], ['']]], 
    "rūl": [['Klang', 'Sound', 'Ton', 'Geräusch', 'Laut'], ['Nomen'], [[''], [''], ['kunrūl', 'rūlaƥ', 'dârul']]], 
    "ƥākul": [['Lösung', 'Ergebnis', 'Entscheidung'], ['Nomen'], [[''], [''], ['laƥuldar', 'ƥakuldar', 'ƥākul dunradur']]], 
    "kal": [['schlecht', 'böse'], ['Adjektiv'], [[''], ['kalur', 'karal'], ['karuð']]], 
    "qur": [['Weg', 'Straße'], ['Nomen'], [[''], [''], ['']]], 
    "quxal": [['Gesetz', 'Regel', 'Bestimmung'], ['Nomen'], [[''], [''], ['']]], 
    "laƥrad": [['Gras'], ['Nomen'], [[''], [''], ['laƥradun', 'kalaƥrad']]], 
    "dārulaƥ": [['Sturm', 'Orkan', 'Tornado'], ['Nomen'], [['dārul', 'raƥ'], [''], ['']]], 
    "kuður": [['Schönheit', 'etwas Besonderes', 'etwas Außergewöhnliches', 'Besonderes', 'Außergewöhnliches'], ['Nomen'], [[''], ['kuðul'], ['']]], 
    "dārulan": [['Wetter', 'Winde'], ['Nomen'], [['dārul'], [''], ['']]], 
    "ural": [['Sand'], ['Nomen'], [[''], [''], ["ka'ural", 'urad', 'ural-kadūr']]], 
    "ūral": [[], [''], [[''], [''], ['']]], 
    "kadūr": [['Land', 'Gebiet', 'Gegend', 'Gelände'], ['Nomen'], [['dūr', 'ka'], ['qadūr'], ['kadūgul', 'ural-kadūr']]], 
    "kaður": [[], [''], [[''], [''], ['']]], 
    "dûqandur": [['springen', 'hochbewegen'], ['Verb'], [['qan', 'rukdar'], [''], ['']]], 
    "dûrukdar": [['fallen', 'hinfallen'], ['Verb'], [['dukdar', 'ruk'], [''], ['']]], 
    "kaxug": [['Schloß', 'Großhaus', 'großes Haus'], ['Nomen'], [['xug', 'ka'], [''], ['']]], 
    "ka": [['viel', 'oft'], ['Adjektiv'], [[''], [''], ['kaxug', 'kadūr', 'kanal', 'kagalan', "ka'uldūr", 'kadur', 'kanāxku', "ka'ural", 'kaxur', 'kalaƥrad', 'kalūnad']]], 
    "kunrūl": [['Stimme'], ['Nomen'], [['kun', 'rūl'], [''], ['']]], 
    "kanal": [['Brand', 'großes Feuer'], ['Nomen'], [['nal', 'ka'], [''], ['']]], 
    "naldur": [['brennen', 'verbrennen'], ['Verb'], [['nal'], [''], ['']]], 
    "luqak": [[], [''], [[''], [''], ['']]], 
    "guluð": [['Haar', 'Haare', 'Fell'], ['Nomen'], [['guldur'], [''], ['']]], 
    "kagalan": [['Geschichte', 'Erzählung'], ['Nomen'], [['ka', 'galan'], [''], ['']]], 
    "qâladul": [['Hauptstadt'], ['Nomen'], [['qalar', 'dul'], [''], ['']]], 
    "ður": [['Neuheit', 'Neuigkeit', 'etwas Neues'], ['Nomen'], [[''], [''], ['āl-ðurul']]], 
    "ƥarquð": [[], [''], [[''], [''], ['']]], 
    "rālun": [[], [''], [[''], [''], ['']]], 
    "ƥaxur": [['Perfektion', 'Vollkommenheit', 'Vollständigkeit'], ['Nomen'], [[''], ['ƥaxul'], ['']]], 
    "ƥaxul": [['ganz', 'perfekt', 'vollkommen', 'vollständig'], ['Adjektiv'], [[''], ['ƥaxur'], ['']]], 
    "ðurax": [['Anfang', 'Beginn', 'Start'], ['Nomen'], [['ðuru'], [''], ['ðuraxdur', 'ðural']]], 
    "dūl": [['trocken', 'erdig'], ['Adjektiv'], [[''], ['dūr'], ['']]], 
    "rūldar": [['klingen', 'Geräusche machen', 'tönen', 'singen'], ['Verb'], [[''], [''], ['']]], 
    "lagrūdar": [['sagen', 'reden'], ['Verb'], [['lagdur', 'rux'], [''], ['ƥûlaqdar', 'lagruðaldur']]], 
    "ðagudar": [['träumen', 'nachdenken', 'lösen', 'lernen'], ['Verb'], [['ðugul', 'ðuguldar', 'ðagadur', 'ðagar'], [''], ['']]], 
    "ka'uldūr": [['Buch', 'Schriften', 'Text'], ['Nomen'], [['ka', 'uldūr'], [''], ['']]], 
    "kadur": [['addieren', 'vervielfältigen', 'erweitern', 'vermehren', 'bereichern', 'hinzufügen'], ['Verb'], [['ka'], [''], ['']]], 
    "ƥûlaqdar": [['erwidern', 'antworten', 'entgegnen'], ['Verb'], [['ƥul', 'lagrūdar'], [''], ['']]], 
    "lūd": [[], [''], [[''], [''], ['']]], 
    "qadur": [['Zacken', 'Spitze'], ['Nomen'], [[''], [''], ['']]], 
    "ðugul-gul": [['der große Schlaf', '(Schlaf eines Anführers um bedeutende Probleme zu lösen oder Krisen zu bewältigen)'], ['Eigenname'], [[''], [''], ['']]], 
    "kalūnad": [['die große Katastrophe', '(ein nationaler Notstand)'], ['Eigenname'], [['ka', 'lūnad'], [''], ['']]], 
    "ƥûlaq": [['Antwort'], ['Nomen'], [[''], [''], ['']]], 
    "gâla": [['Glanz', 'Schein'], ['Nomen'], [[''], ['galar', 'gâlal'], ['gâladur']]], 
    "ragul": [['langsam'], ['Adjektiv'], [[''], [''], ['']]], 
    "ral": [[], [''], [[''], [''], ['']]], 
    "lax": [[], [''], [[''], [''], ['']]], 
    "rūqul": [['weich', 'angenehm', 'schön', 'sanft'], ['Adjektiv'], [[''], [''], ['']]], 
    "nûqur": [[], [''], [[''], [''], ['']]], 
    "gudan": [[], [''], [[''], [''], ['']]], 
    "kunda": [['Aussehen', 'Erscheinung'], ['Nomen'], [['kundar'], ['kun'], ['']]], 
    "naƥ": [['Kälte'], ['Nomen'], [[''], ['nâƥal'], ['']]], 
    "nukal": [['möglich', 'wenn', 'ob'], ['Adjektiv'], [[''], [''], ['']]], 
    "kadað": [[], [''], [[''], [''], ['']]], 
    "dûquk": [[], [''], [[''], [''], ['']]], 
    "gudun": [['Sieg', 'Erfolg', 'Gewinn'], ['Nomen'], [[''], ['gudundar'], ['gudul']]], 
    "kuqar": [[], [''], [[''], [''], ['']]], 
    "qul": [['laut'], ['Adjektiv'], [[''], [''], ['qulakdur']]], 
    "ād": [['hinter', 'nach'], ['Präposition'], [[''], [''], ['kunād', 'ādqul']]], 
    "nux": [['Name', 'Bezeichnung', 'Kennung'], ['Nomen'], [[''], [''], ['']]], 
    "ûrux": [[], [''], [[''], [''], ['']]], 
    "kudunað": [['Mörder', 'Töter'], ['Nomen'], [['kudunaður'], [''], ['']]], 
    "gak": [['Ort', 'Platz', 'Stätte', 'Stelle'], ['Nomen'], [[''], [''], ['lagakdur', 'qaðak']]], 
    "kad": [[], [''], [[''], [''], ['']]], 
    "rūlaƥ": [['Lied', 'Song'], ['Nomen'], [['rūl'], [''], ['']]], 
    "rūlaður": [['singen', 'erzählen'], ['Verb'], [[''], [''], ['']]], 
    "ūrnakdur": [['wehen', 'schweben', 'durch die Luft bewegen'], ['Verb'], [['ūrna', 'dukdar'], [''], ['']]], 
    "dukur": [['Wagen', 'Vehikel', 'Fahrzeug'], ['Nomen'], [['dukdar'], ['dukal'], ['']]], 
    "ðural": [['neu', 'neuartig'], ['Adjektiv'], [['ðurax'], ['ðuraxdur', 'ðuru'], ['ðuraldur', 'ðuralagdur']]], 
    "ðuraldur": [['lernen', 'erlangen', 'aneignen', 'aufnehmen'], ['Verb'], [['ðural'], [''], ["xug-ðura'ul"]]], 
    "dur": [['Dunkelheit', 'Schwärze', 'Finsternis', 'Nacht'], ['Nomen'], [[''], [''], ['duran', 'dûrul', 'dûrur']]], 
    "duran": [['schwarz'], ['Adjektiv'], [['dur', 'dûrul'], [''], ['']]], 
    "lûran": [['weiß'], ['Adjektiv'], [['lûrad'], [''], ['']]], 
    "laƥradun": [['grün'], ['Adjektiv'], [['laƥrad'], [''], ['']]], 
    "kanāxku": [['Ozean', 'Meer'], ['Nomen'], [['nāxku', 'ka'], ['runāxku'], ['']]], 
    "ðagâral": [['20. Umlauf eines Monats', 'Traumtag'], ['Nomen'], [['ðagar', 'dal'], [''], ['']]], 
    "lunaƥ": [['großer Zeitraum', 'Ära', 'Zeitalter', 'Phase'], ['Nomen'], [['luna'], [''], ['']]], 
    "ƥûkur": [[], [''], [[''], [''], ['']]], 
    "qal": [['wahr', 'echt', 'rein'], ['Adjektiv'], [['qa'], ['qalar', 'qalur'], ['']]], 
    "rukula": [['Salat', 'Pflanzenmix'], ['Nomen'], [[''], [''], ['']]], 
    "āl-ðurul": [['lebensfeindlich', 'unaushaltbar', 'bedrohlich'], ['Adjektiv'], [['ður', 'āl-'], [''], ['']]], 
    "rax": [['geheiligt', 'gesegnet', 'besonders', 'heilig'], ['Adjektiv'], [[''], [''], ['']]], 
    "nūƥ": [['Natur', 'Erde', 'Ursprung', 'Magie'], ['Nomen'], [[''], ['ðar'], ['nūðar', 'nuƥral']]], 
    "nūðar": [['Magie ausüben', 'zaubern', 'Myzar', "Mys'thar"], ['Nomen'], [['nūƥ'], ['ðar'], ['']]], 
    "ruðal": [['falsch', 'unecht', 'schlecht'], ['Adjektiv'], [['ruð'], [''], ['ðagar-ruðal', 'lagruðaldur', 'karuð']]], 
    "ðagar-ruðal": [['Halluzination'], ['Nomen'], [['ðagar', 'ruðal'], [''], ['narud ðagar-ruðal']]], 
    "narud": [['Pilz'], ['Nomen'], [[''], [''], ['narud ðagar-ruðal', 'narud gâlal']]], 
    "narud ðagar-ruðal": [['Halluzinationspilz', 'Tagrut'], ['Nomen'], [['narud', 'ðagar-ruðal'], [''], ['']]], 
    "luq": [['Sitz', 'Stuhl'], ['Nomen'], [[''], ['luxdar'], ['']]], 
    "nalda": [['Fackel', 'Lampe', 'Leuchte', 'Licht'], ['Nomen'], [['nal'], [''], ['']]], 
    "ðuruð": [['Kreislauf des Lebens', ' (Konzept der Verbundenheit von Leben und Tod)'], ['Nomen'], [[''], [''], ['']]], 
    "qar": [['einzig', 'einzigartig', 'allein', 'nur'], ['Adjektiv'], [['qa'], ['qad'], ['qadūr']]], 
    "qadūr": [['Insel'], ['Nomen'], [['qar', 'dūr'], ['kadūr'], ['qadūr-nâƥal']]], 
    "ƥulað": [['Puletsi'], ['Eigenname'], [[''], [''], ['']]], 
    "ak": [['Ak', '(InselbeiWirinima)'], ['Nomen'], [[''], [''], ['']]], 
    "dunāku": [['Träne', 'Augenwasser'], ['Nomen'], [['duna', 'nāxku'], [''], ['nākudar']]], 
    "nākudar": [['weinen', 'tränen'], ['Verb'], [['dunāku'], [''], ['']]], 
    "nakdur": [['stehen'], ['Verb'], [[''], [''], ['nakul']]], 
    "xuran": [['Leute', 'Personen', 'Gruppe an Personen'], ['Nomen'], [['xur'], [''], ['']]], 
    "kalaran": [['gelb'], ['Adjektiv'], [[''], [''], ['']]], 
    "lâraquk": [['Triesel'], ['Eigenname'], [['laquk', 'lar'], [''], ['']]], 
    "nâƥal": [['kalt'], ['Adjektiv'], [[''], ['naƥ'], ['qadūr-nâƥal', 'naƥāx', 'ūrnaƥal']]], 
    "qadūr-nâƥal": [['Illoda', 'kalte Insel'], ['Eigenname'], [['qadūr', 'nâƥal'], [''], ['']]], 
    "ka'ural": [['Wüste'], ['Nomen'], [['ka', 'ural'], [''], ['']]], 
    "rūk": [['Ry'], ['Eigenname'], [[''], ['ruk'], ['']]], 
    "qun axa": [['Qun Axa', '[Stadt]'], ['Eigenname'], [[''], [''], ['']]], 
    "ðar": [['Zauberressource', 'Magiekraft', 'Mana'], ['Nomen'], [[''], ['nūðar', 'nūƥ'], ['']]], 
    "kûludar": [['leuchten', 'scheinen'], ['Verb'], [['kûlu'], [''], ['']]], 
    "gâlal": [['leuchtend', 'funkelnd', 'glitzernd'], ['Adjektiv'], [[''], ['gâla', 'galar', 'gâladur'], ['narud gâlal']]], 
    "narud gâlal": [['Fluoreszierender Pilz', 'Flukte'], ['Nomen'], [['narud', 'gâlal'], [''], ['']]], 
    "nāruk": [['Wasserfall'], ['Nomen'], [['nāxku', 'rukdar'], [''], ['']]], 
    "nakul": [['Tisch'], ['Nomen'], [['nakdur'], [''], ['']]], 
    "nûlar": [['steinern', 'fest', 'hart', 'stark', 'schön', 'grau'], ['Adjektiv'], [['nûlad'], [''], ['']]], 
    "lurul": [['warm'], ['Adjektiv'], [['lûru'], ['lûran'], ['']]], 
    "ralux": [[], [''], [[''], [''], ['']]], 
    "kað": [['an', 'offen', 'angestellt', 'aktiviert', 'laufend', 'in Betrieb', 'benutzbar'], ['Adjektiv'], [[''], ['kaðan', 'kaðal'], ['kaðadur', 'kaðuk']]], 
    "kaðal": [['kräftig', 'stark', 'heftig', 'kraftvoll', 'eindrücklich'], ['Adjektiv'], [['kaðan'], ['kað', 'kaðadur'], ['']]], 
    "kaðadur": [['anmachen', 'anstellen', 'öffnen', 'aktivieren', 'benutzen', 'angehen'], ['Verb'], [['kað'], ['kaðan', 'kaðal'], ['kaðuk']]], 
    "xug-ðura'ul": [['Schule', 'Haus des Lernenden'], ['Nomen'], [['xug', 'ðuraldur'], [''], ['']]], 
    "nud": [['wieder', 'nochmal', 'noch einmal', 'zum zweiten Mal'], ['Adjektiv'], [[''], ['nu'], ['']]], 
    "ƥâladur": [['beeilen', 'sich beeilen', 'schnell machen', 'spurten'], ['Verb'], [['ƥal'], ['ƥâlukdar'], ['']]], 
    "ƥâlukdar": [['rennen', 'schnell bewegen', 'sausen', 'huschen'], ['Verb'], [['ƥal'], ['ƥâladur'], ['']]], 
    "gundar": [['Kind', 'Nachkomme', 'Nachfahre', 'Abkömmling', 'gebären', 'Kinder bekommen'], ['Nomen'], [[''], ['gunda'], ['rugundar']]], 
    "qulakdur": [['rufen', 'schreien', 'laut sein'], ['Verb'], [['qul', 'lâkadur'], [''], ['qulak']]], 
    "gāl": [['schwach', 'schlaff', 'kraftlos', 'müde'], ['Adjektiv'], [[''], ['gād'], ['']]], 
    "dukadur": [['fahren', 'reisen', 'wegbewegen', 'hin und her bewegen'], ['Verb'], [[''], ['dukdar', 'dukar'], ["duka'ul"]]], 
    "dukar": [['Reise', 'Fahrt'], ['Nomen'], [[''], ['dukadur', "duka'ul"], ['']]], 
    "duka'ul": [['Reisender', 'Fahrender', 'Fahrer'], ['Nomen'], [['dukadur'], ['dukar'], ['']]], 
    "xâlad": [['Lachen', 'Begeisterung', 'Erheiterung'], ['Nomen'], [[''], ['xal'], ['xâladur']]], 
    "xâladur": [['lachen', 'lächeln', 'amüsiert sein'], ['Verb'], [['xâlad'], ['xal'], ['']]], 
    "ðun": [['in', 'innen', 'drinnen', 'rein'], ['Präposition'], [[''], [''], ['ðûkundar', 'ðunuldar']]], 
    "ðûkundar": [['hereingehen', 'hineingehen', 'hereinbewegen', 'hineinbewegen'], ['Verb'], [['ðun', 'dukdar'], [''], ['ðukun']]], 
    "ðukun": [['Eingang', 'Tür', 'Tor', 'Öffnung', 'Portal'], ['Nomen'], [['ðûkundar'], [''], ['']]], 
    "lakdur": [['machen', 'tun', 'benutzen'], ['Verb'], [['lag', 'dukdar'], [''], ['lakur', 'laƥuldar', 'lâkar']]], 
    "lakur": [['Werkzeug', 'Gerät', 'Ding'], ['Nomen'], [['lakdur'], [''], ['lunakur', 'lâkar']]], 
    "xal": [['froh', 'fröhlich', 'glücklich', 'lachend', 'gut gelaunt'], ['Adjektiv'], [[''], ['xâlad', 'xâladur'], ['']]], 
    "dârul": [['Pfeife'], ['Nomen'], [['dārul', 'rūl'], [''], ['daruldar']]], 
    "daruldar": [['pfeifen', 'zischen'], ['Verb'], [['dârul'], [''], ['']]], 
    "qaður-luna": [['immer'], ['Adjektiv'], [['qaður', 'luna'], [''], ['']]], 
    "ga-luna": [['jetzt', 'gerade', 'momentan', 'aktuell'], ['Adjektiv'], [['luna'], [''], ['']]], 
    "nuxur": [['Paar', 'Verbindung', 'Verbund'], ['Nomen'], [['nu', 'xur'], ['nuxul'], ['nuxdar']]], 
    "nuxul": [['zusammen', 'gemeinsam', 'verbunden'], ['Adjektiv'], [['nu', 'xur'], ['nuxur'], ['nuxdar']]], 
    "nuxdar": [['verbinden', 'kooperieren', 'zusammenarbeiten', 'zusammenbringen'], ['Verb'], [['nuxur', 'nuxul'], [''], ['']]], 
    "lunakur": [['Uhr'], ['Nomen'], [['luna', 'lakur'], [''], ['']]], 
    "kalur": [['Gegner', 'Feind', 'Bösewicht'], ['Nomen'], [[''], ['kal'], ['']]], 
    "duqandur": [['kommen', 'hinkommen', 'ankommen'], ['Verb'], [['dukdar', '-dān'], [''], ['duqan']]], 
    "duk": [['Bewegung'], ['Nomen'], [[''], ['dukdar', 'dukal'], ['ðulðukdar']]], 
    "nārul": [['warmes Getränk', 'Tee'], ['Nomen'], [[''], [''], ['']]], 
    "duqan": [['Ankunft', 'Ankommen', 'Erscheinen'], ['Nomen'], [['duqandur'], [''], ['']]], 
    "kunadur": [['haben', 'besitzen'], ['Verb'], [['kun'], ['kûnudar', 'rakundar'], ['']]], 
    "ðulðukdar": [['drehen', 'umdrehen', 'im Kreis bewegen'], ['Verb'], [['duk', 'dukdar', 'ðulðu'], [''], ['']]], 
    "lagruðaldur": [['lügen', 'falsches erzählen', 'falsch liegen'], ['Verb'], [['ruðal', 'lagrūdar'], [''], ['']]], 
    "kâðadur": [['kämpfen', 'auseinandersetzen', 'streiten', 'ankämpfen'], ['Verb'], [['kaðan'], [''], ['kaðar']]], 
    "kaðar": [['Kampf', 'Auseinandersetzung', 'Streit', 'Konflikt'], ['Nomen'], [['kâðadur'], [''], ['']]], 
    "qað": [['Teil', 'Stück', 'Part', 'Anteil', 'Abschnitt'], ['Nomen'], [['qa'], [''], ['qaðardur']]], 
    "qax": [['Jemand', 'Etwas'], ['Nomen'], [['qa'], [''], ['']]], 
    "ruðax": [['Niemand'], ['Nomen'], [['ruð'], [''], ['']]], 
    "rakundar": [['sich erinnern', 'erinnern', 'aufbewahren', 'konservieren', 'erhalten'], ['Verb'], [['kun'], ['kunadur'], ['']]], 
    "kudunaður": [['töten', 'ermorden', 'schlachten'], ['Verb'], [['kûnudar', 'ðuru'], [''], ['kudunað']]], 
    "nādul": [['Flüssigkeit', 'Trank'], ['Nomen'], [['nādukadur'], ['nār', 'nādur'], ['']]], 
    "nuƥral": [['gesund', 'normal', 'natürlich', 'richtig', 'fit'], ['Adjektiv'], [['nūƥ'], [''], ['ālnuƥal']]], 
    "qaƥar": [['Kern', 'Punkt', 'Mittelpunkt', 'Herz', 'Herzstück'], ['Nomen'], [['qa'], [''], ['']]], 
    "karuð": [['das große Böse', 'Übel', 'Böse', 'Untergang'], ['Nomen'], [['kal', 'ruðal'], [''], ['']]], 
    "kar": [[], [''], [[''], [''], ['']]], 
    "kalar": [['Gefahr'], ['Nomen'], [[''], ['karal'], ['']]], 
    "karal": [['gefährlich', 'bedrohlich'], ['Adjektiv'], [[''], ['kalar', 'kal'], ['']]], 
    "ƥar": [['spät'], ['Temporaladverb'], [['ƥadur'], [''], ['ƥârul']]], 
    "rak": [[], [''], [[''], [''], ['']]], 
    "nakur": [['Länge', 'Breite', 'Distanz', 'Weite'], ['Nomen'], [[''], ['nak'], ['']]], 
    "nak": [['lang', 'breit', 'weit entfernt', 'weit'], ['Adjektiv'], [[''], ['nakur'], ['']]], 
    "laqandur": [['heben', 'hochheben', 'anheben', 'tragen', 'halten'], ['Verb'], [['lag', 'qan'], [''], ['laqan']]], 
    "laqan": [['Tasche', 'Beutel', 'Sack', 'Rucksack'], ['Nomen'], [['laqandur'], [''], ['']]], 
    "ðuraƥdur": [['lang leben', 'alt werden', 'alt sein'], ['Verb'], [['ðuru', 'ðurudar'], [''], ['']]], 
    "dunaƥdur": [['beobachten', 'anschauen', 'ansehen'], ['Verb'], [['dunadur'], [''], ['']]], 
    "dar": [['sein'], ['Verb'], [[''], [''], ['āldar']]], 
    "kaxur": [['Gesellschaft', 'Volk', 'Stamm', 'Rasse', 'Rudel', 'Gemeinschaft', 'Tiergemeinschaft', 'Herde'], ['Nomen'], [['xur', 'ka'], [''], ['']]], 
    "xalan": [['rot'], ['Adjektiv'], [[''], [''], ['']]], 
    "kunād": [['Hinterteil', 'Schwanz'], ['Nomen'], [['kun', 'ād'], [''], ['']]], 
    "nāk": [['Gewässer'], ['Nomen'], [[''], ['nāxku'], ['']]], 
    "dūradur": [['stammen', 'abstammen'], ['Verb'], [['dūr'], [''], ['']]], 
    "ru": [['wenig', 'klein'], ['Adjektiv'], [[''], [''], ['rugulūr', 'lagru', 'rugundar']]], 
    "runāxku": [['See', 'Teich', 'Tümpel'], ['Nomen'], [['nāxku'], ['kanāxku'], ['']]], 
    "dūrak": [['Wenai'], ['Eigenname'], [['dūr'], [''], ['']]], 
    "nâlak": [['Ahai'], ['Eigenname'], [['nal'], [''], ['']]], 
    "nāxak": [['Wai'], ['Eigenname'], [['nāxku'], [''], ['']]], 
    "ūrnak": [[], [''], [[''], [''], ['']]], 
    "ūrandak": [['Ranai'], ['Eigenname'], [['ūrna'], [''], ['']]], 
    "quƥar": [['Kuberika'], ['Eigenname'], [[''], [''], ['']]], 
    "raqath": [["Ras'qath"], ['Eigenname'], [[''], [''], ['']]], 
    "ðâlaƥur": [['Stalbu', 'Minort'], ['Eigenname'], [[''], [''], ['']]], 
    "darað": [['Dras'], ['Eigenname'], [[''], [''], ['']]], 
    "duruð": [['Drus'], ['Eigenname'], [[''], [''], ['']]], 
    "draðna": [['Drasna'], ['Eigenname'], [[''], [''], ['']]], 
    "lagadur": [['bauen', 'erstellen', 'erschaffen', 'herstellen', 'aufbauen'], ['Verb'], [['lag'], ['ðagadur'], ['ðuralagdur']]], 
    "ðuralagdur": [['erneuern', 'ersetzen'], ['Verb'], [['ðural', 'lagadur'], [''], ['']]], 
    "dak": [['Gott', 'Gottheit'], ['Nomen'], [[''], ['dakar'], ['dâkadur']]], 
    "dakar": [['Gottesglaube', 'Glaube', 'Religion'], [''], [[''], ['dak', 'dâkadur'], ['kaðurak']]], 
    "dâkadur": [['glauben', 'an Gott glauben'], ['Verb'], [['dak'], ['dakar'], ['']]], 
    "ðulur": [['Lebenszeit', 'Leben'], ['Nomen'], [[''], ['ðuru'], ['']]], 
    "kulur": [['Gewicht'], ['Nomen'], [['kul'], [''], ['kuldar']]], 
    "kul": [['schwer', 'gewichtig'], ['Adjektiv'], [[''], [''], ['kuldar', 'kulur']]], 
    "kuldar": [['wiegen'], ['Verb'], [['kul', 'kulur'], [''], ['']]], 
    "dūrad": [['Herkunft', 'Abstammung'], ['Nomen'], [[''], [''], ['']]], 
    "rugulūr": [['Gewächs', 'kleine Pflanze', 'Kraut'], ['Nomen'], [['ru', 'guldūr'], [''], ['']]], 
    "kalaƥrad": [['Wiese', 'Grasgebiet'], ['Nomen'], [['laƥrad', 'ka'], [''], ['']]], 
    "laƥuldar": [['verursachen', 'auslösen', 'bewirken'], ['Verb'], [['lakdur', 'ƥākul'], [''], ['nâlaƥuldar']]], 
    "ƥakuldar": [['lösen', 'Ergebnis erzielen', 'vollenden', 'fertig stellen', 'beenden'], ['Verb'], [['ƥākul'], [''], ['']]], 
    "urad": [['sandig', 'pulverig', 'wie Staub'], ['Adjektiv'], [['ural'], [''], ['raduk']]], 
    "raduk": [['Pulver', 'Staub', 'Puder'], ['Nomen'], [['urad'], [''], ['']]], 
    "gulðar": [['Blüte', 'Blume'], ['Nomen'], [['guldūr'], [''], ['gulðardur']]], 
    "duqardur": [['herauskommen', 'weggehen', 'verlassen', 'gehen', 'weglaufen'], ['Verb'], [['dukdar', 'dār'], [''], ['']]], 
    "ðunuldar": [['einschlafen'], ['Verb'], [['ðuguldar', 'ðun'], [''], ['']]], 
    "nalgudar": [['bestehen aus', 'gemacht sein von/aus', 'zusammengestellt sein aus', 'sich zusammensetzen aus'], ['Verb'], [['nalgur'], [''], ['nargul']]], 
    "nargul": [['zusammengestellt', 'zusammengesetzt', 'aus verschiedenen Teilen bestehend'], ['Adjektiv'], [['nalgur', 'nalgudar'], [''], ['']]], 
    "ƥur-nalgur": [['Die vier Elemente'], ['Eigenname'], [['ƥur', 'nalgur'], [''], ['']]], 
    "lagru": [['Finger'], ['Nomen'], [['lag', 'ru'], [''], ['lagrudar']]], 
    "aðradur": [['schmecken'], ['Verb'], [['aðrak'], [''], ['']]], 
    "âkana": [['Akamah'], ['Eigenname'], [[''], [''], ['']]], 
    "dûrur": [['nachts'], ['Adjektiv'], [['dûrul', 'dur'], [''], ['']]], 
    "dâlar": [['tagsüber', 'tags'], ['Adjektiv'], [['dal'], [''], ['']]], 
    "kaðuk": [['Schlüssel', 'Öffner'], ['Nomen'], [['kaðadur', 'kað'], [''], ['kaðurak']]], 
    "kaðurak": [['Versiegeltes Schloss'], ['Eigenname'], [['kaðuk', 'dakar'], [''], ['']]], 
    "âdarul": [['Ruhe', 'Stille'], ['Nomen'], [['āl-', 'dārul'], ['âdalur'], ['']]], 
    "âdalur": [['still', 'ruhig', 'leise', 'beruhigt', 'gelassen', 'entspannt'], ['Adjektiv'], [[''], ['âdarul'], ['']]], 
    "âdarul lagdur": [['beruhigen', 'runterbringen', 'entspannen', 'jemanden entspannen', 'zur Ruhe kommen', 'jemanden zur Ruhe bringen'], ['Verb'], [[''], [''], ['']]], 
    "gudundar": [['schaffen', 'gewinnen', 'siegen'], ['Verb'], [[''], ['gudun'], ['gudul']]], 
    "gudul": [['siegreich', 'erfolgreich'], ['Adjektiv'], [['gudun', 'gudundar'], [''], ['']]], 
    "kaðandur": [['drücken', 'schieben'], ['Verb'], [['kaðan'], [''], ['']]], 
    "xul": [['Hälfte', 'halb'], ['Nomen'], [[''], [''], ['qaxul']]], 
    "qaxul": [['anderthalb'], ['Zahl'], [['qa', 'xul'], [''], ['']]], 
    "gûladun": [['Gebirge'], ['Nomen'], [['gûlad'], [''], ['']]], 
    "lâkar": [['Handwerk', 'Handwerken'], ['Nomen'], [['lakur', 'lakdur'], [''], ['lâkaxur']]], 
    "lâkaxur": [['Mensch'], ['Eigenname'], [['lâkar', 'xur'], ['lâkarux'], ['']]], 
    "kadūgul": [['Kontinent'], ['Nomen'], [['kadūr', 'gulur'], [''], ['']]], 
    "guqudāndur": [['anpassen', 'sich anpassen', 'angleichen', 'sich angleichen', 'hinwandeln', 'in etwas verwandeln'], ['Verb'], [['guqudar', '-dān'], [''], ['']]], 
    "kundar": [['aussehen', 'erscheinen'], ['Verb'], [['kun'], [''], ['kunda']]], 
    "āldar": [['tot', 'verstorben', 'verschieden', 'nicht existent'], ['Adjektiv'], [['āl-', 'dar'], [''], ['']]], 
    "ālnuƥal": [['anders', 'unterschiedlich'], ['Adjektiv'], [['nuƥral', 'āl-'], [''], ['']]], 
    "naƥāx": [['Eis'], ['Nomen'], [['nāxku', 'nâƥal'], [''], ['']]], 
    "ūrnaƥal": [['Schnee'], ['Nomen'], [['ūrna', 'nâƥal'], [''], ['']]], 
    "dūran": [['braun'], ['Adjektiv'], [['dūr'], [''], ['']]], 
    "dūd": [['Tôt'], ['Eigenname'], [[''], [''], ['']]], 
    "ƥarūð": [['Wrethh'], ['Eigenname'], [[''], [''], ['']]], 
    "daraðna": [['Drasna'], ['Eigenname'], [[''], [''], ['']]], 
    "runad": [['Runad'], ['Eigenname'], [[''], [''], ['']]], 
    "lâkarux": [['Menschensprache'], ['Eigenname'], [[''], ['lâkaxur'], ['']]], 
    "ruq": [['Zeichen', 'Symbol', 'Name'], ['Nomen'], [[''], ['rux'], ['rûqudar', 'ruqdar']]], 
    "rûqudar": [['zeichnen', 'malen', 'schreiben'], ['Verb'], [['ruq'], ['ruqdar'], ['']]], 
    "dunradur": [['finden', 'herausfinden', 'entdecken', 'aufspüren'], ['Verb'], [['dunadur', 'râdūl'], [''], ['ƥākul dunradur']]], 
    "lagakdur": [['setzen', 'stellen', 'legen', 'hinsetzen', 'hinstellen', 'hinlegen'], ['Verb'], [['lag', 'gak'], [''], ['']]], 
    "qulak": [['Ruf', 'Schrei', 'lautes Geräusch'], ['Nomen'], [['qulakdur'], [''], ['']]], 
    "na": [[], [''], [[''], [''], ['']]], 
    "ðâral": [['9. Umlauf eines Monats', 'Thartag'], ['Nomen'], [[''], [''], ['']]], 
    "gulak": [['Fläche', 'Weite'], ['Nomen'], [['gul', 'gulur'], [''], ['']]], 
    "qanak": [['Ebene', 'Level', 'Stufe'], ['Nomen'], [['qan'], ['qanar'], ['']]], 
    "rugundar": [['Baby', 'Neugeborenes', 'Kleinkind'], ['Nomen'], [['ru', 'gundar'], [''], ['']]], 
    "lagrudar": [['zeigen', 'deuten', 'aufzeigen', 'herausstellen', 'hervorheben'], ['Verb'], [['lagru'], [''], ['']]], 
    "gulðardur": [['blühen'], ['Verb'], [['gulðar'], [''], ['']]], 
    "qaðak": [['überall', 'an jedem Ort'], [''], [['qad', 'gak'], [''], ['']]], 
    "dâra": [['Drah'], ['Eigenname'], [[''], [''], ['']]], 
    "rukul": [['Mix', 'Vermischung', 'Mischung', 'Verbindung'], ['Nomen'], [[''], [''], ['rukuldar']]], 
    "rukuldar": [['mischen', 'vermischen', 'mixen', 'verbinden', 'umrühren'], ['Verb'], [['rukul'], [''], ['']]], 
    "ƥākul dunradur": [['entscheiden', 'bestimmen', 'festlegen'], ['Verb'], [['ƥākul', 'dunradur'], [''], ['']]], 
    "qaral": [['mittig', 'zentral', 'zentriert', 'ausgeglichen', 'ausbalanciert', 'austariert'], ['Adjektiv'], [['qalar'], ['qalardur'], ['qaraldur']]], 
    "qaraldur": [['ausbalancieren', 'zentrieren', 'ausgleichen', 'in die Mitte bringen', 'mittig ausrichten'], ['Verb'], [['qaral'], ['qalar', 'qalardur'], ['']]], 
    "qalardur": [['herrschen', 'regieren', 'anführen', 'leiten', 'führen'], ['Verb'], [['qalar'], ['qaral', 'qaraldur'], ['']]], 
    "ƥaluq": [['Gefühl', 'Wahrnehmung'], ['Nomen'], [['ƥaladur', 'ƥalar'], [''], ['']]], 
    "ƥaxuq": [['Gesicht'], ['Nomen'], [['ƥalar', 'ƥaladur', 'xug'], [''], ['ƥax']]], 
    "ƥax": [['vor'], ['Präposition'], [['ƥaxuq'], [''], ['ƥaqrul']]], 
    "ƥadur": [['behalten', 'aufbewahren', 'bewahren', 'konservieren'], ['Verb'], [[''], [''], ['ƥar', 'ƥarūdar']]], 
    "ƥârul": [['Abend'], ['Nomen'], [['ƥar'], [''], ['ƥârān']]], 
    "ƥarūdar": [['Essen haltbar machen', 'Essen konservieren'], ['Verb'], [['ƥadur', 'ûdar', 'ūd'], [''], ['']]], 
    "dūn": [['Ecke'], ['Nomen'], [[''], [''], ['ƥuradūn']]], 
    "ƥuradūn": [['Gebiet'], ['Nomen'], [['ƥur', 'dūn'], [''], ['xaradūn']]], 
    "xar": [['hinten'], ['Präposition'], [[''], [''], ['xaradūn']]], 
    "dārxad": [['Osten'], ['Nomen'], [['dārðaru', 'xaradūn'], [''], ['']]], 
    "ƥaxdūn": [['Süden'], ['Nomen'], [[''], [''], ['']]], 
    "dārðalun": [['Norden'], ['Nomen'], [['dārðaru', 'lûrunað'], [''], ['']]], 
    "ƥâralur": [['Westen'], ['Nomen'], [['ƥârān', 'lûrunað'], [''], ['']]], 
    "qaðardur": [['teilen', 'aufteilen', 'verteilen'], ['Verb'], [['qað'], [''], ['qaðra']]], 
    "lūn": [['schrecklich', 'abscheulich', 'beängstigend', 'schlimm'], ['Adjektiv'], [[''], [''], ['lūnad']]], 
    "nâlaƥuldar": [['Feuer machen', 'zusammen kommen', 'zu Abend essen'], ['Verb'], [['nal', 'laƥuldar'], [''], ['nâlaƥur', 'nâlaƥul']]], 
    "nâlaƥur": [['Abendessen', 'Feuermachen', 'Zusammenkommen'], ['Nomen'], [['nâlaƥuldar'], ['nâlaƥul'], ['']]], 
    "nâlaƥul": [['gemütlich', 'heimisch', 'angenehm'], ['Adjektiv'], [['nâlaƥuldar'], ['nâlaƥur'], ['']]], 
    "ƥaqrul": [['1. Hälfte des Mondlaufs', '1. Monatshälfte'], ['Nomen'], [['ƥax', '-krul'], ['ādqul'], ['']]], 
    "ādqul": [['2. Hälfte des Mondlaufs', '2. Monatshälfte'], ['Nomen'], [['ād', '-krul'], ['ƥaqrul'], ['']]], 
    "ural-kadūr": [['Vadon'], ['Nomen'], [['ural', 'kadūr'], [''], ['']]], 
    }
    
    
const gram = {
    "xur": ['xurað', 'xuran', 'xurda', 'gu-xur', 'xur-gūn', 'xuran-gūn'], 
    "rux": ['ruxað', 'ruxan', 'ruxda', 'ga-rux', 'rux-gān', 'ruxan-gān'], 
    "gul": [], 
    "a-": ['ā-', 'āl-', 'ūl-', 'ra-', 'ār-'], 
    "dal": ['dalað', 'dalan', 'dalda', 'ga-dal', 'dal-gān', 'dalan-gān'], 
    "gal": ['galað', 'galan', 'galda', 'ga-gal', 'gal-gān', 'galan-gān'], 
    "lâkadur": ["lâka'ul", 'lâkad', 'lâkadun', 'lâkada', 'lâkadu', 'lâkadad', 'lâkadā', 'lâkadū', 'lâkadud'], 
    "dûqur": ['dûqurað', 'dûquran', 'dûqurda', 'gu-dûqur', 'dûqur-gūn', 'dûquran-gūn'], 
    "duna": ['dunaduð', 'dunadun', 'dunada', 'gu-duna', 'duna-gūn', 'dunadun-gūn'], 
    "nādukal": ['nādukaluð', 'nādukalun', 'nādukalda', 'ga-nādukal', 'nādukal-gān', 'nādukalun-gān'], 
    "dūr": ['dūrað', 'dūran', 'dūrda', 'a-dūr', 'dūr-dān', 'dūran-dān'], 
    "ūrna": ['ūrnaduð', 'ūrnadun', 'ūrnada', 'ga-ūrna', 'ūrna-gān', 'ūrnadun-gān'], 
    "ūrnâqu": ['ūrnâqudað', 'ūrnâqudan', 'ūrnâquda', 'a-ūrnâqu', 'ūrnâqu-dān', 'ūrnâqudan-dān'], 
    "qna": ['qnadað', 'qnadan', 'qnada', 'a-qna', 'qna-dān', 'qnadan-dān'], 
    "qun": ['qunað', 'qunan', 'qunda', 'a-qun', 'qun-dān', 'qunan-dān'], 
    "kral": ['kralað', 'kralan', 'kralda', 'ga-kral', 'kral-gān', 'kralan-gān'], 
    "gunda": [], 
    "dukdar": ['dukal', 'dukud', 'dukudan', 'duka', 'duku', 'dukad', 'duqa', 'duqu', 'dukud'], 
    "nâqudar": ["nâqu'al", 'nâqud', 'nâqudan', 'nâquda', 'nâqudu', 'nâqudad', 'nâqudā', 'nâqudū', 'nâqudud'], 
    "guqudar": ["guqu'al", 'guqud', 'guqudan', 'guquda', 'guqudu', 'guqudad', 'guqudā', 'guqudū', 'guqudud'], 
    "axa": [], 
    "dunaxur": ['dunaxurað', 'dunaxuran', 'dunaxurda', 'gu-dunaxur', 'dunaxur-gūn', 'dunaxuran-gūn'], 
    "dunadur": ["duna'ul", 'dunad', 'dunadun', 'dunada', 'dunadu', 'dunadad', 'dunadā', 'dunadū', 'dunadud'], 
    "nāxur": ['nāxurað', 'nāxuran', 'nāxurda', 'gu-nāxur', 'nāxur-gūn', 'nāxuran-gūn'], 
    "dūxur": ['dūxurað', 'dūxuran', 'dūxurda', 'gu-dūxur', 'dūxur-gūn', 'dūxuran-gūn'], 
    "lukdar": ['lukal', 'lukud', 'lukudan', 'luka', 'luku', 'lukad', 'luqa', 'luqu', 'lukud'], 
    "lûqur": ['lûqurað', 'lûquran', 'lûqurda', 'gu-lûqur', 'lûqur-gūn', 'lûquran-gūn'], 
    "kûlu": ['kûludað', 'kûludan', 'kûluda', 'ga-kûlu', 'kûlu-gān', 'kûludan-gān'], 
    "ruqdar": ['ruqal', 'ruqud', 'ruqudan', 'ruqa', 'ruqu', 'ruqad', 'ruqā', 'ruqū', 'ruqud'], 
    "ruk": [], 
    "qan": [], 
    "dārul": ['dārulað', 'dārulan', 'dārulda', 'ga-dārul', 'dārul-gān', 'dārulan-gān'], 
    "âkadur": ["âka'ul", 'âkad', 'âkadun', 'âkada', 'âkadu', 'âkadad', 'âkadā', 'âkadū', 'âkadud'], 
    "ūd": ['ūdað', 'ūdan', 'ûda', 'a-ūd', 'ūd-dān', 'ūdan-dān'], 
    "qural": ['quraluð', 'quralun', 'quralda', 'ga-qural', 'qural-gān', 'quralun-gān'], 
    "lūnad": ['lūnaduð', 'lūnadun', 'lūnâda', 'a-lūnad', 'lūnad-dān', 'lūnadun-dān'], 
    "luxdar": ['luxal', 'luxud', 'luxudan', 'luxa', 'luxu', 'luxad', 'luxā', 'luxū', 'luxud'], 
    "kûdudar": ["kûdu'al", 'kûdud', 'kûdudan', 'kûduda', 'kûdudu', 'kûdudad', 'kûdudā', 'kûdudū', 'kûdudud'], 
    "nūk": ['nūkað', 'nūkan', 'nūkda', 'ga-nūk', 'nūk-gān', 'nūkan-gān'], 
    "ralxū": ['ralxūdað', 'ralxūdan', 'ralxūda', 'a-ralxū', 'ralxū-dān', 'ralxūdan-dān'], 
    "lûrad": ['lûraduð', 'lûradun', 'lûrâda', 'a-lûrad', 'lûrad-dān', 'lûradun-dān'], 
    "kûnudar": ["kûnu'al", 'kûnud', 'kûnudan', 'kûnuda', 'kûnudu', 'kûnudad', 'kûnudā', 'kûnudū', 'kûnudud'], 
    "kûnadur": ["kûna'ul", 'kûnad', 'kûnadun', 'kûnada', 'kûnadu', 'kûnadad', 'kûnadā', 'kûnadū', 'kûnadud'], 
    "dûrul": ['dûrulað', 'dûrulan', 'dûrulda', 'ga-dûrul', 'dûrul-gān', 'dûrulan-gān'], 
    "a-dal": [], 
    "a-gal": [], 
    "a-kral": [], 
    "ûdar": ['ud', 'ûdan', 'ûda', 'ûdu', 'ûdad', 'udā', 'udū', 'ûdud'], 
    "luna": ['lunaduð', 'lunadun', 'lunada', 'ga-luna', 'luna-gān', 'lunadun-gān'], 
    "lûru": ['lûrudað', 'lûrudan', 'lûruda', 'ga-lûru', 'lûru-gān', 'lûrudan-gān'], 
    "âdar": ['âdaruð', 'âdarun', 'âdarda', 'ga-âdar', 'âdar-gān', 'âdarun-gān'], 
    "nûkudar": ["nûku'al", 'nûkud', 'nûkudan', 'nûkuda', 'nûkudu', 'nûkudad', 'nûkudā', 'nûkudū', 'nûkudud'], 
    "u-": [], 
    "āl-": [], 
    "ā-": [], 
    "nādur": ["nā'ul", 'nād', 'nādun', 'nāda', 'nādu', 'nādad', 'nadā', 'nadū', 'nādud'], 
    "dûrudar": ["dûru'al", 'dûrud', 'dûrudan', 'dûruda', 'dûrudu', 'dûrudad', 'dûrudā', 'dûrudū', 'dûrudud'], 
    "dul": ['dulað', 'dulan', 'dulda', 'a-dul', 'dul-dān', 'dulan-dān'], 
    "xuq": ['xuqað', 'xuqan', 'xuqda', 'gu-xuq', 'xuq-gūn', 'xuqan-gūn'], 
    "kaðan": ['kaðanuð', 'kaðanun', 'kaðanda', 'a-kaðan', 'kaðan-dān', 'kaðanun-dān'], 
    "ûlud": ['ûludað', 'ûludan', 'ûlûda', 'ga-ûlud', 'ûlud-gān', 'ûludan-gān'], 
    "guldur": ['gulal', 'gulud', 'guludan', 'gula', 'gulu', 'gulad', 'gulā', 'gulū', 'gulud'], 
    "guldūr": ['guldūrað', 'guldūran', 'guldūrda', 'ga-guldūr', 'guldūr-gān', 'guldūran-gān'], 
    "gûlad": ['gûladuð', 'gûladun', 'gûlâda', 'ga-gûlad', 'gûlad-gān', 'gûladun-gān'], 
    "rûqur": ['rûqurað', 'rûquran', 'rûqurda', 'a-rûqur', 'rûqur-dān', 'rûquran-dān'], 
    "larnaqa": [], 
    "nûluk": ['nûlukað', 'nûlukan', 'nûlukda', 'a-nûluk', 'nûluk-dān', 'nûlukan-dān'], 
    "-ūn": [], 
    "ūl-": [], 
    "ðāndrug": ['ðāndrugað', 'ðāndrugan', 'ðāndrugda', 'a-ðāndrug', 'ðāndrug-dān', 'ðāndrugan-dān'], 
    "a-dārulūn": ['a-dārulūnað', 'a-dārulūnan', 'a-dārulūnda', 'ga-a-dārulūn', 'a-dārulūn-gān', 'a-dārulūnan-gān'], 
    "xaradūn": ['xaradūnað', 'xaradūnan', 'xaradūnda', 'a-xaradūn', 'xaradūn-dān', 'xaradūnan-dān'], 
    "adûranð": [], 
    "lûrunað": ['lûrunaðuð', 'lûrunaðun', 'lûrunaðda', 'a-lûrunað', 'lûrunað-dān', 'lûrunaðun-dān'], 
    "ƥârān": ['ƥârānuð', 'ƥârānun', 'ƥârānda', 'a-ƥârān', 'ƥârān-dān', 'ƥârānun-dān'], 
    "dārðaru": ['dārðarudað', 'dārðarudan', 'dārðaruda', 'a-dārðaru', 'dārðaru-dān', 'dārðarudan-dān'], 
    "uldūr": ['uldūrað', 'uldūran', 'uldūrda', 'a-uldūr', 'uldūr-dān', 'uldūran-dān'], 
    "nurguð": ['nurguðað', 'nurguðan', 'nurguðda', 'ga-nurguð', 'nurguð-gān', 'nurguðan-gān'], 
    "ðagar": ['ðagaruð', 'ðagarun', 'ðagarda', 'ga-ðagar', 'ðagar-gān', 'ðagarun-gān'], 
    "gulrað": ['gulraðuð', 'gulraðun', 'gulraðda', 'a-gulrað', 'gulrað-dān', 'gulraðun-dān'], 
    "ðâladur": ["ðâla'ul", 'ðâlad', 'ðâladun', 'ðâlada', 'ðâladu', 'ðâladad', 'ðâladā', 'ðâladū', 'ðâladud'], 
    "ðulðu": [], 
    "ðulður": ['ðulðurað', 'ðulðuran', 'ðulðurda', 'gu-ðulður', 'ðulður-gūn', 'ðulðuran-gūn'], 
    "ðuru": ['ðurudað', 'ðurudan', 'ðuruda', 'ga-ðuru', 'ðuru-gān', 'ðurudan-gān'], 
    "ðurudar": ["ðuru'al", 'ðurud', 'ðurudan', 'ðuruda', 'ðurudu', 'ðurudad', 'ðurudā', 'ðurudū', 'ðurudud'], 
    "ðulðudar": ["ðulðu'al", 'ðulðud', 'ðulðudan', 'ðulðuda', 'ðulðudu', 'ðulðudad', 'ðulðudā', 'ðulðudū', 'ðulðudud'], 
    "gûluð": ['gûluðað', 'gûluðan', 'gûluðda', 'a-gûluð', 'gûluð-dān', 'gûluðan-dān'], 
    "akdūl": [], 
    "ðadudar": ["ðadu'al", 'ðadud', 'ðadudan', 'ðaduda', 'ðadudu', 'ðadudad', 'ðadudā', 'ðadudū', 'ðadudud'], 
    "dûluruð": ['dûluruðað', 'dûluruðan', 'dûluruðda', 'a-dûluruð', 'dûluruð-dān', 'dûluruðan-dān'], 
    "kuna": ['kunaduð', 'kunadun', 'kunada', 'gu-kuna', 'kuna-gūn', 'kunadun-gūn'], 
    "-(û)ruð": [], 
    "gâranul": [], 
    "ūlrad": [], 
    "râdūl": ['râdūlað', 'râdūlan', 'râdūlda', 'a-râdūl', 'râdūl-dān', 'râdūlan-dān'], 
    "gâladur": ["gâla'ul", 'gâlad', 'gâladun', 'gâlada', 'gâladu', 'gâladad', 'gâladā', 'gâladū', 'gâladud'], 
    "galadur": ["gala'ul", 'galad', 'galadun', 'galada', 'galadu', 'galadad', 'galadā', 'galadū', 'galadud'], 
    "galan": ['galanuð', 'galanun', 'galanda', 'a-galan', 'galan-dān', 'galanun-dān'], 
    "nalgur": ['nalgurað', 'nalguran', 'nalgurda', 'a-nalgur', 'nalgur-dān', 'nalguran-dān'], 
    "nadūl": [], 
    "-dān": [], 
    "ūrnadur": ["ūrna'ul", 'ūrnad', 'ūrnadun', 'ūrnada', 'ūrnadu', 'ūrnadad', 'ūrnadā', 'ūrnadū', 'ūrnadud'], 
    "rukdān": [], 
    "qandān": [], 
    "ðuruðu'a": ["ðuruðu'aduð", "ðuruðu'adun", "ðuruðu'ada", "a-ðuruðu'a", "ðuruðu'a-dān", "ðuruðu'adun-dān"], 
    "akdūldān": [], 
    "ūlradān": [], 
    "xug": ['xugað', 'xugan', 'xugda', 'a-xug', 'xug-dān', 'xugan-dān'], 
    "durān": [], 
    "luga": ['lugaduð', 'lugadun', 'lugada', 'gu-luga', 'luga-gūn', 'lugadun-gūn'], 
    "kā": [], 
    "la": [], 
    "rā": [], 
    "kān": [], 
    "lan": [], 
    "rān": [], 
    "rukdāndur": ['rukdānul', 'rukdānad', 'rukdānudun', 'rukdāna', 'rukdānu', 'rukdānad', 'rukdanā', 'rukdanū', 'rukdānud'], 
    "qa": [], 
    "ruð": ['ruðað', 'ruðan', 'ruðda', 'ga-ruð', 'ruð-gān', 'ruðan-gān'], 
    "ðagadur": ["ðaga'ul", 'ðagad', 'ðagadun', 'ðagada', 'ðagadu', 'ðagadad', 'ðagadā', 'ðagadū', 'ðagadud'], 
    "rukdār": [], 
    "rukdar": ['rukal', 'rukud', 'rukudan', 'ruka', 'ruku', 'rukad', 'ruqa', 'ruqu', 'rukud'], 
    "ðuxur": ['ðuxurað', 'ðuxuran', 'ðuxurda', 'gu-ðuxur', 'ðuxur-gūn', 'ðuxuran-gūn'], 
    "rûkundar": ['rûkunal', 'rûkunud', 'rûkunadan', 'rûkuna', 'rûkunu', 'rûkunad', 'rûkunā', 'rûkunū', 'rûkunud'], 
    "nāxku": ['nāxkudað', 'nāxkudan', 'nāxkuda', 'ga-nāxku', 'nāxku-gān', 'nāxkudan-gān'], 
    "gād": [], 
    "nûlad": ['nûladuð', 'nûladun', 'nûlâda', 'a-nûlad', 'nûlad-dān', 'nûladun-dān'], 
    "nal": ['nalað', 'nalan', 'nalda', 'ga-nal', 'nal-gān', 'nalan-gān'], 
    "dār": [], 
    "lux": [], 
    "gurul": ['gurulað', 'gurulan', 'gurulda', 'ga-gurul', 'gurul-gān', 'gurulan-gān'], 
    "axaxur": ['axaxurað', 'axaxuran', 'axaxurda', 'gu-axaxur', 'axaxur-gūn', 'axaxuran-gūn'], 
    "ūrnaxur": ['ūrnaxurað', 'ūrnaxuran', 'ūrnaxurda', 'gu-ūrnaxur', 'ūrnaxur-gūn', 'ūrnaxuran-gūn'], 
    "dunarux": ['dunaruxað', 'dunaruxan', 'dunaruxda', 'ga-dunarux', 'dunarux-gān', 'dunaruxan-gān'], 
    "dûrux": ['dûruxað', 'dûruxan', 'dûruxda', 'ga-dûrux', 'dûrux-gān', 'dûruxan-gān'], 
    "nārux": ['nāruxað', 'nāruxan', 'nāruxda', 'ga-nārux', 'nārux-gān', 'nāruxan-gān'], 
    "lugrux": ['lugruxað', 'lugruxan', 'lugruxda', 'ga-lugrux', 'lugrux-gān', 'lugruxan-gān'], 
    "dugrux": ['dugruxað', 'dugruxan', 'dugruxda', 'ga-dugrux', 'dugrux-gān', 'dugruxan-gān'], 
    "ūrnarux": ['ūrnaruxað', 'ūrnaruxan', 'ūrnaruxda', 'ga-ūrnarux', 'ūrnarux-gān', 'ūrnaruxan-gān'], 
    "axarux": ['axaruxað', 'axaruxan', 'axaruxda', 'ga-axarux', 'axarux-gān', 'axaruxan-gān'], 
    "krūl": ['krūlað', 'krūlan', 'krūlda', 'a-krūl', 'krūl-dān', 'krūlan-dān'], 
    "qârad": ['qâraduð', 'qâradun', 'qârâda', 'a-qârad', 'qârad-dān', 'qâradun-dān'], 
    "gul xad": ['gul xaduð', 'gul xadun', 'gul xâda', 'a-gul xad', 'gul xad-dān', 'gul xadun-dān'], 
    "drâqul": ['drâqulað', 'drâqulan', 'drâqulda', 'a-drâqul', 'drâqul-dān', 'drâqulan-dān'], 
    "gul qūd": ['gul qūdað', 'gul qūdan', 'gul qûda', 'a-gul qūd', 'gul qūd-dān', 'gul qūdan-dān'], 
    "gûluk": ['gûlukað', 'gûlukan', 'gûlukda', 'a-gûluk', 'gûluk-dān', 'gûlukan-dān'], 
    "gârak": ['gârakuð', 'gârakun', 'gârakda', 'a-gârak', 'gârak-dān', 'gârakun-dān'], 
    "nâkadur": ['nâkadurað', 'nâkaduran', 'nâkadurda', 'a-nâkadur', 'nâkadur-dān', 'nâkaduran-dān'], 
    "guldūn": ['guldūnað', 'guldūnan', 'guldūnda', 'a-guldūn', 'guldūn-dān', 'guldūnan-dān'], 
    "dûnad": ['dûnaduð', 'dûnadun', 'dûnâda', 'a-dûnad', 'dûnad-dān', 'dûnadun-dān'], 
    "xa'ād": ["xa'āduð", "xa'ādun", "xa'âda", "a-xa'ād", "xa'ād-dān", "xa'ādun-dān"], 
    "gul gunud": ['gul gunudað', 'gul gunudan', 'gul gunûda', 'a-gul gunud', 'gul gunud-dān', 'gul gunudan-dān'], 
    "narūd": ['narūdað', 'narūdan', 'narûda', 'a-narūd', 'narūd-dān', 'narūdan-dān'], 
    "nadul": ['nadulað', 'nadulan', 'nadulda', 'a-nadul', 'nadul-dān', 'nadulan-dān'], 
    "qun xaqud": ['qun xaqudað', 'qun xaqudan', 'qun xaqûda', 'a-qun xaqud', 'qun xaqud-dān', 'qun xaqudan-dān'], 
    "dan": [], 
    "run": ['runað', 'runan', 'runda', 'gu-run', 'run-gūn', 'runan-gūn'], 
    "runal": ['runaluð', 'runalun', 'runalda', 'gu-runal', 'runal-gūn', 'runalun-gūn'], 
    "larun": [], 
    "aral": [], 
    "lāg": [], 
    "qalar": ['qalaruð', 'qalarun', 'qalarda', 'gu-qalar', 'qalar-gūn', 'qalarun-gūn'], 
    "qaðra": ['qaðraduð', 'qaðradun', 'qaðrada', 'a-qaðra', 'qaðra-dān', 'qaðradun-dān'], 
    "ur-": [], 
    "ra-": [], 
    "ār-": [], 
    "ga-": ['uga-', 'gāl-', 'gūl-', 'gar-', 'gār-'], 
    "uga-": [], 
    "gāl-": [], 
    "gūl-": [], 
    "gar-": [], 
    "gār-": [], 
    "gu-": ['ugu-', 'gul-', 'ugul-', 'gur-', 'āgur-'], 
    "ugu-": [], 
    "gul-": [], 
    "ugul-": [], 
    "gur-": [], 
    "āgur-": [], 
    "ðugul": ['ðugulað', 'ðugulan', 'ðugulda', 'ga-ðugul', 'ðugul-gān', 'ðugulan-gān'], 
    "ðuguldar": ['ðugulal', 'ðugulud', 'ðuguladan', 'ðugula', 'ðugulu', 'ðugulad', 'ðugulā', 'ðugulū', 'ðugulud'], 
    "qalar-krul": ['qalar-krulað', 'qalar-krulan', 'qalar-krulda', 'a-qalar-krul', 'qalar-krul-dān', 'qalar-krulan-dān'], 
    "-krul": [], 
    "lag": ['lagað', 'lagan', 'lagda', 'gu-lag', 'lag-gūn', 'lagan-gūn'], 
    "lagdur": ['lagul', 'lagad', 'lagadun', 'laga', 'lagu', 'lagad', 'lagā', 'lagū', 'lagud'], 
    "kun": ['kunað', 'kunan', 'kunda', 'gu-kun', 'kun-gūn', 'kunan-gūn'], 
    "aðrak": ['aðrakuð', 'aðrakun', 'aðrakda', 'gu-aðrak', 'aðrak-gūn', 'aðrakun-gūn'], 
    "ƥarnadul": [], 
    "ƥarla": [], 
    "qalur": ['qalurað', 'qaluran', 'qalurda', 'a-qalur', 'qalur-dān', 'qaluran-dān'], 
    "dukal": ['dukaluð', 'dukalun', 'dukalda', 'a-dukal', 'dukal-dān', 'dukalun-dān'], 
    "ƥul": [], 
    "ƥāður": [], 
    "rundar": ['runal', 'runud', 'runudan', 'runa', 'runu', 'runad', 'runā', 'runū', 'runud'], 
    "gal-krul": ['gal-krulað', 'gal-krulan', 'gal-krulda', 'a-gal-krul', 'gal-krul-dān', 'gal-krulan-dān'], 
    "lûru-krul": ['lûru-krulað', 'lûru-krulan', 'lûru-krulda', 'a-lûru-krul', 'lûru-krul-dān', 'lûru-krulan-dān'], 
    "guður": ['guðurað', 'guðuran', 'guðurda', 'ga-guður', 'guður-gān', 'guðuran-gān'], 
    "lak": ['lakað', 'lakan', 'lakda', 'gu-lak', 'lak-gūn', 'lakan-gūn'], 
    "ƥalar": ['ƥalaruð', 'ƥalarun', 'ƥalarda', 'gu-ƥalar', 'ƥalar-gūn', 'ƥalarun-gūn'], 
    "ƥaladur": ["ƥala'ul", 'ƥalad', 'ƥaladun', 'ƥalada', 'ƥaladu', 'ƥaladad', 'ƥaladā', 'ƥaladū', 'ƥaladud'], 
    "nu": [], 
    "lar": [], 
    "ƥur": [], 
    "dāð": [], 
    "dun": [], 
    "xan": [], 
    "gur": [], 
    "ðan": [], 
    "nādukdar": ['nādukal', 'nādukud', 'nādukadan', 'nāduka', 'nāduku', 'nādukad', 'nāduqa', 'nāduqu', 'nādukud'], 
    "ûrukdar": ['ûrukal', 'ûrukud', 'ûrukadan', 'ûruka', 'ûruku', 'ûrukad', 'ûruqa', 'ûruqu', 'ûrukud'], 
    "ālun": ['ālunað', 'ālunan', 'ālunda', 'ga-ālun', 'ālun-gān', 'ālunan-gān'], 
    "ruqalun": ['ruqalunað', 'ruqalunan', 'ruqalunda', 'a-ruqalun', 'ruqalun-dān', 'ruqalunan-dān'], 
    "laquk": ['laqukað', 'laqukan', 'laqukda', 'gu-laquk', 'laquk-gūn', 'laqukan-gūn'], 
    "guqu'al": ["guqu'aluð", "guqu'alun", "guqu'alda", "gu-guqu'al", "guqu'al-gūn", "guqu'alun-gūn"], 
    "qad": ['qadað', 'qadan', 'qâda', 'a-qad', 'qad-dān', 'qadan-dān'], 
    "qaður": ['qaðurað', 'qaðuran', 'qaðurda', 'ga-qaður', 'qaður-gān', 'qaðuran-gān'], 
    "akal": [], 
    "akar": ['akaruð', 'akarun', 'akarda', 'ga-akar', 'akar-gān', 'akarun-gān'], 
    "qanar": ['qanaruð', 'qanarun', 'qanarda', 'a-qanar', 'qanar-dān', 'qanarun-dān'], 
    "gulur": ['gulurað', 'guluran', 'gulurda', 'a-gulur', 'gulur-dān', 'guluran-dān'], 
    "rûkur": ['rûkurað', 'rûkuran', 'rûkurda', 'a-rûkur', 'rûkur-dān', 'rûkuran-dān'], 
    "nuqal": [], 
    "nāl": [], 
    "kûdur": ['kûdurað', 'kûduran', 'kûdurda', 'a-kûdur', 'kûdur-dān', 'kûduran-dān'], 
    "nār": ['nārað', 'nāran', 'nārda', 'a-nār', 'nār-dān', 'nāran-dān'], 
    "nādukadur": ["nāduka'ul", 'nādukad', 'nādukudun', 'nādukada', 'nādukadu', 'nādukadad', 'nādukadā', 'nādukadū', 'nādukadud'], 
    "ānul": [], 
    "ƥal": [], 
    "âxadur": ["âxa'ul", 'âxad', 'âxadun', 'âxada', 'âxadu', 'âxadad', 'âxadā', 'âxadū', 'âxadud'], 
    "ƥulur": ['ƥulurað', 'ƥuluran', 'ƥulurda', 'gu-ƥulur', 'ƥulur-gūn', 'ƥuluran-gūn'], 
    "laran": [], 
    "nākrul": ['nākrulað', 'nākrulan', 'nākrulda', 'a-nākrul', 'nākrul-dān', 'nākrulan-dān'], 
    "nādal": ['nādaluð', 'nādalun', 'nādalda', 'a-nādal', 'nādal-dān', 'nādalun-dān'], 
    "nulâdal": ['nulâdaluð', 'nulâdalun', 'nulâdalda', 'a-nulâdal', 'nulâdal-dān', 'nulâdalun-dān'], 
    "gulâdal": ['gulâdaluð', 'gulâdalun', 'gulâdalda', 'a-gulâdal', 'gulâdal-dān', 'gulâdalun-dān'], 
    "nûlukdal": ['nûlukdaluð', 'nûlukdalun', 'nûlukdalda', 'a-nûlukdal', 'nûlukdal-dān', 'nûlukdalun-dān'], 
    "âdal": ['âdaluð', 'âdalun', 'âdalda', 'a-âdal', 'âdal-dān', 'âdalun-dān'], 
    "naldal": ['naldaluð', 'naldalun', 'naldalda', 'a-naldal', 'naldal-dān', 'naldalun-dān'], 
    "kundal": ['kundaluð', 'kundalun', 'kundalda', 'a-kundal', 'kundal-dān', 'kundalun-dān'], 
    "ðurudal": ['ðurudaluð', 'ðurudalun', 'ðurudalda', 'a-ðurudal', 'ðurudal-dān', 'ðurudalun-dān'], 
    "dûral": ['dûraluð', 'dûralun', 'dûralda', 'a-dûral', 'dûral-dān', 'dûralun-dān'], 
    "ðuxural": ['ðuxuraluð', 'ðuxuralun', 'ðuxuralda', 'a-ðuxural', 'ðuxural-dān', 'ðuxuralun-dān'], 
    "guldûral": ['guldûraluð', 'guldûralun', 'guldûralda', 'a-guldûral', 'guldûral-dān', 'guldûralun-dān'], 
    "ūrnadal": ['ūrnadaluð', 'ūrnadalun', 'ūrnadalda', 'a-ūrnadal', 'ūrnadal-dān', 'ūrnadalun-dān'], 
    "lûrudal": ['lûrudaluð', 'lûrudalun', 'lûrudalda', 'a-lûrudal', 'lûrudal-dān', 'lûrudalun-dān'], 
    "gâdal": ['gâdaluð', 'gâdalun', 'gâdalda', 'a-gâdal', 'gâdal-dān', 'gâdalun-dān'], 
    "âkadal": ['âkadaluð', 'âkadalun', 'âkadalda', 'a-âkadal', 'âkadal-dān', 'âkadalun-dān'], 
    "guðudal": ['guðudaluð', 'guðudalun', 'guðudalda', 'a-guðudal', 'guðudal-dān', 'guðudalun-dān'], 
    "galuq": ['galuqað', 'galuqan', 'galuqda', 'ga-galuq', 'galuq-gān', 'galuqan-gān'], 
    "galar": ['galaruð', 'galarun', 'galarda', 'ga-galar', 'galar-gān', 'galarun-gān'], 
    "ðagar-dan": ['ðagar-danuð', 'ðagar-danun', 'ðagar-danda', 'ga-ðagar-dan', 'ðagar-dan-gān', 'ðagar-danun-gān'], 
    "uruk": ['urukað', 'urukan', 'urukda', 'ga-uruk', 'uruk-gān', 'urukan-gān'], 
    "ðuraxdur": ['ðuraxul', 'ðuraxad', 'ðuraxudun', 'ðuraxa', 'ðuraxu', 'ðuraxad', 'ðuraxā', 'ðuraxū', 'ðuraxud'], 
    "qaðurdar": ['qaðural', 'qaðurud', 'qaðuradan', 'qaðura', 'qaðuru', 'qaðurad', 'qaðurā', 'qaðurū', 'qaðurud'], 
    "ƥuxur": ['ƥuxurað', 'ƥuxuran', 'ƥuxurda', 'ga-ƥuxur', 'ƥuxur-gān', 'ƥuxuran-gān'], 
    "raƥ": [], 
    "kuðul": [], 
    "rūl": ['rūlað', 'rūlan', 'rūlda', 'ga-rūl', 'rūl-gān', 'rūlan-gān'], 
    "ƥākul": ['ƥākulað', 'ƥākulan', 'ƥākulda', 'a-ƥākul', 'ƥākul-dān', 'ƥākulan-dān'], 
    "kal": [], 
    "qur": ['qurað', 'quran', 'qurda', 'a-qur', 'qur-dān', 'quran-dān'], 
    "quxal": ['quxaluð', 'quxalun', 'quxalda', 'a-quxal', 'quxal-dān', 'quxalun-dān'], 
    "laƥrad": ['laƥraduð', 'laƥradun', 'laƥrâda', 'ga-laƥrad', 'laƥrad-gān', 'laƥradun-gān'], 
    "dārulaƥ": ['dārulaƥuð', 'dārulaƥun', 'dārulaƥda', 'ga-dārulaƥ', 'dārulaƥ-gān', 'dārulaƥun-gān'], 
    "kuður": ['kuðurað', 'kuðuran', 'kuðurda', 'a-kuður', 'kuður-dān', 'kuðuran-dān'], 
    "dārulan": ['dārulanuð', 'dārulanun', 'dārulanda', 'ga-dārulan', 'dārulan-gān', 'dārulanun-gān'], 
    "ural": ['uraluð', 'uralun', 'uralda', 'a-ural', 'ural-dān', 'uralun-dān'], 
    "ūral": [], 
    "kadūr": ['kadūrað', 'kadūran', 'kadūrda', 'a-kadūr', 'kadūr-dān', 'kadūran-dān'], 
    "kaður": [], 
    "dûqandur": ['dûqanul', 'dûqanad', 'dûqanudun', 'dûqana', 'dûqanu', 'dûqanad', 'dûqanā', 'dûqanū', 'dûqanud'], 
    "dûrukdar": ['dûrukal', 'dûrukud', 'dûrukadan', 'dûruka', 'dûruku', 'dûrukad', 'dûruqa', 'dûruqu', 'dûrukud'], 
    "kaxug": ['kaxugað', 'kaxugan', 'kaxugda', 'a-kaxug', 'kaxug-dān', 'kaxugan-dān'], 
    "ka": [], 
    "kunrūl": ['kunrūlað', 'kunrūlan', 'kunrūlda', 'a-kunrūl', 'kunrūl-dān', 'kunrūlan-dān'], 
    "kanal": ['kanaluð', 'kanalun', 'kanalda', 'ga-kanal', 'kanal-gān', 'kanalun-gān'], 
    "naldur": ['nalul', 'nalad', 'naladun', 'nala', 'nalu', 'nalad', 'nalā', 'nalū', 'nalud'], 
    "luqak": [], 
    "guluð": ['guluðað', 'guluðan', 'guluðda', 'ga-guluð', 'guluð-gān', 'guluðan-gān'], 
    "kagalan": ['kagalanuð', 'kagalanun', 'kagalanda', 'a-kagalan', 'kagalan-dān', 'kagalanun-dān'], 
    "qâladul": ['qâladulað', 'qâladulan', 'qâladulda', 'a-qâladul', 'qâladul-dān', 'qâladulan-dān'], 
    "ður": ['ðurað', 'ðuran', 'ðurda', 'a-ður', 'ður-dān', 'ðuran-dān'], 
    "ƥarquð": [], 
    "rālun": [], 
    "ƥaxur": ['ƥaxurað', 'ƥaxuran', 'ƥaxurda', 'a-ƥaxur', 'ƥaxur-dān', 'ƥaxuran-dān'], 
    "ƥaxul": [], 
    "ðurax": ['ðuraxuð', 'ðuraxun', 'ðuraxda', 'ga-ðurax', 'ðurax-gān', 'ðuraxun-gān'], 
    "dūl": [], 
    "rūldar": ['rūlal', 'rūlud', 'rūludan', 'rūla', 'rūlu', 'rūlad', 'rulā', 'rulū', 'rūlud'], 
    "lagrūdar": ["lagrū'al", 'lagrūd', 'lagrūdan', 'lagrūda', 'lagrūdu', 'lagrūdad', 'lagrudā', 'lagrudū', 'lagrūdud'], 
    "ðagudar": ["ðagu'al", 'ðagud', 'ðagudan', 'ðaguda', 'ðagudu', 'ðagudad', 'ðagudā', 'ðagudū', 'ðagudud'], 
    "ka'uldūr": ["ka'uldūrað", "ka'uldūran", "ka'uldūrda", "a-ka'uldūr", "ka'uldūr-dān", "ka'uldūran-dān"], 
    "kadur": ["ka'ul", 'kad', 'kadun', 'kada', 'kadu', 'kadad', 'kadā', 'kadū', 'kadud'], 
    "ƥûlaqdar": ['ƥûlaqul', 'ƥûlaqad', 'ƥûlaqudun', 'ƥûlaqa', 'ƥûlaqu', 'ƥûlaqad', 'ƥûlaqā', 'ƥûlaqū', 'ƥûlaqud'], 
    "lūd": [], 
    "qadur": ['qadurað', 'qaduran', 'qadurda', 'a-qadur', 'qadur-dān', 'qaduran-dān'], 
    "ðugul-gul": ['ðugul-gulað', 'ðugul-gulan', 'ðugul-gulda', 'ga-ðugul-gul', 'ðugul-gul-gān', 'ðugul-gulan-gān'], 
    "kalūnad": ['kalūnaduð', 'kalūnadun', 'kalūnâda', 'a-kalūnad', 'kalūnad-dān', 'kalūnadun-dān'], 
    "ƥûlaq": ['ƥûlaquð', 'ƥûlaqun', 'ƥûlaqda', 'a-ƥûlaq', 'ƥûlaq-dān', 'ƥûlaqun-dān'], 
    "gâla": ['gâladuð', 'gâladun', 'gâlada', 'a-gâla', 'gâla-dān', 'gâladun-dān'], 
    "ragul": [], 
    "ral": [], 
    "lax": [], 
    "rūqul": [], 
    "nûqur": [], 
    "gudan": [], 
    "kunda": ['kundaduð', 'kundadun', 'kundada', 'gu-kunda', 'kunda-gūn', 'kundadun-gūn'], 
    "naƥ": ['naƥað', 'naƥan', 'naƥda', 'ga-naƥ', 'naƥ-gān', 'naƥan-gān'], 
    "nukal": [], 
    "kadað": [], 
    "dûquk": [], 
    "gudun": ['gudunað', 'gudunan', 'gudunda', 'a-gudun', 'gudun-dān', 'gudunan-dān'], 
    "kuqar": [], 
    "qul": [], 
    "ād": [], 
    "nux": ['nuxað', 'nuxan', 'nuxda', 'a-nux', 'nux-dān', 'nuxan-dān'], 
    "ûrux": [], 
    "kudunað": ['kudunaðuð', 'kudunaðun', 'kudunaðda', 'gu-kudunað', 'kudunað-gūn', 'kudunaðun-gūn'], 
    "gak": ['gakað', 'gakan', 'gakda', 'a-gak', 'gak-dān', 'gakan-dān'], 
    "kad": [], 
    "rūlaƥ": ['rūlaƥuð', 'rūlaƥun', 'rūlaƥda', 'ga-rūlaƥ', 'rūlaƥ-gān', 'rūlaƥun-gān'], 
    "rūlaður": ['rūlaƥul', 'rūlaƥad', 'rūlaƥudun', 'rūlaƥa', 'rūlaƥu', 'rūlaƥad', 'rūlaƥā', 'rūlaƥū', 'rūlaƥud'], 
    "ūrnakdur": ['ūrnakul', 'ūrnakad', 'ūrnakudun', 'ūrnaka', 'ūrnaku', 'ūrnakad', 'ūrnaqa', 'ūrnaqu', 'ūrnakud'], 
    "dukur": ['dukurað', 'dukuran', 'dukurda', 'a-dukur', 'dukur-dān', 'dukuran-dān'], 
    "ðural": [], 
    "ðuraldur": ['ðuralul', 'ðuralad', 'ðuraludun', 'ðurala', 'ðuralu', 'ðuralad', 'ðuralā', 'ðuralū', 'ðuralud'], 
    "dur": ['durað', 'duran', 'durda', 'ga-dur', 'dur-gān', 'duran-gān'], 
    "duran": [], 
    "lûran": [], 
    "laƥradun": [], 
    "kanāxku": ['kanāxkudað', 'kanāxkudan', 'kanāxkuda', 'ga-kanāxku', 'kanāxku-gān', 'kanāxkudan-gān'], 
    "ðagâral": ['ðagâraluð', 'ðagâralun', 'ðagâralda', 'a-ðagâral', 'ðagâral-dān', 'ðagâralun-dān'], 
    "lunaƥ": ['lunaƥuð', 'lunaƥun', 'lunaƥda', 'ga-lunaƥ', 'lunaƥ-gān', 'lunaƥun-gān'], 
    "ƥûkur": [], 
    "qal": [], 
    "rukula": ['rukuladuð', 'rukuladun', 'rukulada', 'a-rukula', 'rukula-dān', 'rukuladun-dān'], 
    "āl-ðurul": [], 
    "rax": [], 
    "nūƥ": ['nūƥað', 'nūƥan', 'nūƥda', 'ga-nūƥ', 'nūƥ-gān', 'nūƥan-gān'], 
    "nūðar": ['nūƥal', 'nūƥud', 'nūƥudan', 'nūƥa', 'nūƥu', 'nūƥad', 'nuƥā', 'nuƥū', 'nūƥud'], 
    "ruðal": [], 
    "ðagar-ruðal": ['ðagar-ruðaluð', 'ðagar-ruðalun', 'ðagar-ruðalda', 'ga-ðagar-ruðal', 'ðagar-ruðal-gān', 'ðagar-ruðalun-gān'], 
    "narud": ['narudað', 'narudan', 'narûda', 'ga-narud', 'narud-gān', 'narudan-gān'], 
    "narud ðagar-ruðal": ['narud ðagar-ruðaluð', 'narud ðagar-ruðalun', 'narud ðagar-ruðalda', 'ga-narud ðagar-ruðal', 'narud ðagar-ruðal-gān', 'narud ðagar-ruðalun-gān'], 
    "luq": ['luqað', 'luqan', 'luqda', 'a-luq', 'luq-dān', 'luqan-dān'], 
    "nalda": ['naldaduð', 'naldadun', 'naldada', 'a-nalda', 'nalda-dān', 'naldadun-dān'], 
    "ðuruð": ['ðuruðað', 'ðuruðan', 'ðuruðda', 'ga-ðuruð', 'ðuruð-gān', 'ðuruðan-gān'], 
    "qar": [], 
    "qadūr": ['qadūrað', 'qadūran', 'qadūrda', 'a-qadūr', 'qadūr-dān', 'qadūran-dān'], 
    "ƥulað": ['ƥulaðuð', 'ƥulaðun', 'ƥulaðda', 'a-ƥulað', 'ƥulað-dān', 'ƥulaðun-dān'], 
    "ak": ['akað', 'akan', 'akda', 'a-ak', 'ak-dān', 'akan-dān'], 
    "dunāku": ['dunākudað', 'dunākudan', 'dunākuda', 'a-dunāku', 'dunāku-dān', 'dunākudan-dān'], 
    "nākudar": ["nāku'al", 'nākud', 'nākudan', 'nākuda', 'nākudu', 'nākudad', 'nākudā', 'nākudū', 'nākudud'], 
    "nakdur": ['nakul', 'nakad', 'nakadun', 'naka', 'naku', 'nakad', 'naqa', 'naqu', 'nakud'], 
    "xuran": ['xuranuð', 'xuranun', 'xuranda', 'gu-xuran', 'xuran-gūn', 'xuranun-gūn'], 
    "kalaran": [], 
    "lâraquk": ['lâraqukað', 'lâraqukan', 'lâraqukda', 'gu-lâraquk', 'lâraquk-gūn', 'lâraqukan-gūn'], 
    "nâƥal": [], 
    "qadūr-nâƥal": ['qadūr-nâƥaluð', 'qadūr-nâƥalun', 'qadūr-nâƥalda', 'a-qadūr-nâƥal', 'qadūr-nâƥal-dān', 'qadūr-nâƥalun-dān'], 
    "ka'ural": ["ka'uraluð", "ka'uralun", "ka'uralda", "ga-ka'ural", "ka'ural-gān", "ka'uralun-gān"], 
    "rūk": ['rūkað', 'rūkan', 'rūkda', 'a-rūk', 'rūk-dān', 'rūkan-dān'], 
    "qun axa": ['qun axaduð', 'qun axadun', 'qun axada', 'a-qun axa', 'qun axa-dān', 'qun axadun-dān'], 
    "ðar": ['ðarað', 'ðaran', 'ðarda', 'ga-ðar', 'ðar-gān', 'ðaran-gān'], 
    "kûludar": ["kûlu'al", 'kûlud', 'kûludan', 'kûluda', 'kûludu', 'kûludad', 'kûludā', 'kûludū', 'kûludud'], 
    "gâlal": [], 
    "narud gâlal": ['narud gâlaluð', 'narud gâlalun', 'narud gâlalda', 'ga-narud gâlal', 'narud gâlal-gān', 'narud gâlalun-gān'], 
    "nāruk": ['nārukað', 'nārukan', 'nārukda', 'a-nāruk', 'nāruk-dān', 'nārukan-dān'], 
    "nakul": ['nakulað', 'nakulan', 'nakulda', 'a-nakul', 'nakul-dān', 'nakulan-dān'], 
    "nûlar": [], 
    "lurul": [], 
    "ralux": [], 
    "kað": [], 
    "kaðal": [], 
    "kaðadur": ["kaða'ul", 'kaðad', 'kaðadun', 'kaðada', 'kaðadu', 'kaðadad', 'kaðadā', 'kaðadū', 'kaðadud'], 
    "xug-ðura'ul": ["xug-ðura'ulað", "xug-ðura'ulan", "xug-ðura'ulda", "a-xug-ðura'ul", "xug-ðura'ul-dān", "xug-ðura'ulan-dān"], 
    "nud": [], 
    "ƥâladur": ["ƥâla'ul", 'ƥâlad', 'ƥâladun', 'ƥâlada', 'ƥâladu', 'ƥâladad', 'ƥâladā', 'ƥâladū', 'ƥâladud'], 
    "ƥâlukdar": ['ƥâlukal', 'ƥâlukud', 'ƥâlukadan', 'ƥâluka', 'ƥâluku', 'ƥâlukad', 'ƥâluqa', 'ƥâluqu', 'ƥâlukud'], 
    "gundar": ['gunal', 'gunud', 'gunudan', 'guna', 'gunu', 'gunad', 'gunā', 'gunū', 'gunud'], 
    "qulakdur": ['qulakul', 'qulakad', 'qulakudun', 'qulaka', 'qulaku', 'qulakad', 'qulaqa', 'qulaqu', 'qulakud'], 
    "gāl": [], 
    "dukadur": ["duka'ul", 'dukad', 'dukadun', 'dukada', 'dukadu', 'dukadad', 'dukadā', 'dukadū', 'dukadud'], 
    "dukar": ['dukaruð', 'dukarun', 'dukarda', 'ga-dukar', 'dukar-gān', 'dukarun-gān'], 
    "duka'ul": ["duka'ulað", "duka'ulan", "duka'ulda", "gu-duka'ul", "duka'ul-gūn", "duka'ulan-gūn"], 
    "xâlad": ['xâladuð', 'xâladun', 'xâlâda', 'ga-xâlad', 'xâlad-gān', 'xâladun-gān'], 
    "xâladur": ["xâla'ul", 'xâlad', 'xâladun', 'xâlada', 'xâladu', 'xâladad', 'xâladā', 'xâladū', 'xâladud'], 
    "ðun": [], 
    "ðûkundar": ['ðûkunal', 'ðûkunud', 'ðûkunadan', 'ðûkuna', 'ðûkunu', 'ðûkunad', 'ðûkunā', 'ðûkunū', 'ðûkunud'], 
    "ðukun": ['ðukunað', 'ðukunan', 'ðukunda', 'a-ðukun', 'ðukun-dān', 'ðukunan-dān'], 
    "lakdur": ['lakul', 'lakad', 'lakadun', 'laka', 'laku', 'lakad', 'laqa', 'laqu', 'lakud'], 
    "lakur": ['lakurað', 'lakuran', 'lakurda', 'a-lakur', 'lakur-dān', 'lakuran-dān'], 
    "xal": [], 
    "dârul": ['dârulað', 'dârulan', 'dârulda', 'a-dârul', 'dârul-dān', 'dârulan-dān'], 
    "daruldar": ['darulal', 'darulud', 'daruladan', 'darula', 'darulu', 'darulad', 'darulā', 'darulū', 'darulud'], 
    "qaður-luna": [], 
    "ga-luna": [], 
    "nuxur": ['nuxurað', 'nuxuran', 'nuxurda', 'ga-nuxur', 'nuxur-gān', 'nuxuran-gān'], 
    "nuxul": [], 
    "nuxdar": ['nuxal', 'nuxud', 'nuxudan', 'nuxa', 'nuxu', 'nuxad', 'nuxā', 'nuxū', 'nuxud'], 
    "lunakur": ['lunakurað', 'lunakuran', 'lunakurda', 'a-lunakur', 'lunakur-dān', 'lunakuran-dān'], 
    "kalur": ['kalurað', 'kaluran', 'kalurda', 'gu-kalur', 'kalur-gūn', 'kaluran-gūn'], 
    "duqandur": ['duqanul', 'duqanad', 'duqanudun', 'duqana', 'duqanu', 'duqanad', 'duqanā', 'duqanū', 'duqanud'], 
    "duk": ['dukað', 'dukan', 'dukda', 'a-duk', 'duk-dān', 'dukan-dān'], 
    "nārul": ['nārulað', 'nārulan', 'nārulda', 'a-nārul', 'nārul-dān', 'nārulan-dān'], 
    "duqan": ['duqanuð', 'duqanun', 'duqanda', 'a-duqan', 'duqan-dān', 'duqanun-dān'], 
    "kunadur": ["kuna'ul", 'kunad', 'kunadun', 'kunada', 'kunadu', 'kunadad', 'kunadā', 'kunadū', 'kunadud'], 
    "ðulðukdar": ['ðulðukal', 'ðulðukud', 'ðulðukadan', 'ðulðuka', 'ðulðuku', 'ðulðukad', 'ðulðuqa', 'ðulðuqu', 'ðulðukud'], 
    "lagruðaldur": ['lagruðalul', 'lagruðalad', 'lagruðaludun', 'lagruðala', 'lagruðalu', 'lagruðalad', 'lagruðalā', 'lagruðalū', 'lagruðalud'], 
    "kâðadur": ["kâða'ul", 'kâðad', 'kâðadun', 'kâðada', 'kâðadu', 'kâðadad', 'kâðadā', 'kâðadū', 'kâðadud'], 
    "kaðar": ['kaðaruð', 'kaðarun', 'kaðarda', 'ga-kaðar', 'kaðar-gān', 'kaðarun-gān'], 
    "qað": ['qaðað', 'qaðan', 'qaðda', 'a-qað', 'qað-dān', 'qaðan-dān'], 
    "qax": ['qaxað', 'qaxan', 'qaxda', 'gu-qax', 'qax-gūn', 'qaxan-gūn'], 
    "ruðax": ['ruðaxuð', 'ruðaxun', 'ruðaxda', 'gu-ruðax', 'ruðax-gūn', 'ruðaxun-gūn'], 
    "rakundar": ['rakunal', 'rakunud', 'rakunadan', 'rakuna', 'rakunu', 'rakunad', 'rakunā', 'rakunū', 'rakunud'], 
    "kudunaður": ['kudunaƥul', 'kudunaƥad', 'kudunaƥudun', 'kudunaƥa', 'kudunaƥu', 'kudunaƥad', 'kudunaƥā', 'kudunaƥū', 'kudunaƥud'], 
    "nādul": ['nādulað', 'nādulan', 'nādulda', 'ga-nādul', 'nādul-gān', 'nādulan-gān'], 
    "nuƥral": [], 
    "qaƥar": ['qaƥaruð', 'qaƥarun', 'qaƥarda', 'gu-qaƥar', 'qaƥar-gūn', 'qaƥarun-gūn'], 
    "karuð": ['karuðað', 'karuðan', 'karuðda', 'ga-karuð', 'karuð-gān', 'karuðan-gān'], 
    "kar": [], 
    "kalar": ['kalaruð', 'kalarun', 'kalarda', 'ga-kalar', 'kalar-gān', 'kalarun-gān'], 
    "karal": [], 
    "ƥar": [], 
    "rak": [], 
    "nakur": ['nakurað', 'nakuran', 'nakurda', 'a-nakur', 'nakur-dān', 'nakuran-dān'], 
    "nak": [], 
    "laqandur": ['laqanul', 'laqanad', 'laqanudun', 'laqana', 'laqanu', 'laqanad', 'laqanā', 'laqanū', 'laqanud'], 
    "laqan": ['laqanuð', 'laqanun', 'laqanda', 'a-laqan', 'laqan-dān', 'laqanun-dān'], 
    "ðuraƥdur": ['ðuraƥul', 'ðuraƥad', 'ðuraƥudun', 'ðuraƥa', 'ðuraƥu', 'ðuraƥad', 'ðuraƥā', 'ðuraƥū', 'ðuraƥud'], 
    "dunaƥdur": ['dunaƥul', 'dunaƥad', 'dunaƥudun', 'dunaƥa', 'dunaƥu', 'dunaƥad', 'dunaƥā', 'dunaƥū', 'dunaƥud'], 
    "dar": ["da'ul", 'dad', 'dadun', 'da', 'du', 'dad', 'dā', 'dū', 'dud'], 
    "kaxur": ['kaxurað', 'kaxuran', 'kaxurda', 'gu-kaxur', 'kaxur-gūn', 'kaxuran-gūn'], 
    "xalan": [], 
    "kunād": ['kunāduð', 'kunādun', 'kunâda', 'gu-kunād', 'kunād-gūn', 'kunādun-gūn'], 
    "nāk": ['nākað', 'nākan', 'nākda', 'ga-nāk', 'nāk-gān', 'nākan-gān'], 
    "dūradur": ["dūra'ul", 'dūrad', 'dūradun', 'dūrada', 'dūradu', 'dūradad', 'dūradā', 'dūradū', 'dūradud'], 
    "ru": [], 
    "runāxku": ['runāxkudað', 'runāxkudan', 'runāxkuda', 'ga-runāxku', 'runāxku-gān', 'runāxkudan-gān'], 
    "dūrak": ['dūrakuð', 'dūrakun', 'dūrakda', 'ga-dūrak', 'dūrak-gān', 'dūrakun-gān'], 
    "nâlak": ['nâlakuð', 'nâlakun', 'nâlakda', 'ga-nâlak', 'nâlak-gān', 'nâlakun-gān'], 
    "nāxak": ['nāxakuð', 'nāxakun', 'nāxakda', 'ga-nāxak', 'nāxak-gān', 'nāxakun-gān'], 
    "ūrnak": [], 
    "ūrandak": ['ūrandakuð', 'ūrandakun', 'ūrandakda', 'ga-ūrandak', 'ūrandak-gān', 'ūrandakun-gān'], 
    "quƥar": ['quƥaruð', 'quƥarun', 'quƥarda', 'ga-quƥar', 'quƥar-gān', 'quƥarun-gān'], 
    "raqath": ['raqathuð', 'raqathun', 'raqathda', 'a-raqath', 'raqath-dān', 'raqathun-dān'], 
    "ðâlaƥur": ['ðâlaƥurað', 'ðâlaƥuran', 'ðâlaƥurda', 'a-ðâlaƥur', 'ðâlaƥur-dān', 'ðâlaƥuran-dān'], 
    "darað": ['daraðuð', 'daraðun', 'daraðda', 'a-darað', 'darað-dān', 'daraðun-dān'], 
    "duruð": ['duruðað', 'duruðan', 'duruðda', 'a-duruð', 'duruð-dān', 'duruðan-dān'], 
    "draðna": ['draðnaduð', 'draðnadun', 'draðnada', 'a-draðna', 'draðna-dān', 'draðnadun-dān'], 
    "lagadur": ["laga'ul", 'lagad', 'lagadun', 'lagada', 'lagadu', 'lagadad', 'lagadā', 'lagadū', 'lagadud'], 
    "ðuralagdur": ['ðuralagul', 'ðuralagad', 'ðuralagudun', 'ðuralaga', 'ðuralagu', 'ðuralagad', 'ðuralagā', 'ðuralagū', 'ðuralagud'], 
    "dak": ['dakað', 'dakan', 'dakda', 'ga-dak', 'dak-gān', 'dakan-gān'], 
    "dakar": [], 
    "dâkadur": ["dâka'ul", 'dâkad', 'dâkadun', 'dâkada', 'dâkadu', 'dâkadad', 'dâkadā', 'dâkadū', 'dâkadud'], 
    "ðulur": ['ðulurað', 'ðuluran', 'ðulurda', 'ga-ðulur', 'ðulur-gān', 'ðuluran-gān'], 
    "kulur": ['kulurað', 'kuluran', 'kulurda', 'a-kulur', 'kulur-dān', 'kuluran-dān'], 
    "kul": [], 
    "kuldar": ['kulal', 'kulud', 'kuludan', 'kula', 'kulu', 'kulad', 'kulā', 'kulū', 'kulud'], 
    "dūrad": ['dūraduð', 'dūradun', 'dūrâda', 'a-dūrad', 'dūrad-dān', 'dūradun-dān'], 
    "rugulūr": ['rugulūrað', 'rugulūran', 'rugulūrda', 'ga-rugulūr', 'rugulūr-gān', 'rugulūran-gān'], 
    "kalaƥrad": ['kalaƥraduð', 'kalaƥradun', 'kalaƥrâda', 'ga-kalaƥrad', 'kalaƥrad-gān', 'kalaƥradun-gān'], 
    "laƥuldar": ['laƥulal', 'laƥulud', 'laƥuladan', 'laƥula', 'laƥulu', 'laƥulad', 'laƥulā', 'laƥulū', 'laƥulud'], 
    "ƥakuldar": ['ƥakulal', 'ƥakulud', 'ƥakuladan', 'ƥakula', 'ƥakulu', 'ƥakulad', 'ƥakulā', 'ƥakulū', 'ƥakulud'], 
    "urad": [], 
    "raduk": ['radukað', 'radukan', 'radukda', 'a-raduk', 'raduk-dān', 'radukan-dān'], 
    "gulðar": ['gulðaruð', 'gulðarun', 'gulðarda', 'ga-gulðar', 'gulðar-gān', 'gulðarun-gān'], 
    "duqardur": ['duqarul', 'duqarad', 'duqarudun', 'duqara', 'duqaru', 'duqarad', 'duqarā', 'duqarū', 'duqarud'], 
    "ðunuldar": ['ðunulal', 'ðunulud', 'ðunuladan', 'ðunula', 'ðunulu', 'ðunulad', 'ðunulā', 'ðunulū', 'ðunulud'], 
    "nalgudar": ["nalgu'al", 'nalgud', 'nalgudan', 'nalguda', 'nalgudu', 'nalgudad', 'nalgudā', 'nalgudū', 'nalgudud'], 
    "nargul": [], 
    "ƥur-nalgur": ['ƥur-nalgurað', 'ƥur-nalguran', 'ƥur-nalgurda', 'a-ƥur-nalgur', 'ƥur-nalgur-dān', 'ƥur-nalguran-dān'], 
    "lagru": ['lagrudað', 'lagrudan', 'lagruda', 'gu-lagru', 'lagru-gūn', 'lagrudan-gūn'], 
    "aðradur": ["aðra'ul", 'aðrad', 'aðradun', 'aðrada', 'aðradu', 'aðradad', 'aðradā', 'aðradū', 'aðradud'], 
    "âkana": ['âkanaduð', 'âkanadun', 'âkanada', 'a-âkana', 'âkana-dān', 'âkanadun-dān'], 
    "dûrur": [], 
    "dâlar": [], 
    "kaðuk": ['kaðukað', 'kaðukan', 'kaðukda', 'a-kaðuk', 'kaðuk-dān', 'kaðukan-dān'], 
    "kaðurak": ['kaðurakuð', 'kaðurakun', 'kaðurakda', 'a-kaðurak', 'kaðurak-dān', 'kaðurakun-dān'], 
    "âdarul": ['âdarulað', 'âdarulan', 'âdarulda', 'a-âdarul', 'âdarul-dān', 'âdarulan-dān'], 
    "âdalur": [], 
    "âdarul lagdur": ['âdarul lagul', 'âdarul lagad', 'âdarul lagudun', 'âdarul laga', 'âdarul lagu', 'âdarul lagad', 'âdarul lagā', 'âdarul lagū', 'âdarul lagud'], 
    "gudundar": ['gudunal', 'gudunud', 'gudunadan', 'guduna', 'gudunu', 'gudunad', 'gudunā', 'gudunū', 'gudunud'], 
    "gudul": [], 
    "kaðandur": ['kaðanul', 'kaðanad', 'kaðanudun', 'kaðana', 'kaðanu', 'kaðanad', 'kaðanā', 'kaðanū', 'kaðanud'], 
    "xul": ['xulað', 'xulan', 'xulda', 'a-xul', 'xul-dān', 'xulan-dān'], 
    "qaxul": [], 
    "gûladun": ['gûladunað', 'gûladunan', 'gûladunda', 'ga-gûladun', 'gûladun-gān', 'gûladunan-gān'], 
    "lâkar": ['lâkaruð', 'lâkarun', 'lâkarda', 'a-lâkar', 'lâkar-dān', 'lâkarun-dān'], 
    "lâkaxur": ['lâkaxurað', 'lâkaxuran', 'lâkaxurda', 'gu-lâkaxur', 'lâkaxur-gūn', 'lâkaxuran-gūn'], 
    "kadūgul": ['kadūgulað', 'kadūgulan', 'kadūgulda', 'a-kadūgul', 'kadūgul-dān', 'kadūgulan-dān'], 
    "guqudāndur": ['guqudānul', 'guqudānad', 'guqudānudun', 'guqudāna', 'guqudānu', 'guqudānad', 'guqudanā', 'guqudanū', 'guqudānud'], 
    "kundar": ['kunal', 'kunud', 'kunudan', 'kuna', 'kunu', 'kunad', 'kunā', 'kunū', 'kunud'], 
    "āldar": [], 
    "ālnuƥal": [], 
    "naƥāx": ['naƥāxuð', 'naƥāxun', 'naƥāxda', 'ga-naƥāx', 'naƥāx-gān', 'naƥāxun-gān'], 
    "ūrnaƥal": ['ūrnaƥaluð', 'ūrnaƥalun', 'ūrnaƥalda', 'ga-ūrnaƥal', 'ūrnaƥal-gān', 'ūrnaƥalun-gān'], 
    "dūran": [], 
    "dūd": ['dūdað', 'dūdan', 'dûda', 'a-dūd', 'dūd-dān', 'dūdan-dān'], 
    "ƥarūð": ['ƥarūðað', 'ƥarūðan', 'ƥarūðda', 'a-ƥarūð', 'ƥarūð-dān', 'ƥarūðan-dān'], 
    "daraðna": ['daraðnaduð', 'daraðnadun', 'daraðnada', 'a-daraðna', 'daraðna-dān', 'daraðnadun-dān'], 
    "runad": ['runaduð', 'runadun', 'runâda', 'a-runad', 'runad-dān', 'runadun-dān'], 
    "lâkarux": ['lâkaruxað', 'lâkaruxan', 'lâkaruxda', 'ga-lâkarux', 'lâkarux-gān', 'lâkaruxan-gān'], 
    "ruq": ['ruqað', 'ruqan', 'ruqda', 'a-ruq', 'ruq-dān', 'ruqan-dān'], 
    "rûqudar": ["rûqu'al", 'rûqud', 'rûqudan', 'rûquda', 'rûqudu', 'rûqudad', 'rûqudā', 'rûqudū', 'rûqudud'], 
    "dunradur": ["dunra'ul", 'dunrad', 'dunradun', 'dunrada', 'dunradu', 'dunradad', 'dunradā', 'dunradū', 'dunradud'], 
    "lagakdur": ['lagakul', 'lagakad', 'lagakudun', 'lagaka', 'lagaku', 'lagakad', 'lagaqa', 'lagaqu', 'lagakud'], 
    "qulak": ['qulakuð', 'qulakun', 'qulakda', 'a-qulak', 'qulak-dān', 'qulakun-dān'], 
    "na": [], 
    "ðâral": ['ðâraluð', 'ðâralun', 'ðâralda', 'a-ðâral', 'ðâral-dān', 'ðâralun-dān'], 
    "gulak": ['gulakuð', 'gulakun', 'gulakda', 'a-gulak', 'gulak-dān', 'gulakun-dān'], 
    "qanak": ['qanakuð', 'qanakun', 'qanakda', 'a-qanak', 'qanak-dān', 'qanakun-dān'], 
    "rugundar": ['rugundaruð', 'rugundarun', 'rugundarda', 'gu-rugundar', 'rugundar-gūn', 'rugundarun-gūn'], 
    "lagrudar": ["lagru'al", 'lagrud', 'lagrudan', 'lagruda', 'lagrudu', 'lagrudad', 'lagrudā', 'lagrudū', 'lagrudud'], 
    "gulðardur": ['gulðarul', 'gulðarad', 'gulðarudun', 'gulðara', 'gulðaru', 'gulðarad', 'gulðarā', 'gulðarū', 'gulðarud'], 
    "qaðak": [], 
    "dâra": ['dâraduð', 'dâradun', 'dârada', 'a-dâra', 'dâra-dān', 'dâradun-dān'], 
    "rukul": ['rukulað', 'rukulan', 'rukulda', 'a-rukul', 'rukul-dān', 'rukulan-dān'], 
    "rukuldar": ['rukulal', 'rukulud', 'rukuladan', 'rukula', 'rukulu', 'rukulad', 'rukulā', 'rukulū', 'rukulud'], 
    "ƥākul dunradur": ["ƥākul dunra'ul", 'ƥākul dunrad', 'ƥākul dunrudun', 'ƥākul dunrada', 'ƥākul dunradu', 'ƥākul dunradad', 'ƥākul dunradā', 'ƥākul dunradū', 'ƥākul dunradud'], 
    "qaral": [], 
    "qaraldur": ['qaralul', 'qaralad', 'qaraludun', 'qarala', 'qaralu', 'qaralad', 'qaralā', 'qaralū', 'qaralud'], 
    "qalardur": ['qalarul', 'qalarad', 'qalarudun', 'qalara', 'qalaru', 'qalarad', 'qalarā', 'qalarū', 'qalarud'], 
    "ƥaluq": ['ƥaluqað', 'ƥaluqan', 'ƥaluqda', 'ga-ƥaluq', 'ƥaluq-gān', 'ƥaluqan-gān'], 
    "ƥaxuq": ['ƥaxuqað', 'ƥaxuqan', 'ƥaxuqda', 'gu-ƥaxuq', 'ƥaxuq-gūn', 'ƥaxuqan-gūn'], 
    "ƥax": [], 
    "ƥadur": ["ƥa'ul", 'ƥad', 'ƥadun', 'ƥada', 'ƥadu', 'ƥadad', 'ƥadā', 'ƥadū', 'ƥadud'], 
    "ƥârul": ['ƥârulað', 'ƥârulan', 'ƥârulda', 'a-ƥârul', 'ƥârul-dān', 'ƥârulan-dān'], 
    "ƥarūdar": ["ƥarū'al", 'ƥarūd', 'ƥarūdan', 'ƥarūda', 'ƥarūdu', 'ƥarūdad', 'ƥarudā', 'ƥarudū', 'ƥarūdud'], 
    "dūn": ['dūnað', 'dūnan', 'dūnda', 'a-dūn', 'dūn-dān', 'dūnan-dān'], 
    "ƥuradūn": ['ƥuradūnað', 'ƥuradūnan', 'ƥuradūnda', 'a-ƥuradūn', 'ƥuradūn-dān', 'ƥuradūnan-dān'], 
    "xar": [], 
    "dārxad": ['dārxaduð', 'dārxadun', 'dārxâda', 'a-dārxad', 'dārxad-dān', 'dārxadun-dān'], 
    "ƥaxdūn": ['ƥaxdūnað', 'ƥaxdūnan', 'ƥaxdūnda', 'a-ƥaxdūn', 'ƥaxdūn-dān', 'ƥaxdūnan-dān'], 
    "dārðalun": ['dārðalunað', 'dārðalunan', 'dārðalunda', 'a-dārðalun', 'dārðalun-dān', 'dārðalunan-dān'], 
    "ƥâralur": ['ƥâralurað', 'ƥâraluran', 'ƥâralurda', 'a-ƥâralur', 'ƥâralur-dān', 'ƥâraluran-dān'], 
    "qaðardur": ['qaðarul', 'qaðarad', 'qaðarudun', 'qaðara', 'qaðaru', 'qaðarad', 'qaðarā', 'qaðarū', 'qaðarud'], 
    "lūn": [], 
    "nâlaƥuldar": ['nâlaƥulal', 'nâlaƥulud', 'nâlaƥuladan', 'nâlaƥula', 'nâlaƥulu', 'nâlaƥulad', 'nâlaƥulā', 'nâlaƥulū', 'nâlaƥulud'], 
    "nâlaƥur": ['nâlaƥurað', 'nâlaƥuran', 'nâlaƥurda', 'a-nâlaƥur', 'nâlaƥur-dān', 'nâlaƥuran-dān'], 
    "nâlaƥul": [], 
    "ƥaqrul": ['ƥaqrulað', 'ƥaqrulan', 'ƥaqrulda', 'a-ƥaqrul', 'ƥaqrul-dān', 'ƥaqrulan-dān'], 
    "ādqul": ['ādqulað', 'ādqulan', 'ādqulda', 'a-ādqul', 'ādqul-dān', 'ādqulan-dān'], 
    "ural-kadūr": ['ural-kadūrað', 'ural-kadūran', 'ural-kadūrda', 'a-ural-kadūr', 'ural-kadūr-dān', 'ural-kadūran-dān'], 
    }
              
    
        


function write_d() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "ð"
    search()
}

function write_f() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "ƥ"
    search()
}

function write_a() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "ā"
    search()
}

function write_u() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "ū"
    search()
}

function write_doppela() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "â"
    search()
}

function write_doppelu() {
    document.getElementById("searchbar").value = document.getElementById("searchbar").value + "û"
    search()
}

function randomatse() {
    num = Math.floor(Math.random() * Object.keys(lex).length);
    document.getElementById("searchbar").value = Object.keys(lex)[num]
    search()
}


function search() {
    let resultsContainer = document.getElementById("results");
    let resultItems = document.getElementsByClassName("resultItem");
    let input = document.getElementById("searchbar").value
    let wort1 = document.getElementById("wort1")
    let wort2 = document.getElementById("wort2")
    let wort3 = document.getElementById("wort3")
    let wort4 = document.getElementById("wort4")
    let uebersetzung1 = document.getElementById("uebersetzung1")
    let uebersetzung2 = document.getElementById("uebersetzung2")
    let uebersetzung3 = document.getElementById("uebersetzung3")
    let uebersetzung4 = document.getElementById("uebersetzung4")
    let pos1 = document.getElementById("pos1")
    let pos2 = document.getElementById("pos2")
    let pos3 = document.getElementById("pos3")
    let pos4 = document.getElementById("pos4")
    let root1 = document.getElementById("root1")
    let root2 = document.getElementById("root2")
    let root3 = document.getElementById("root3")
    let root4 = document.getElementById("root4")
    let rel1 = document.getElementById("rel1")
    let rel2 = document.getElementById("rel2")
    let rel3 = document.getElementById("rel3")
    let rel4 = document.getElementById("rel4")
    let derv1 = document.getElementById("derv1")
    let derv2 = document.getElementById("derv2")
    let derv3 = document.getElementById("derv3")
    let derv4 = document.getElementById("derv4")


    
    Object.entries(lex).forEach(([key, value])=>{
        if ((input == key) || (value[0].includes(input)) ||gram[key].includes(input)) {
            if ((wort1.innerText)&&(wort1.innerText!=key)) {
                if ((wort2.innerText)&&wort2.innerText!=key) {
                    wort3.innerText = wort2.innerText
                    pos3.innerText= pos2.innerText
                    uebersetzung3.innerText = uebersetzung2.innerText
                    root3.innerText = root2.innerText
                    rel3.innerText = rel2.innerText
                    derv3.innerText = derv2.innerText
                    
                }
                wort2.innerText = wort1.innerText
                pos2.innerText = pos1.innerText
                uebersetzung2.innerText = uebersetzung1.innerText
                root2.innerText = root1.innerText
                rel2.innerText = rel1.innerText
                derv2.innerText = derv1.innerText
            }
            wort1.innerText = key
            uebersetzung1.innerText = value[0].join(", ")
            pos1.innerText = value[1]
            console.log(value[1])
            if (value[1]==['']) {
                console.log("jaja")
            }
            else {
                root1.innerText = "Wurzel: " + value[2][0].join(", ")
                rel1.innerText = "Verwandte Worte: " + value[2][1].join(", ")
                derv1.innerText = "Abgeleitete Worte: " + value[2][2].join(", ")           
            }
        }
        
    })



};
